### ISSUE TITLE
[REQUEST] Progress bars with undetermined 'total'

### ISSUE THREAD

**Issue by azmeuk** [Textualize/rich#1054]
Hi. The documentation describes the usage of [indeterminate progress bars](https://rich.readthedocs.io/en/latest/progress.html#indeterminate-progress) that displays a waiting animation during the time the number of steps is computed.

![indeterminate state](https://media.moyaproject.com/willmcgugan/uploads/thumbnails/techblog/788d9cb6-9e8f-11ea-b769-f23c91845b44.png/788d9cb6-9e8f-11ea-b769-f23c91845b44png.lg.3.jpeg)

However, sometimes you never know how many steps you except (when reading a stream for instance), but this is something rich does not accept:
https://github.com/willmcgugan/rich/blob/1c1d72ccad965a41500253680c73e6606924cd13/rich/progress.py#L667-L673

I suggest in those cases to display a waiting animation instead.

Of course in this case the percentage and the ETA would not be very usable, but the bar could display the number of items processed (this is what tqdm does).

What do you think?

**Comment by willmcgugan** [comment]
Would a [status](https://rich.readthedocs.io/en/latest/console.html#status) not be more appropriate for that?

**Comment by azmeuk** [comment]
Status can do the job if you know the *thing* you iterate on has always an undetermined size. Sometimes you may want to use a progress bar without knowing in advance if the total size could be determined.

**Comment by geoffsmith** [comment]
Just to note a few things that you'd need to do manually with a status that could perhaps be done more cleanly with a progress bar: elapsed time so far, number of units complete so far and the rate of units. TQDM is a nice example of this, if you just leave out a `total` (really enjoying rich so far btw - really lovely library 😄 )

**Comment by Daddy2200** [comment]
> Hi. The documentation describes the usage of [indeterminate progress bars](https://rich.readthedocs.io/en/latest/progress.html#indeterminate-progress) that displays a waiting animation during the time the number of steps is computed.
> 
> 
> 
> ![indeterminate state](https://media.moyaproject.com/willmcgugan/uploads/thumbnails/techblog/788d9cb6-9e8f-11ea-b769-f23c91845b44.png/788d9cb6-9e8f-11ea-b769-f23c91845b44png.lg.3.jpeg)
> 
> 
> 
> However, sometimes you never know how many steps you except (when reading a stream for instance), but this is something rich does not accept:
> 
> https://github.com/willmcgugan/rich/blob/1c1d72ccad965a41500253680c73e6606924cd13/rich/progress.py#L667-L673
> 
> 
> 
> I suggest in those cases to display a waiting animation instead.
> 
> 
> 
> Of course in this case the percentage and the ETA would not be very usable, but the bar could display the number of items processed (this is what tqdm does).
> 
> 
> 
> What do you think?

**Comment by willmcgugan** [comment]
I'm unlikely to get to this any time soon. Opening it up for contributions.

**Comment by mrvkino** [comment]
I will help on this one. Since it is the same as #1528, I guess will take both.

I will look at their override and see if anything is salvageable. @willmcgugan Do you have any comment on their solution or preference on how to proceed (e.g. the use of `float("inf")` vs `None` as a value for `total`)?

**Comment by astrochun** [comment]
> elapsed time so far

Elapsed time would be very nice, particularly when the progress bar hits 100%, it should at least show that instead of time remaining, which is 00:00:00. I suspect some would like elapsed time during run for long jobs, but not as critical for my needs. Perhaps this should be a separate issue?

**Comment by willmcgugan** [comment]
Have a look at `TimeRemainingColumn`. You can set `elapsed_when_finished=True` which displays the elapsed time when it reaches 100%.

The `TimeElapsedColumn` will display just the elapsed time.

**Comment by astrochun** [comment]
> Have a look at `TimeRemainingColumn`. You can set `elapsed_when_finished=True` which displays the elapsed time when it reaches 100%.
> 
> The `TimeElapsedColumn` will display just the elapsed time.

Thanks! I've only touch on `track()` and not `Progress`. Guess I'm now in the advanced settings :-)
