### ISSUE TITLE
[help] How to print text in between `[` and `]`

### ISSUE THREAD

**Issue by avatar-lavventura** [Textualize/rich#1549]
When I try to print any text in between `[ and `]` it is not printed.

For example, `print("[in]")` prints an empty line. How could I prevent this from happening?

**Comment by willmcgugan** [comment]
See [escaping](https://rich.readthedocs.io/en/latest/markup.html#escaping)

**Comment by willmcgugan** [comment]
You will need the `r""` or double up the slashes. But I find it is better to use the escape function if you can.

**Comment by avatar-lavventura** [comment]
I have observed that we don't require any escape function or `\` if the variable inside `{}` is an integer.

```
attempt = 1
log(f"[{attempt}] hello")
log(f"\[{attempt}] hello")
```
prints: 
```
[1] hello
/[1] hello
```

Is it a normal case?
