### ISSUE TITLE
The output with resized window is really confusing

### ISSUE THREAD

**Issue by astroyh** [Textualize/rich#1561]
I really appreciate the beauty of the rich output only if I do not change the size of the window. In fact I am changing the window size all the time for some reason, but the output of the text is changing accordingly, which makes the output a mess. What can I do to disable the automatic resizing ?

**The output of the text when I resize the window some times:**
<img width="771" alt="Snipaste_2021-10-11_21-17-55" src="https://user-images.githubusercontent.com/37318693/136802011-c0db4a56-8227-4eef-a817-b97ceda4b63c.png">
**What I want is like this (the default output):**
<img width="770" alt="image" src="https://user-images.githubusercontent.com/37318693/136801973-9d7ec7b2-009a-45bb-95ee-ff730d5730e6.png">

In fact most terminals could soft-wrap the lines automatically when changing the window size, it is meaningless for rich to resize the output.

**Comment by willmcgugan** [comment]
Rich word wraps by default. Please see [docs](https://rich.readthedocs.io/en/latest/console.html#soft-wrapping).

**Comment by astroyh** [comment]
Thank you! This is exactly what I want.
