### ISSUE TITLE
[help] How can I apply depth control in rich.pretty?

### ISSUE THREAD

**Issue by avatar-lavventura** [Textualize/rich#1585]
[pprint](https://docs.python.org/3/library/pprint.html#pprint.PrettyPrinter) has a `depth` argument in order to control nesting level.

> `depth` controls the number of nesting levels which may be printed; if the data structure being printed is too deep, the next contained level is replaced by .... By default, there is no constraint on the depth of the objects being formatted.

Would it be possible to apply similiar apprach on [`rich.pretty`](https://rich.readthedocs.io/en/stable/pretty.html?highlight=pretty%20) in order to save its results into a file?

**Comment by willmcgugan** [comment]
There isn't a depth parameter ATM. Although it will detect a recursive data structure.

Open to adding one. I will take a look at some point, but would also accept a PR.

**Comment by avatar-lavventura** [comment]
@willmcgugan Thank you sir. If I can accomplish as PR will let you know.

**Comment by willmcgugan** [comment]
v11.0.0 has a max_depth argument for pretty printing
