### ISSUE TITLE
[REQUEST/IDEA] Tree Expand/Collapse

### ISSUE THREAD

**Issue by danieldjewell** [Textualize/rich#1608]
#### Background
So, I'm falling in love with `rich.tree.Tree` 😁 and have several nested trees (not unlike the results of the example: https://github.com/willmcgugan/rich/blob/eb673d1204340738d3084ebc2e4c789a35a4e49b/examples/tree.py) 

#### The Improvement

Things are working great. The only thing that's a bit of a challenge is collapsing/expanding deeply nested trees. It would be awesome to have a couple of methods that would:

* Collapse all nested child tree elements (i.e. recursively set the `Tree.expanded = False` property of all children)
* Expand (reverse of above)
* Choose a depth (or depths, or all) on both of the above 

Effectively something like:
```python
#semi pseudocode
ftree = rich.tree.Tree() #result of the tree dir walk example?

ftree.collapse_all()
ftree.collapse(depth=1)

ftree.expand(depth=1)

#Maybe have an option to include parents of a certain depth too?
ftree.expand(depth=3, parents=True)
```
#### Implementation Notes/Ideas

Not sure which is better:
* Separate `collapse()` and `collapse_all()` methods?
* A single method with a parameter? e.g. `collapse(all=True)` (or maybe just `collapse()` implies all when called without a depth?)

### Other Thoughts
Relatedly, it would be kinda nice to have another mechanism to interact with children beyond a simple list. Maybe having the option to store children as a `dict` (with keys)? (Would be hepful to be able to recursively search children too... but maybe I'm getting a little far ahead 😉 ) 

### **What problem does it solve for you?**

Working with nested trees, convenience.

**Comment by willmcgugan** [comment]
I'd consider a PR to add this functionality.
