### ISSUE TITLE
[REQUEST] pprint should sort unordered collections like `set()` and `dict()`

### ISSUE THREAD

**Issue by zachriggle** [Textualize/rich#1652]
**How would you improve Rich?**

`rich.pretty.pprint` should have the option to sort unordered collections like `set()` and `dict()`.

The same should be possible for the REPL via e.g. `pretty.install`.

**What problem does it solve for you?**

When in a REPL, after `rich.pretty.install()`, it would be nice if printing e.g. `dict` objects were sorted by key.

For compatibility reasons (and since Python3 dict objects are technically ordered by insertion order), this would probably be behind a new flag for `pprint` and `pretty.install`.

For example, it would be nice to have sorted keys for a `dict` ('ExampleToBreakLines' was added to force `pprint` to do line-breaks).

```
{
    'a': 1,
    'c': 3,
    'b': 2,
    'ExampleToBreakLines': 'AAAAAAAAAA...AAAAAAAAAAAA'
}
```

This may cause issues when the values-to-be-sorted (`dict` keys or `set` values) are not comparable (e.g. `TypeError: '<' not supported between instances of 'str' and 'int'`).  However, a best-effort would still be nice.

This should not violate the added functionality of types in `collections` e.g. `OrderedDict`:

```py
>>> isinstance(collections.OrderedDict, dict)
False
```

**Did I help**

Indeed you did help in the Discussions: https://github.com/willmcgugan/rich/discussions/1651

**Comment by willmcgugan** [comment]
I don't think this would be a good idea for dict, since they are sorted. And of a low value for sets.

I may change my mind if there are any more requests for it, but closing for now.

**Comment by emagieika** [comment]
Hey Will, I would like to +1 this issue. It would help a lot in git diffs, as currently I'm seeing a lot of instances with:
```
{
- "a": "*"
- "b": "*"
+ "b": "*"
+ "a": "*"
}
```
in files that are created by this tool.
I see that you've mentioned that dicts are sorted and I see that this should indeed be the case, but maybe I'm doing something wrong?

**Comment by willmcgugan** [comment]
Dicts preserve insertion order. For that reason, the default should remain not sorting the keys. Any sorting would need to be an option, as noted by the OP.

>>> in files that are created by this tool.

What files are you creating?
