### ISSUE TITLE
[REQUEST] rich.inspect() should have a flag to show all contents of a module

### ISSUE THREAD

**Issue by zachriggle** [Textualize/rich#1659]
**How would you improve Rich?**

`rich.inspect()` is really, genuinely great.  I love it! ❤️ 

However, when used on modules, even with `method=True` (see #1658) , it leaves a lot to be desired.  It would be nice if there was a `module=True` flag or similar (even if it only works on `types.ModuleType`) that displays all properties of the module, and does this recursively (e.g. `toplevel.somemodule.SomeClass.some_class_method` would be displayed for `rich.inspect(toplevel.somemodule)`.  Things might get complicated if there are reference cycles (which are probably unlikely, but could be trivially constructed).*

Each object that might be displayed can have its `obj.__module__` checked against `somemodule.__name__` such that nice module documentation can be easily viewed.  The rules for `hidden` and `dunder` can continue to take the same effect that they do.

**What problem does it solve for you?**

I would like `inspect()` to be more useful when inspecting module types.

**What are the pitfalls?**

Cycles probably need to be prevented, so you'll probably need to keep track of the `id()` of all objects traversed to prevent cycles.  Something like this, for example:

```py
# mymodule.py

class MyClass:
    some_class_obj = None

MyClass. some_class_obj = MyClass
```

Or, even more trivially, which is handled correctly by Python's default `repr` and handled very slightly differently in `rich`'s `repr`.  So it does appear that `rich` does some level of `id()` tracking.

```
# Standard Python
>>> x = []
>>> x.append(x)
>>> x
[[...]]
```
```
# With rich.pretty.install()
>>> x = []
>>> x.append(x)
>>> x
[...]
```

**Comment by willmcgugan** [comment]
Inspect has no explicit support for modules. Will consider it for a future update.
