### ISSUE TITLE
[REQUEST] Rich trees should not fill line with spaces, to permit automatic resizing as in macOS Terminal.app and iTerm.app

### ISSUE THREAD

**Issue by zachriggle** [Textualize/rich#1690]
**How would you improve Rich?**

Rich's trees are amazing and amazingly useful.  The extra syntax for specifying links and URLs with OSC8 escape codes is incredibly useful.

However, it seems that the trees fill the rest of the line with space characters, meaning that resizing the window to make it smaller -- even if the content would fit fine -- results in disjoined / separated trees.

This may effect other terminal emulators, but I've only tried macOS terminals.

**What problem does it solve for you?**

Resizing terminal windows breaks things.  Screenshots below.

<img width="203" alt="Screen Shot 2021-11-14 at 11 19 32 PM" src="https://user-images.githubusercontent.com/111640/141721846-08e72636-dca1-4a17-9f3e-0e7f54e7ce18.png">

<img width="201" alt="Screen Shot 2021-11-14 at 11 19 46 PM" src="https://user-images.githubusercontent.com/111640/141721853-8a5c751b-9787-48df-9eae-1015549e3fd1.png">

**Did I help**

Please consider adding a one-time payment option to your Github Sponsor page.

**Comment by willmcgugan** [comment]
fixed
