### ISSUE TITLE
[HELP] Possible to overwrite user input?

### ISSUE THREAD

**Issue by standage** [Textualize/rich#1801]
Consider the following script.

```python
#!/usr/bin/env python
from time import sleep
print("Type a word:")
word = input().strip().upper()
print("\033[F", end="")
for letter in word:
    sleep(0.25)
    print(letter, end="", flush=True)
print("")
```

It prompts the user to type a word, which it then prints back out to the terminal character-by-character overwriting the original user input. See https://asciinema.org/a/460155.

I'd like to take advantage of rich for color, formatting, etc., but the control codes don't seem to play nicely with rich. Any suggestions on how I might be able to do this?

**Comment by standage** [comment]
I guess I can get it to work if I print the control codes with the builtin print function instead of rich's. The following seems to work.

```python
#!/usr/bin/env python
import rich
from time import sleep
rich.print("[cyan]Type a word[/cyan]:")
word = input().strip().upper()
print("\033[F", end="")
colors = ["red", "orange", "yellow", "green", "blue", "indigo", "violet"]
for letter, color in zip(word, colors):
    sleep(0.25)
    rich.print(f"[{color}]{letter}[/{color}]", end="", flush=True)
rich.print("")
```

**Comment by willmcgugan** [comment]
Are you happy with this solution? Feel free to close.

**Comment by standage** [comment]
Thank you for the awesome tool!
