### ISSUE TITLE
[BUG] rich.traceback.install(width: int) is ignored when stderr is not a tty

### ISSUE THREAD

**Issue by pbsds** [Textualize/rich#1809]
Rich traceback output is forced to a width of 80 columns when there is no tty on neither stdout nor stderr:

    ./im_going_to_crash.py  2>&1 | cat

This is in spite of me setting the `width` in `rich.traceback.install` to something else. It is completely ignored and seem to simply use the value `80`.

*Possible inconsistency:*
The function default value seem to be set to `100`, different from `rich.console.Console` which seem to default `width` to `None`.

**Rich version:** 10.16.2

**Comment by willmcgugan** [comment]
When there is no tty, Rich is unable to detect the width of the terminal, and so defaults to a maximum of 80 characters.

If you know the width, you can set the `COLUMNS` environment variable.

**Comment by pbsds** [comment]
Seems it is not set automatically in my shell.

```
$ echo $COLUMNS
174
$ python -c 'import os; print(os.environ.get("COLUMNS"))'
None
```

But when the environ variable is unset and i explicitly provide a `width`, it should be respected or at least raise a warning.

**Comment by willmcgugan** [comment]
Try:

```
export COLUMNS
```

or

```
COLUMN=100 python whatever.py
```

> But when the environ variable is unset and i explicitly provide a width, it should be respected or at least raise a warning.

The width on the traceback sets the desired width. The width on the Console sets the *maximum* width. "respecting" the width on the traceback would result in unreadable output, which would either be clipped or wrapper.

**Comment by taranlu-houzz** [comment]
@willmcgugan I just ran into this issue as well. I use `tmux` on `kitty`. Do you happen to know if there is a way to get `rich` the info it needs about the terminal width automatically (as opposed to setting `COLUMN` manually)? Other automatic `rich` renderables seem to adjust automatically when running within a `tmux` pane, so it seems odd that this issue only affects tracebacks. Maybe there is something else wrong with my setup?

**Comment by taranlu-houzz** [comment]
For more context, I am using `pdm` to develop a namespace package. Within my package, I have an internal module the loads the exception handler using:
```python
import rich.traceback
.
.
.
rich.traceback.install(width=150)
```

The package exposes a cli script which I am currently testing. When I run the script and it raises an error, the `width` setting is not respected (e.g. `pdm run my_script_entry_point --arg1 "boop"`). However, if I just use the same environment to run a simple example like this:
```python
from rich.traceback import install
install(width=150)         


def func():
    raise AssertionError("barf")


func()
```
then the `width` value is used.

**Comment by taranlu-houzz** [comment]
Also, when running my script, I can use `COLUMNS` to reduce the width, but it seems to cap out at 100 regardless of what I set for `width` (I assume since that is the default).
