### ISSUE TITLE
[BUG] jupyter.print takes start-console width as reference for max line width in notebook

### ISSUE THREAD

**Issue by dev-zero** [Textualize/rich#1814]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

I am tryingprinting wide tables, ex.:

```
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Structure   ┃ CP2K       ┃ CP2K       ┃ CP2K       ┃ CP2K       ┃ CP2K       ┃ CP2K       ┃ CP2K       ┃ CP2K       ┃ CP2K       ┃ CP2K      ┃ CP2K      ┃ CP2K      ┃ CP2K      ┃
┃             ┃ DZVP       ┃ DZVP       ┃ DZVP       ┃ DZVP       ┃ TZVP       ┃ TZVP       ┃ TZVP       ┃ TZVP       ┃ TZV2P      ┃ TZV2P     ┃ TZV2P     ┃ TZV2P     ┃ xTB       ┃
┃             ┃ PBE        ┃ PBE0       ┃ TPSS       ┃ ADMM       ┃ PBE        ┃ PBE0       ┃ TPSS       ┃ ADMM       ┃ PBE        ┃ PBE0      ┃ TPSS      ┃ ADMM      ┃           ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Ag2         │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✘✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✘✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓  │ ✓✓✓✓✓✘✓✓  │ ✓✓✓✓✓✓✘✘  │ ✓✓✘✘✘✘✘✘  │
│ AgCl        │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✘✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✘✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓  │ ✓✓✓✓✓✘✓✓  │ ✓✓✓✓✓✓✘✘  │ ✓✓✘✘✘✘✘✘  │
│ Al2O3       │ ✓✓✓✓✓✓✘✘   │ ✓✓✓✓✓✓✘✘   │ ✓✓✓✓✓✘✘✘   │ ✓✓✓✓✓✓✘✘   │ ✓✓✓✓✓✓✘✘   │ ✓✓✓✓✓✓✘✘   │ ✓✓✓✓✓✘✓✓   │ ✓✓✓✓✓✓✘✘   │ ✓✓✓✓✓✓✘✘   │ ✓✓✓✓✓✓✘✘  │ ✓✓✓✓✓✘✘✘  │ ✓✓✓✓✓✓✘✘  │ ✓✓✘✘✘✘✘✘  │
│ Al2S3       │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✘✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✘✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓   │ ✓✓✓✓✓✓✓✓  │ ✓✓✓✓✓✘✓✓  │ ✓✓✓✓✓✓✘✘  │ ✓✓✘✘✘✘✘✘  │
...
```

when making the width of the terminal the jupyter lab server was started from smaller, `print` the table starts to make the columns smaller (ellipsed) and when forced to a fixed width `print` starts to cutoff from the table at the right.
I am currently using the Xeus-python kernel in Jupyter Lab.

**Platform**

The Jupyter Lab server runs on Linux inside a Wezterm Terminal, the browser connecting to it runs on macOS.

```
rich==10.16.2
```

**Comment by willmcgugan** [comment]
Rich has no way of know what the available width in Jupyter, so it choses a fixed width. I don't know of any workaround for this.

**Comment by moleary-earnest** [comment]
FWIW this affects me too. 

I understand your answer @willmcgugan however what confuses me is that if I run something with a shebang "!" (such as `!pip install x`) in a code cell, the output takes the entire width available on the screen.

**Comment by willmcgugan** [comment]
Tables can't wrap in the same way are regular output. If they did, you wouldn't be able to make sense of them.

**Comment by dev-zero** [comment]
@willmcgugan for now it would help if I could fix the assumed width myself inside the notebook. Any hints for that?
For later it might be helpful to patch the output mode to yield an html table instead when within a jupyter notebook, but I guess this is outside of the scope of rich?
