### ISSUE TITLE
[BUG] display width of certain unicode characters

### ISSUE THREAD

**Issue by zmoon** [Textualize/rich#1820]
**Describe the bug**

When I was making <https://twitter.com/zmoon92/status/1479532125443424256>, I tried some longer unicode characters like :snake: (`"\U0001F40D"`/`:snake:`) for the marker, and they messed up the drawing. It seemed like it was taking two characters of space in the row even though it only displays as one on screen, causing an offset in the lines due to the wrapping. The one that I used instead, `"\u263A"`, didn't have that problem.

**Platform**

> What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

Windows Terminal, tried with both Windows PowerShell and Ubuntu WSL 1.

**Comment by willmcgugan** [comment]
It's a difficult problem. The visual width of characters varies from terminal to terminal and platform to platform. Windows is particularly problematic for this, as the choice of font can change things.

We're working on improvements, in the meantime your only option is to test any emojis you use.
