### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by danikiru** [Textualize/rich#1825]
Good evening

i would like to report an issue when using RichHandler.
1. using pycharm, and default Console does not show colors ( only Console(color_system="windows") 
2. in the RichHandler i set console=Console(color_system="windows")
Then i see this
![Screenshot at Jan 11 03-06-05](https://user-images.githubusercontent.com/79114034/148904285-64e6c7e9-f3f7-4211-b605-8110f6b13749.png)

when i set the "show_path" to False ... i see normal text... but i need to see the path

Platform mac
**Platform**

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=233 ColorSystem.EIGHT_BIT>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = '256'                                                         │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 21                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=233, height=21),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=233,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=21,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=233, height=21)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 233                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯

platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)

rich==10.16.2

**Comment by willmcgugan** [comment]
I'm afraid Pycharm only emulates a console, and does so poorly. Suggest using the builtin terminal or iTerm.

**Comment by danikiru** [comment]
i found a work around! 
since i see that everything is displayed FINE with terminal i ran tests using the configuration Python and NOT pytest
![solution](https://user-images.githubusercontent.com/79114034/148995750-f67fa48a-883c-4043-afb4-68ad60e6552c.png)

3 things you need to do as described in image. create Pytest configuration, set the script path to pytest.__main__ and check the EMULATE TERMINAL IN OUTPUT CONSOLE. the last option is the one that fixes everything, unfortunatelly is not available in pytest run configuration. so maybe this tip can help others. BTW....great product
