### ISSUE TITLE
Faulty Progress Bar on Mac

### ISSUE THREAD

**Issue by nellorebhanuteja** [Textualize/rich#1833]
I am using VS Code in MacOS
When I use python interactive window, the progress bar doesn't function properly.

This is my code
```python
from rich.progress import track
import time
months = ['January','February','March']
for month in track(months):
    print(month)
    time.sleep(1)
```

**Comment by willmcgugan** [comment]
Would you mind post a screenshot so I know what is wrong.

**Comment by acbokade** [comment]
@nellorebhanuteja Can you elaborate more on what exactly do you mean by "progress bar not updating properly"? Is it stuck or what exactly is the behavior you are experiencing?

**Comment by nellorebhanuteja** [comment]
@acbokade 
1. Well, the progress bar is stuck (doesn't progress), while other print statements are executing fine. 
2. Some times progress bar keeps blinking.
3. When I run the script in terminal, progress bar is at the bottom of all logs always. Here its on the top and doesn't move.  This makes it difficult to track progress esp. when there are many logs.

**Comment by UltraStudioLTD** [comment]
> @acbokade
> 
> 1. Well, the progress bar is stuck (doesn't progress), while other print statements are executing fine.
> 2. Some times progress bar keeps blinking.
> 3. When I run the script in terminal, progress bar is at the bottom of all logs always. Here its on the top and doesn't move.  This makes it difficult to track progress esp. when there are many logs.

Try running it on Terminal Emulator and see if result is same. Also check VS Code's terminal settings. See if it supports ANSI

**Comment by nellorebhanuteja** [comment]
@UltraStudioLTD 
It is working fine in Terminal Emulator.

Yes, VS code supports ANSI.
Its working fine in VS Code integrated terminal also.

The above behaviour exists in VS Code Python Interactive window.

**Comment by willmcgugan** [comment]
@nellorebhanuteja I gather you are using Jupyter notebooks in VS Code (you might want to lead with that next time).

This works fine in Jupyter outside of VSCode. Could be a bug in VS Code. We will investigate.

**Comment by Tyriar** [comment]
FYI I believe notebooks support very few sequences, ie. it's not using [xterm.js](https://github.com/xtermjs/xterm.js like the main integrated terminal). cc @rebornix

**Comment by darrenburns** [comment]
We've managed to reproduce this in VS Code only, but it appears to be intermittent.

Running the code you supplied in VS Code works sometimes, and sometimes it doesn't. However, when we run this in Jupyter outside of VS Code it works consistently.

We suspect it's a bug in VS Code, so there's nothing we'll be able to do here I'm afraid. Sorry we can't be of more help.
