### ISSUE TITLE
Speed of console.print with rich.table.Table

### ISSUE THREAD

**Issue by mafrosis** [Textualize/rich#1835]
I spent some time porting some code which displays tabular data from using the `tabulate` library to using `rich`. The table has just less than 300 rows, so in most cases we would consider this not a lot of data.

Using `cProfile`, I can see the time for the call to a function `print_table` has blown out from 0.067s to 1.241s. I get similar numbers on each test.

My questions are: is this expected? And, am I doing something obviously wrong?

Code for reference:

(For the record it's not the `df.iterrows()` call which is slow, the profiling shows `venv/lib/python3.9/site-packages/rich/console.py::1545::print` as the culprit.)

With `tabulate`:
```python
def print_table(df: pd.DataFrame):
    '''Helper to pretty print dataframes'''
    click.echo(tabulate(df, headers='keys', tablefmt='psql'))
```

With `rich`:
```python
def print_table(df: pd.DataFrame):
    '''Helper to pretty print dataframes'''
    table = Table()

    # Add the index column header
    table.add_column(df.index.name)

    # Include all remaining column headers
    for col in df.columns.to_list():
        table.add_column(col)

    # Add rows from the passed DataFrame
    for index, row in df.iterrows():
        table.add_row(index, *[str(x) for x in row.to_list()])

    # Render table
    console.print(table)
```

**Comment by willmcgugan** [comment]
The Rich table is quite likely doing a lot more work than tabulate, to support things like word-wrapping, formatting, etc. So I wouldn't expect it to be as fast as tabulate, which is tuned for simpler tables.

That said, your comparison isn't apples to apples. You are timing how long your terminal takes to render the output in addition to how long the libraries take to render. I'd suggest writing the table to a StringIO object to remove that difference. I'd also have Rich and Tabulate rendering similar output, maybe set the table box attribute to `box.ASCII`.

I've also notice that tabulate doesn't handle wide characters by default, you might want to [enable that](https://github.com/astanin/python-tabulate#wide-fullwidth-cjk-symbols) to do a fair comparison.

You might also want to use the timeit library to negate the overhead of profiling.

Even so, I would expect tabulate to be faster. You say 300 rows isn't larger, but that is more than 12 pages of table on a standard terminal rendered in a second. Way faster than you could actually read.

**Comment by mafrosis** [comment]
All good points; I wasn't intending a "fair" comparison, just showing the substantial difference between the two functions - and hoping I was doing something terribly inefficient you could point out 😄 

The thing I really liked about the `rich` version over the `tabulate` version is the wrapping of the text based on the current terminal width. Perhaps all those calculations and string assignments are a bit too much overhead? 1.2s for my end users to print a table is just too slow.

Apologies for appearing to criticise - I love this library and really appreciate your work!

**Comment by mafrosis** [comment]
I notice this in the [`tabulate` docs](https://github.com/astanin/python-tabulate#performance-considerations):

```
=================================  ==========  ===========
Table formatter                      time, μs    rel. time
=================================  ==========  ===========
tabulate (0.8.9)                        472.8         38.0
tabulate (0.8.9, WIDE_CHARS_MODE)       789.6         63.4
```

I wonder, can I save some milliseconds by disabling wide chars in `rich`?

**Comment by willmcgugan** [comment]
12 *pages* of table in 1.2 seconds. As long as your user is not Johnny Nemonic, that's not slow.

**Comment by mafrosis** [comment]
This issue was evidently heading towards a straight close, but I have to disagree with your logic. A `git show` can render thousands of lines of parsed, coloured text in milliseconds. I don't need to be a movie character to find this useful.

Sure the comparison is not apples to apples, but your dismissal of my report is a little sad.
