### ISSUE TITLE
[REQUEST] Add suppress to RichHandler

### ISSUE THREAD

**Issue by daddycocoaman** [Textualize/rich#1836]
**How would you improve Rich?**

Hi. Thanks for the continued work and solving the recent issue (https://github.com/Textualize/rich/issues/1510) for adding suppress to `traceback.install`. Would it be possible to also add this to RichHandler as well so that the Traceback object there also suppresses modules? 

**What problem does it solve for you?**

Performs the same intended actions as addressed in the previous issue. It would also be convenient to do this in the logging handler too.

**Comment by daddycocoaman** [comment]
I can make a PR for this. One thing to settle though; should RichHandler and traceback.install() have different Traceback objects or should they reference the same object with the ability to overwrite `suppress` in either call?

**Comment by willmcgugan** [comment]
Yeah, good idea.

I think that RichHandler should probably grow `tracebacks_suppress` parameter, which gets passed to `emit`.

Thanks for the offer of a PR!

**Comment by willmcgugan** [comment]
Thanks for the PR!
