### ISSUE TITLE
[REQUEST] An interactive selection prompt

### ISSUE THREAD

**Issue by zopanix** [Textualize/rich#1843]
Have you checked the issues for a similar suggestions? => yes

**How would you improve Rich?**

I would love to see rich implement feature like pick, but prettier. (https://pypi.org/project/pick/)

**What problem does it solve for you?**

Currently, I'm using pick for this but I'd like to keep my dependencies to a minimum and since I'm coding a CLI, I would love to the selection prompt more aligned with what I currently have.

**Comment by JoshPaulie** [comment]
Sounds like you want features similar to [Textual](https://github.com/Textualize/textual), which utilizes Rich and is written by the same author. _Apologies if I misunderstood your request._

**Comment by willmcgugan** [comment]
It may happen in the future, but see Textual for more dynamic things.
