### ISSUE TITLE
Text not bold in VS Code on Mac.

### ISSUE THREAD

**Issue by udasitharani** [Textualize/rich#1854]
**Description**
I was toying around with Rich. tried to print a basic "Hello, World!" in bold. Inside VS Code terminal, it doesn't seem to have any effect. But when I run it in Terminal, it works.

This is the code that I am trying to run.

```python
from rich.console import Console

console = Console()
console.print("Hello, World!")
console.print("Hello, World!", style="bold")
```

And this is the output.
<img width="277" alt="Screenshot 2022-01-21 at 1 56 25 AM" src="https://user-images.githubusercontent.com/56196911/150416660-35ebc85a-f23c-46cf-974c-9db49aad0dce.png">

**Platform**
I am using macOS Big Sur.

**Comment by udasitharani** [comment]
The other styles, for example "red", "underline" are working fine.

**Comment by willmcgugan** [comment]
I think that’s an issue with either vscode or your font. If you look really closely, the second line is very slightly bolder, although poorly differentiated.

**Comment by udasitharani** [comment]
I think you are right, I just tried the same with color green, and even though there isn't noticeable difference in font weight, there is significant difference in the brightness of the color.

Thanks, closing the issue.
