### ISSUE TITLE
[BUG] List of numpy arrays does not print correctly

### ISSUE THREAD

**Issue by wilrop** [Textualize/rich#1876]
The bug is actually rather simple. Whenever you attempt to print a list that consists of NumPy arrays, it cuts off the first element of the list when combined with a string. Below is a minimal code example that shows the bug:

```Python
import numpy as np
from rich import print

list_of_arrays = [np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1])]
print(list_of_arrays)
print(f'Does something weird with f strings: {list_of_arrays}')
```
output
```
[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]
Does something weird with f strings: ), array([0, 1, 0]), array([0, 0, 1])]
```
Of course, the output should be that the second line also shows the complete list.
I provide a screenshot below to show what it looks like in my terminal.
![image](https://user-images.githubusercontent.com/34691294/151442356-9e74f36f-0bb1-4b3e-b89f-6d5297554c33.png)

**Platform**
Platform: Mac  
Terminal: Oh-my-zsh  
Python version: 3.7  
Rich version: 11.0.0  

<details>
<summary>Click to expand</summary>
The other information that was asked after executing the commands:
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=197 ColorSystem.EIGHT_BIT>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = '256'                                                         │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> │
│           height = 12                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=197, height=12),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=197,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=12,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=197, height=12)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 197                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯

platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)
</details>

I would be happy to provide any additional feedback if necessary.

**Comment by sanders41** [comment]
It seems to be seeing it as markup.

```py
import numpy as np
from rich import print
from rich.console import Console

console = Console()

list_of_arrays = [np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1])]
print(list_of_arrays)
print(f'Does something weird with f strings: {list_of_arrays}')
console.print(f'Does something weird with f strings: {list_of_arrays}', markup=False)
```

output

```sh
[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]
Does something weird with f strings: ), array([0, 1, 0]), array([0, 0, 1])]
Does something weird with f strings: [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]
```

**Comment by sanders41** [comment]
I tracked it down to [here](https://github.com/Textualize/rich/blob/633faab16dc3a8c01a6562648cc2186c19a476e3/rich/markup.py#L13).

Nested lists are being matched in the regular expression so it isn't specific to NumPy. Any function, class, etc with a list matches. For example:

```py
from array import array
from rich import print

test_list = [array("l", [1, 2]), array("l", [3, 4])]
print(f'test {test_list}')
```

output

```sh
test ), array('l', [3, 4])]
```

I can't currently think of a way to fix this without breaking the markkup. With the current regular expression an escape can be used to prevent the issue.

```py
import numpy as np
from rich import print

list_of_arrays = [np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1])]
print(f'Does something weird with f strings: \{list_of_arrays}')
```

output

```sh
Does something weird with f strings: [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]
```

**Comment by willmcgugan** [comment]
@sanders41 is absolutely correct. It's because the output happens to look like a console markup tag.

One option is to escape the value in the f string. Import `escape` from rich.markup, then do `{escape(str(list_of_arrays))}`.

Alternatively, if you use a Console object, you can disable markup, either globally or on the individual print.

However, you're better off not converting the object to a string at all. If you just print the array, Rich can format and highlight it without escaping issues: 

```python
print("Don't do anything with f string:", list_of_arrays)
```

**Comment by willmcgugan** [comment]
The solution above is probably best. But because this is a common, and natural, thing to do in Python we are going to look at excluding tags that contain parenthesis. This should prevent accidental markup processsing.

**Comment by wilrop** [comment]
Thanks for the follow-up. Excited to see what comes out of this!

**Comment by wilrop** [comment]
I have just retested this old bit of code and it seems to be broken still/again?

Proof: 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/34691294/157677807-3005e485-2d13-462f-9d2a-a693c9970e6f.png">

I'm on Rich 11.2.0 with an M1 mac if that makes a difference.

**Comment by willmcgugan** [comment]
We haven't released a new version yet...

**Comment by wilrop** [comment]
I'm absolutely stupid, for some reason I thought it would already be in there. I'm very sorry!
