### ISSUE TITLE
Diagnostics command

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#1896]
In the issue template we ask folk to run a command at the prompt, but this tends to be pointless for folk who run things in a jupyter notebook.

I think we need to expose the same information via a function.

Something along the following lines:

```python
from rich.diagnostics import report
report()
```

We should also look in to adding Jupyter information in to that report.

**Comment by darrenburns** [comment]
> We should also look in to adding Jupyter information in to that report.

What information are you thinking of here?

**Comment by willmcgugan** [comment]
Investigate env variables, or anything that might be exposed via the ipywidgets api that might give us a clue what the platform is.
