### ISSUE TITLE
[BUG] In Jupyter mode have the link target to "_blank"

### ISSUE THREAD

**Issue by kat25230** [Textualize/rich#1905]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

When using `jupyter.print([link=http://my.cool.link.com]cool link[/link])` and when trying to follow the link it tries to open the link in the resulting cell and getting a broken link. I would suggest to fix this link rendering a bit:
https://github.com/Textualize/rich/blob/master/rich/jupyter.py#L66
by adding the following (`target="_blank"`):
`text = f'<a href="{style.link}" target="_blank">{text}</a>'` so it will open the link in a new window

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```
  
</details>

**Comment by willmcgugan** [comment]
Care to submit a PR for that?

**Comment by wasi-master** [comment]
I'll open a PR

**Comment by kat25230** [comment]
> Care to submit a PR for that?

sorry just saw your message! I see someone already beat me to it :)
Thanks for the quick fix...
