### ISSUE TITLE
[REQUEST] Optional RichHandler Keywords

### ISSUE THREAD

**Issue by aaronst** [Textualize/rich#1906]
**How would you improve Rich?**

Currently, `RichHandler.KEYWORDS` is a class variable containing common HTTP methods.
https://github.com/Textualize/rich/blob/94273ee7030be773542110c0c70809535a08c6eb/rich/logging.py#L46-L55

It would be cool if `RichHandler()` had an optional `keywords` parameter that allowed for a custom set of keywords.

I'd be happy to submit a PR for this, let me know!

**Comment by willmcgugan** [comment]
I don't see why not. Feel free to submit a PR.
