### ISSUE TITLE
[REQUEST] Add box.MARKDOWN

### ISSUE THREAD

**Issue by SomwareHR** [Textualize/rich#1910]
**How would you improve Rich?**

I didn't find this in doc: https://rich.readthedocs.io/en/latest/appendix/box.html#appendix-box

Add an option:

 ` leTable=Table(box=box.MARKDOWN) `

so it can create markdown compatible ascii table:

|  Date      |        Revenue |  Percent |
|------------|----------------|----------|
| 2016-12-31 |    197,925,000 |    0.00% |
| 2017-12-31 |    230,828,000 |   16.62% |

**Comment by willmcgugan** [comment]
Interesting. 🤔

**Comment by wasi-master** [comment]
```markdown
|  Date      |        Revenue |  Percent |
|------------|----------------|----------|
| 2016-12-31 |    197,925,000 |    0.00% |
| 2017-12-31 |    230,828,000 |   16.62% |
```

**Comment by wasi-master** [comment]
So I tried to do this myself and got this
```python
| Header 1  | Header 2 |
|-----------|----------|
| Cell      | Cell     |
| Cell      | Cell     |
|           |          |
| Footer 1  | Footer 2 |
```
| Header 1  | Header 2 |
|-----------|----------|
| Cell      | Cell     |
| Cell      | Cell     |
|           |          |
| Footer 1  | Footer 2 |

With the following code
```python
MARKDOWN: Box = Box(
    """\
    
| ||
|-||
| ||
|-||
| ||
| ||
    
""",
    ascii=True,
)
```

I can open a PR if @willmcgugan is intrested

**Comment by willmcgugan** [comment]
@wasi-master Does that always produce the expected output?

If you have a lot of text in a cell and it wraps, it looks like that might generate multiple rows.

@SomwareHR 's idea is a good one, but if it doesn't work all the time its a non-starter.

**Comment by willmcgugan** [comment]
On reflection, Rich tables may produce invalid MD markup. So I'm afraid this wouldn't be a good idea.
