### ISSUE TITLE
[BUG] MyPy Errors Reported in 10.16.3

### ISSUE THREAD

**Issue by bphunter1972** [Textualize/rich#1913]
**Describe the bug**

This _probably_ isn't a bug in rich, but maybe somebody with a better understanding can explain it. Or maybe somebody else is having the same issue and it's not just me.

Since updating from rich=10.15.0 to 10.16.3, mypy in VS Code has been reporting 9 errors and 1 warning in all of my projects that use rich, and all of the issues are found in the installed rich package.

However, if I run mypy or even dmypy from the command-line, it finds no issues. ¯\_(ツ)_/¯

**Platform**
mypy running on CentOS 7 via Remote SSH
VS Code running on OS Catalina
Python 3.8.8
mypy 0.910

<img width="1186" alt="Screen Shot 2022-02-03 at 09 29 50" src="https://user-images.githubusercontent.com/5446342/152396426-306ed38a-f413-40e5-84c1-89e4e18f23cb.png">

**Comment by sanders41** [comment]
Do you have a settings.json file for VS Code and if so does it have anything for mypy? It looks like mypy is running on your virtual environment for some reason.

**Comment by bphunter1972** [comment]
Yes, but there's just this:
```
    "python.linting.enabled": true,
    "python.linting.mypyEnabled": true
```

MyPy is intentionally running on my virtual environment because the whole application--including mypy--lives in a poetry-created virtual environment.

**Comment by sanders41** [comment]
Right, but you want mypy running on your code, not all your installed packages. That said I to recreate the problem and wasn't able to. I didn't try it over ssh so possibly that has something to do with it.

You could add settings for for mypy to ignore these missing imports, but in this case it seems like something else is going on and that isn't the best fix. Or maybe I am misunderstanding your setup and this is the way to solve the issue.

**Comment by bphunter1972** [comment]
That's true. 
Well, I'm stumped, too. But in any case adding this to my pyproject.toml seems to have solved it:

```
[tool.mypy]
[[tool.mypy.overrides]]
module = "rich"
ignore_missing_imports = true
```

Hopefully this helps somebody else someday.
