### ISSUE TITLE
[BUG] Whitespace characters not retained properly on copy and paste out of Terminal compared to stdlib print

### ISSUE THREAD

**Issue by jturmel** [Textualize/rich#1921]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

Copying the output from a terminal window doesn't seem to copy whitespace characters correctly. We have outputs that sometimes use tabs "\t" between values so that it can be copied and pasted into a spreadsheet, we've recently switched some stuff to Rich instead of just Python's stdlib print and now when pasting into spreadsheets the tabs aren't retained, so it just pastes all in one cell.

Provide a minimal code example that demonstrates the issue if you can. If the issue is visual in nature, consider posting a screenshot.

console.print(f"{invoice_number}\t{dateparser.parse(invoice_date_paid).year}\t{invoice_date_paid}\t{Decimal(invoice_amount)}")

Then paste into spreadsheet.

**Platform**
Mac M1
Excel or Google Spreadsheets
iTerm 2

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=158 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 25                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=158, height=25),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=158,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=25,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=158, height=25)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 158                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)
rich==11.1.0

**Comment by willmcgugan** [comment]
Rich in general does not guarantee cut & paste will produce exactly what you printed. Word-wrapping for instance will insert new lines. In your case, Rich is converting tabs to spaces. This is because tabs make it difficult to do any additional formatting.

If preserving tabs is important, you can bypass Rich processing with `console.file.write`.

**Comment by jturmel** [comment]
Would you be open to a PR that allows skipping `expand_tabs` on a per print call?

For now I'm just going to monkey patch it for my use case but thought that might be helpful for someone else that may need this sort of thing.
