### ISSUE TITLE
[REQUEST] Convert instances of string.format() and % string substitution to f-strings

### ISSUE THREAD

**Issue by dr-nugget** [Textualize/rich#1933]
Have you checked the issues for a similar suggestions? Yes

**How would you improve Rich?**

Hello. In examples/print_calendar.py, examples/dynamic_progress.py, and rich/filesize.py, there are uses of the string.format() or % format string substitution where more readable f-strings could be used:

(leading whitespace is stripped)

**examples/print_calendar.py**, lines 39-41
```python
table.add_column(
    "{:.3}".format(calendar.day_name[week_day]), justify="right"
)
```

**examples/dynamic_progress.py**, lines 94-118
```python
    # update message on overall progress bar
    top_descr = "[bold #AAAAAA](%d out of %d apps installed)" % (idx, len(apps))
    overall_progress.update(overall_task_id, description=top_descr)

    # add progress bar for steps of this app, and run the steps
    current_task_id = current_app_progress.add_task("Installing app %s" % name)
    app_steps_task_id = app_steps_progress.add_task(
# Snip...
    current_app_progress.update(
        current_task_id, description="[bold green]App %s installed!" % name
    )
# Snip...
overall_progress.update(
    overall_task_id, description="[bold green]%s apps installed, done!" % len(apps)
)
```

**rich/filesize.py**, line 30
```python
return "{:,} bytes".format(size)
```

These could all be replaced with f-strings:

```python
# examples/print_calendar.py, line 40
   f "{calendar.day_name[week_day]:.3}", justify="right"

# examples/dynamic_progress.py, lines 94-118
    # update message on overall progress bar
    top_descr = f"[bold #AAAAAA]({idx} out of {len(apps)} apps installed)"
    overall_progress.update(overall_task_id, description=top_descr)

    # add progress bar for steps of this app, and run the steps
    current_task_id = current_app_progress.add_task(f"Installing app {name}")
    app_steps_task_id = app_steps_progress.add_task(
# Snip...
    current_app_progress.update(
        current_task_id, description=f"[bold green]App {name} installed!"
    )
# Snip...
overall_progress.update(
    overall_task_id, description=f"[bold green]{len(apps)} apps installed, done!"
)

# rich/filesize.py, line 30
return f"{size:,} bytes"
```

(All of these pieces of code were found using a search of the repo in my editor using the regular expression `(['"].*%\w.*['"])|(['"].*['"]\.format\(.*\))`, which, by the way, turned up many false positives related to time formats.)

**What problem does it solve for you?**

As stated earlier, f-strings are more readable than these other substitution methods, and also more consistent. These parts of the codebase would be easier to read and maintain.

If this gets accepted, I'd be happy to do the work and write the implementation and create a PR.

**Did I help**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
There is very low benefit in change these. However, if you want to do the work I would be happy to merge a PR!
