### ISSUE TITLE
How can I add speed process to rich.progress.track? Is it possible?

### ISSUE THREAD

**Issue by Msameim181** [Textualize/rich#1964]
Rich is wonderful, but I think it needs to be at least as good as '**tqdm**' is in a simple example.

When I want to process data in for loops, I want to tell me about the **'speed'**. that speed helps me to improve performance. Also, I need the **'total time'** of the process at the end.

Is it possible to add these items to ```rich.progress.track```? should I use different functions or libraries?

This is my for loop:
```
for ndf_addr, image_addr in track(zip(ndfs_addr, images_addr), total=len(ndfs_addr), 
                                        description="Processing data..."):
   ...

```

**Comment by willmcgugan** [comment]
You have two options: keep using tqdm, or read the docs on Rich progress bars.
