### ISSUE TITLE
[REQUEST] RichHandler Time Zones

### ISSUE THREAD

**Issue by aaronst** [Textualize/rich#1972]
https://github.com/Textualize/rich/blob/8c3e6be424f36522cbb3c4773e58a01f5f39761f/rich/logging.py#L198

Currently, `RichHandler.render()` converts the `record.created` into a local `datetime` with `datetime.fromtimestamp`. I would love to have the ability to output time in UTC, and I suppose some people might want other specific time zones.

In `logging`, we can control this with a custom `Formatter` class, but I think `RichHandler` ignores that.

It might be really nice if `RichHandler` had a `log_time_tz: datetime.tzinfo | None = None` parameter that would be passed to `datetime.fromtimestamp(record.created, tz=self.log_time_tz)`. This would allow for users to specify any timezone they want, including UTC.

As always, happy to submit a PR if we think this is a reasonable feature!

**Comment by willmcgugan** [comment]
RichHandler already has a really large number of parameters. I’d prefer not to make it larger. I’d suggest extending the class and customising render() for now, if you need this.

**Comment by aaronst** [comment]
Makes sense, thanks for taking a look.

**Comment by con-f-use** [comment]
Sorry for the necro, but it also seems to ignore or cut off the `%z` timezone (or uses time objects where that info is not attached). I.e. with `"log_time_format": "%Y-%m-%dT%H:%M:%S%z"`, for me, it prints:

```
2025-07-04T19:14:40 DEBUG    debug message                                                                                                                                           main.py:26
2025-07-04T19:14:41 INFO     info message                                                                                                                                            main.py:28
```

where it should be something like `2025-07-04T19:14:41+0200`.

@willmcgugan
