### ISSUE TITLE
[BUG] console style is not applied to Live.renderable

### ISSUE THREAD

**Issue by Solvero** [Textualize/rich#1974]
**Describe the bug**
Console style is not applied to renderable updated in rich.live.Live(...).
See code example.

**Platform**
Ubuntu 20.04.3 LTS
Python 3.9.1
*rich* version: 11.2.0
<details>
<summary>code example</summary>

Table generated from below code is white although console style is set to red.
```
from rich.console import Console
from rich.live import Live
from rich.table import Table

console = Console(style="red")

t = Table("ID", "NAME", title="title")
t.add_row("0", "A")
t.add_row("1", "A")

with Live(t, console=console) as l:
    for row in range(12):
        time.sleep(0.4)
        l.update(t)
        # l.console.print(t)  # This prints table correctly with red
```
</details>

**Comment by willmcgugan** [comment]
This is correct, the console.style affects things you print. If you want to apply a style in another context, you can do the following:

```python
from rich.styled import Styled
l.update(Styled(t, "red"))
```
