### ISSUE TITLE
[REQUEST] Mention highlight=false in quickstart example

### ISSUE THREAD

**Issue by mborus** [Textualize/rich#1977]
Hi, I'm just beginning to use Rich and have one comment
to help others get started

Rich hightlights numbers and other elements and this behaviour may be unwanted
when you get started and just want to add some color to text.

You can turn it off with the "highlight=False" paramter. When you're getting started,
you **may not know that** this behaviour is called "highlight", so it's **hard to find out how to turn it off**.

The **quick start** section has the text 
"Rich will do some basic syntax **highlighting** and format data structures to make them easier to read."

If you linked the word "highlighting" to the Highlighting section, it would have helped me to quickly know
how to turn this off.

**Comment by willmcgugan** [comment]
Done.
