### ISSUE TITLE
[QUESTION] How to save_html while using Progress

### ISSUE THREAD

**Issue by AnthoBalitrand** [Textualize/rich#1978]
Need some help here if possible : 
how to render a readable output using console.save_html() while having Progress objects ? 

The Progress outputs are also wrote on the html (which makes it unreadable), while I would like to export only logged stuff. 

Thanks for your help !

**Comment by willmcgugan** [comment]
You can set `disable=console.record` on the Progress bar.

**Comment by AnthoBalitrand** [comment]
Yes but in this case I have to choose between having my progress bar displayed and generating a report :-) 
Isn't it possible to have only the console logged events put on the html report, while the progress bar is just displayed ?

**Comment by willmcgugan** [comment]
Not currently I'm afraid. Perhaps anything dynamic should be removed from the record buffer. Will consider that.

**Comment by willmcgugan** [comment]
Tracking here https://github.com/Textualize/rich/issues/2213

**Comment by AnthoBalitrand** [comment]
Thank you for taking it into account @willmcgugan ! I"ll follow #2213
