### ISSUE TITLE
CONTRIBUTING.md guidlines inadequate

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#1997]
We should review and update CONTRIBUTING.md from the point of view of a beginner starting afresh.

Assume a blank slate, for someone with basic Python skills but no experience contributing to open source

- List of pre-requisits for working with Rich
- Instructions on how to checkout the repo, install poetry, and run Rich (within poetry shell)
- Instructions how to submit a PR for review.

Doesn't have to be too detailed. Just enough to get started. Linking to high-quality tutorials (ideally official for GitHub / Poetry) would be great.

**Comment by darrenburns** [comment]
This has been in "todo" for a while, but there's not really any information on what you'd like to see in it which is why it hasn't been picked up.

**Comment by willmcgugan** [comment]
@darrenburns better?
