### ISSUE TITLE
 [BUG] tests.test_segment.test_repr failing on Windows / 3.10.0b3

### ISSUE THREAD

**Issue by ilanjb** [Textualize/rich#2003]
I wanted to contribute to Rich following the guidlines [here ](https://github.com/Textualize/rich/blob/41279bca20fefdfe7edf4414f80745da4fb13849/CONTRIBUTING.md) and ran into this issue on the test suite.  Maybe this fix can be my first contribution? 

PS C:\Users\ilanb\PycharmProjects\rich> python -m pytest .\tests\test_segment.py  -k test_repr
================================================================================= test session starts ==================================================================================
platform win32 -- Python 3.10.0b3, pytest-7.0.1, pluggy-1.0.0
rootdir: C:\Users\ilanb\PycharmProjects\rich\tests, configfile: pytest.ini
plugins: cov-3.0.0
collected 48 items / 47 deselected / 1 selected

tests\test_segment.py F                                                                                                                                                           [100%]

======================================================================================= FAILURES ======================================================================================= 
______________________________________________________________________________________ test_repr _______________________________________________________________________________________ 

    def test_repr():
        assert repr(Segment("foo")) == "Segment('foo')"
        home = (ControlType.HOME, 0)
>       assert (
            repr(Segment("foo", None, [home]))
            == "Segment('foo', None, [(<ControlType.HOME: 3>, 0)])"
        )
E       assert "Segment('foo...pe.HOME, 0)])" == "Segment('foo...OME: 3>, 0)])"
E         - Segment('foo', None, [(<ControlType.HOME: 3>, 0)])
E         ?                        -                ----
E         + Segment('foo', None, [(ControlType.HOME, 0)])

tests\test_segment.py:12: AssertionError
=============================================================================== short test summary info ================================================================================ 
FAILED tests\test_segment.py::test_repr - assert "Segment('foo...pe.HOME, 0)])" == "Segment('foo...OME: 3>, 0)])"

**Comment by willmcgugan** [comment]
I can see you're using *beta 3* of Python 3.10. The enum repr was briefly changed in the beta but reverted in the release version.

Update Python and this test will pass...

**Comment by ilanjb** [comment]
Well that was fast!

Ilan Brandvain
אילן ברנדווין

**Comment by ilanjb** [comment]
Not a bug
