### ISSUE TITLE
[BUG] progress bar not unique

### ISSUE THREAD

**Issue by zlj-zz** [Textualize/rich#2009]
<img width="958" alt="图片" src="https://user-images.githubusercontent.com/27907644/155888652-d9ce6ec0-89cc-475d-a143-3929013ca82a.png">

```python
from rich.console import Console
from rich.progress import track

console = Console()

  for chapter_name, url in track(res, desc):
            console.print(chapter_name, url)
```

**Comment by willmcgugan** [comment]
You will need to use the same console for printing and for the progress bars. Pass `console=console` to `track`.

**Comment by zlj-zz** [comment]
It's great, thanks.
