### ISSUE TITLE
[BUG] Should RichHandler default to stderr

### ISSUE THREAD

**Issue by rdburns** [Textualize/rich#2022]
**Describe the bug**

"Bug" is a little strong, but I noticed that by default Python logging writes to stderr, but when using RichHandler by default it writes to stdout.

I know you can get around this with something like:

``` python
logging.basicConfig(
    level="DEBUG", datefmt="[%X]", handlers=[RichHandler(console=Console(stderr=True))]
)
```

But would it be more sensible and less surprising for new users if by default RichHandler logged to stderr?

**Comment by willmcgugan** [comment]
If you are implying it is not sensible and is surprising, I'd like to know why...

**Comment by willmcgugan** [comment]
Will need an argument one way or the other...

**Comment by rdburns** [comment]
I just found that it seemed unexpected if python logging writes to stderr by default, I expected the Rich Handler to do the same. Isn’t that generally what one would expect? I might be wrong about that. I don’t think it’s a huge issue, but in my app I was piping the output somewhere and it’s nice for logging to not be mixed into the output stream if it’s a unix-y style terminal application.

**Comment by willmcgugan** [comment]
It would be surprising for some users if they piped the output and it didn't appear. Having the handler share an internal console also allows for logging to be used in conjunction with progress bars. Like you said, its trivial to make it work however you want.

**Comment by imdoroshenko** [comment]
This bug caused issues in my CLI app because logs were mixed with the app output and caused errors when piping. I feel that by default rich should avoid unexpected behaviour.

**Comment by frans-fuerst** [comment]
I'd also consider this a bug - lots (if not most) of cli tools write errors and debug to `stderr` while the (often parse-able) output goes to `stdout` and might be piped to another tool which now would have to guess whether a line is (optional) logging output, some error message or actual data it should process. eg: `ssh -vv <user>@<machine> <command> | <next-tool> | <next-tool> ..` would be quite hard to handle if every tool needed to know the (often flexible) logging format of it's predecessor.

(This is true for every other (at least Posix based) tool I know, correct me if I'm wrong)

If you need both `stderr` and `stdout` you can easily redirect them using e.g. `2>&1`. But without logging/error messages being sent to `stderr` there is no trivial way to separate them.

**Comment by ryandward** [comment]
Lovely package, but I was getting invalid `json` output for the reasons above. Pretty unexpected imo.

**Comment by simonwiles** [comment]
Yeah, this just cost me longer than I'd care to admit before I realized that `RichHandler` in the mix was the cause of my problem.  For my part I can't see a single good argument for changing the behaviour of the `logging` module in this respect.

**Comment by rdburns** [comment]
For the record i am still holding my initial opinion that logging should default to stderr as it does normally with the logging module.

**Comment by envp** [comment]
> I also think that the RichHandler should not change default logger behaviour, ie. it should log to stderr by default.
> 
> > It would be surprising for some users if they piped the output and it didn't appear
> 
> Anyone using `RichHandler` is already using python logging, and therefore expecting log output to go to stderr. It is more surprising for logging to _not_ go to stderr.
> 
> This is a bug, IMO.

Agreed. Python logging defaults to stderr and for a handler to change that contract without explicitly is going to introduce footguns with broken json etc (something I just ran into today!)

**Comment by AncientPatata** [comment]
Python logging defaults to stderr, I also think that RichHandler should respect that behavior by default.

**Comment by robinbowes** [comment]
@willmcgugan Any chance of re-considering your decision to close this bug?

**Comment by willmcgugan** [comment]
@robinbowes Nothing has changed that I am aware of.

**Comment by robinbowes** [comment]
> [@robinbowes](https://github.com/robinbowes) Nothing has changed that I am aware of.

What's changed is that there have been several follow-ups, all expressing a view the the effect of (and I'm paraphrasing here):

"Python logging defaults to stderr. A logging handler should not change that behaviour."

ie. several people do think that the default behaviour is not sensible and is surprising, and have given examples of how this unexpected behaviour has caused them problems.

In view of these views, might you reconsider your position on this?

**Comment by robinbowes** [comment]
You're conflating "stdout vs stderr" with "tty vs. file"

Program output should go to stdout; log output should go to stderr.

The decision to produce rich output should be based on to what the file descriptor is connected, ie. tty or file/pipe.

Regardless of whether writing to stdout or stderr, I would expect this logic:

```
If writing to a tty:
    use rich output
else:
    use plan output 
```

I totally understand the inertia preventing a change of default behaviour, but it would be great to be able to opt in to this behaviour when initialising RichHandler.

> "fix" it with a single line

Out of curiosity, what would this look like?
