### ISSUE TITLE
[REQUEST] prevent expansion of certain columns

### ISSUE THREAD

**Issue by nschloe** [Textualize/rich#2030]
I'd like to be able to expand certain columns and keep others at a fixed width. This is possible right by now by setting `expand=True` on the table and setting `ratio=1` (?) in the columns that can be expanded (see [this discussion](https://github.com/Textualize/rich/discussions/1526)):
```python
from rich.table import Table
from rich.text import Text
from rich import print


t = Table(box=None, padding=0, expand=True)
t.add_column(Text("x", justify="left"), justify="right", ratio=1)
t.add_column(Text("y", justify="left"), justify="right")
t.add_row("12", "12")
t.add_row("1234", "1234")

print(t)
```
```
x                                     y   
                                    12  12
                                  12341234
```
This is a little weird. A better API would be to have an `expand` attribute in each column that overrides the table's `expand`.

**Comment by willmcgugan** [comment]
I think this may be more of a documentation issue.

The docs don't go in to detail regarding how the options for columns and the Table can be used to define the behaviour. The `ratio` can be used to define proportional column widths, e.g. a column that takes up 2/3 of the width, and another that takes the remaining third. You can also mix fixed size, and flexible columns together. These can be used with auto-width, fixed width, or expand to generate flexible layouts.

Your idea for the expand attribute would I'm afraid break some of this functionality.

**Comment by nschloe** [comment]
You're right, `ratio` and `expand=True/False` would be competing, so that's probably not a good idea.

I bumped into the issue trying to set a fixed with on a column in an `expand`ed table:
```python
from rich.table import Table
from rich.text import Text
from rich import print


t = Table(box=None, padding=0, expand=True)
t.add_column(Text("x", justify="left"), justify="right")
t.add_column(Text("y", justify="left"), justify="right", width=5, max_width=5)
t.add_row("12", "12")
t.add_row("1234", "1234")

print(t)
```
```python
x                  y                      
                 12                     12
               1234                   1234
```
It's weird that `expand` overrides the `[max_]width` attributes here. One has to set `ratio=1` in all _other_ columns to get `width=5`. What do you think about this?

**Comment by willmcgugan** [comment]
The problem is that you haven't allowed any column to expand there. x and z will fit their content, y has a width of 5. If the table is to expand it can't respect those constraints.

In that situation Rich will expand columns based on their maximum size.

In general, if you want to expand a table you will need to allow at least one column to expand with a non-zero `ratio`.

**Comment by nschloe** [comment]
> The problem is that you haven't allowed any column to expand there. 

This I don't understand. Is this implicit? I never disallowed the first and third column. I would have expected that, when setting `expand=True` on the whole table, all columns are expanded at will except the ones where I set additional constraints, e.g., `width`, `max_width`, or `min_width`.
