### ISSUE TITLE
Need objects.inv for intersphinx_mapping

### ISSUE THREAD

**Issue by shahzebsiddiqui** [Textualize/rich#2039]
Hello @willmcgugan 

I would like to use intersphinx_mapping https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html to document rich  API in my codebase. I added the following in my `conf.py` but it failed to load. It turns out that it is trying to fetch objects.inv 

```
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "rich": ("https://rich.readthedocs.io/", None),
}
```

This is the error message from the `make html`

```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://rich.readthedocs.io/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://rich.readthedocs.io/objects.inv
```

The python docs has one in its top-level directory https://docs.python.org/3/objects.inv which can be downloaded.  Can you please tell me where this file is located so i can get this hooked up to my project

**Comment by willmcgugan** [comment]
Try https://rich.readthedocs.io/en/stable/
