### ISSUE TITLE
[BUG] Table column truncates despite no_wrap=False when it contains pipe character

### ISSUE THREAD

**Issue by NSBum** [Textualize/rich#2048]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

The `no_wrap` option when set to False on a column should allow the column content to wrap. This does not work when the text of a row contains the pipe character. In this situation, the `no_wrap=False` flag is not respected and the the content is truncated. This is only the case when a `|` character is present in the string.

Provide a minimal code example that demonstrates the issue if you can. If the issue is visual in nature, consider posting a screenshot.

### Text with `|` character

<img width="648" alt="Screen Shot 2022-03-11 at 5 39 19 AM" src="https://user-images.githubusercontent.com/10759859/157852842-2493cd0a-54d2-473a-bd34-fdf476f96f91.png">

```
from rich.console import Console
from rich.table import Table

table = Table(title='Test')
table.add_column('Text')
table.add_column('Wrap', no_wrap=False)

text = "This|is|a|bunch|of|text|that|should|wrap|,|but|does|it|actually|wrap|blah|blah|blah|blah|blah|"
table.add_row("Foo", text)

console = Console()
console.print(table)
```

### Text _without_ `|` character

<img width="655" alt="Screen Shot 2022-03-11 at 5 41 02 AM" src="https://user-images.githubusercontent.com/10759859/157853127-dfcff8c3-93de-4587-baae-df3ce2b46945.png">

```
from rich.console import Console
from rich.table import Table


table = Table(title='Test')
table.add_column('Text')
table.add_column('Wrap', no_wrap=False)

text = "This|is|a|bunch|of|text|that|should|wrap|,|but|does|it|actually|wrap|blah|blah|blah|blah|blah|"
text = text.replace('|', ', ')
table.add_row("Foo", text)

console = Console()
console.print(table)
```

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

macOS, iTerm, ZSH

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```
rich==12.0.0
╭─────────────────────── <class 'rich.console.Console'> ────────────────────────╮
│ A high level console interface.                                               │
│                                                                               │
│ ╭───────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=81 ColorSystem.TRUECOLOR>                                  │ │
│ ╰───────────────────────────────────────────────────────────────────────────╯ │
│                                                                               │
│     color_system = 'truecolor'                                                │
│         encoding = 'utf-8'                                                    │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w'                │
│                    encoding='utf-8'>                                          │
│           height = 28                                                         │
│    is_alt_screen = False                                                      │
│ is_dumb_terminal = False                                                      │
│   is_interactive = True                                                       │
│       is_jupyter = False                                                      │
│      is_terminal = True                                                       │
│   legacy_windows = False                                                      │
│         no_color = False                                                      │
│          options = ConsoleOptions(                                            │
│                        size=ConsoleDimensions(width=81, height=28),           │
│                        legacy_windows=False,                                  │
│                        min_width=1,                                           │
│                        max_width=81,                                          │
│                        is_terminal=True,                                      │
│                        encoding='utf-8',                                      │
│                        max_height=28,                                         │
│                        justify=None,                                          │
│                        overflow=None,                                         │
│                        no_wrap=False,                                         │
│                        highlight=None,                                        │
│                        markup=None,                                           │
│                        height=None                                            │
│                    )                                                          │
│            quiet = False                                                      │
│           record = False                                                      │
│         safe_box = True                                                       │
│             size = ConsoleDimensions(width=81, height=28)                     │
│        soft_wrap = False                                                      │
│           stderr = False                                                      │
│            style = None                                                       │
│         tab_size = 8                                                          │
│            width = 81                                                         │
╰───────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'iTerm.app',   │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by willmcgugan** [comment]
The `no_wrap` option refers to *word wrapping*. In your first examples you have no spaces, so it is considered one large word. If you don't want the truncation you can specify `overflow="fold"` on the `add_column`.
