### ISSUE TITLE
[BUG] Possible missing `end` keyword argument in `Text.from_markup`

### ISSUE THREAD

**Issue by cadojo** [Textualize/rich#2054]
Is `Text.from_markup` missing an `end` keyword-argument?

I use `Text("Hello, world!", end="")` to create ` Text` object without a newline. If I want to use console markup, I'd want to use `Text.from_markup(":rocket: Hello, world!", end="")`, but this throws an argument error.

**Comment by willmcgugan** [comment]
You may be right! In the meantime, you can set `end` after you have created the Text object with `text.end=''`

**Comment by wasi-master** [comment]
@willmcgugan need a PR?

**Comment by willmcgugan** [comment]
If you wouldn't mind! :)

**Comment by wasi-master** [comment]
@willmcgugan while testing my changes, I noticed one thing (same happened with my from_markup implementation)

```python
import rich
from rich.text import Text

rich.print(Text("hello", end=" ") +  Text("hi"))
```
shouldn't this print `hello hi` and not `hellohi`? If not, how could I test if the end parameter is actually working?

**Comment by willmcgugan** [comment]
I don't think that would be desirable, although I can see the logic. The default is "\n", but you wouldn't want adding text to have new lines.

`console.print` will join text objects together and override `end`. The end will work in different contexts, the easiest way to test would be to put one or more Text instances within a `rich.console.Group`. Then print and capture the output. See the docs for capturing.
