### ISSUE TITLE
[REQUEST] - Console export to SVG

### ISSUE THREAD

**Issue by jeremyschulman** [Textualize/rich#2068]
As a Developer using rich Tables I would like to create images so that they can be included into messaging applications, such as Slack.  I am currently using the console.export_html() feature to create HTML string.  Then using a third-party package, imgkit, I can creating an image file.  

This issue request to have a console.export_svg() feature would enable me to create the image file without requiring the third-party package.

Thank you!

**Comment by darrenburns** [comment]
This feature has been merged to master now, keep an eye out for the next release :)

P.S. Thanks for `iterm2-colors2rgb` - it saved me a lot of time when pulling over a couple of initial themes to be included in Rich for exporting!
