### ISSUE TITLE
[BUG] Windows: Nothing is printed on Git Bash

### ISSUE THREAD

**Issue by naveen521kk** [Textualize/rich#2092]
**Describe the bug**
On Git Bash's Terminal (Mintty), nothing is printed when run with `rich==12.0.0`
![git bash rich bug](https://user-images.githubusercontent.com/49693820/159411423-462b2dba-116d-4abd-8a5b-468f294fd5fd.png)
I think this isn't an expected behaviour right? Seeing https://github.com/Textualize/rich/issues/988 and https://github.com/Textualize/rich/issues/330, it says Git Bash's terminal isn't a real terminal and can't print colours (which is fine), but not printing anything isn't.

The test script I used is really a Hello World script.
```py
from rich import print
print('Hello World')
```

Also, I noticed when running the same script through subprocess and checking for the output (consider the script below)
```py
import subprocess
import sys
op = subprocess.run(
    [sys.executable, 'test.py'],
    stdout=subprocess.PIPE
)
print(op.stdout)
```
Again, the stdout contains only `b''` (an empty string). This happens even when using `cmd`.
![image](https://user-images.githubusercontent.com/49693820/159412294-2802b11f-4ede-4685-a46a-76c7218ac777.png)
I initially noticed this when tests for the version printing on Manim started to fail https://github.com/ManimCommunity/manim/pull/2630#issuecomment-1074135310.

I think both these are related to each other and caused because of replacing Colorama.

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
I'm using Windows 11, Git Bash

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```
1st command: Prints nothing (that's literally the issue here)
2nd command:
```
❯ pip freeze | grep rich
rich==12.0.0
```
</details>

**Comment by willmcgugan** [comment]
Could you possibly check against the current master branch? I think that will fix it.

**Comment by wasi-master** [comment]
I'll try

**Comment by naveen521kk** [comment]
> Could you possibly check against the current master branch? I think that will fix it.

Nope, it didn't fix.
![image](https://user-images.githubusercontent.com/49693820/159467977-c73f3fe2-5f88-4efe-a4db-41e8126cefbe.png)
