### ISSUE TITLE
[BUG] ASV failed to publish

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2094]
https://github.com/Textualize/rich/actions/runs/2021954439

**Comment by darrenburns** [comment]
Just thrown the fix in here https://github.com/Textualize/rich/pull/2101/commits/0f1bd553656d62b4d8637b4368090e49a403593a#diff-3f278a8b9b660b85569060ea2063aef4ff14166476714b128279cf54ee6dcdb6L16
