### ISSUE TITLE
[REQUEST] Allow setting default parameters for `Console` via environment variables

### ISSUE THREAD

**Issue by joouha** [Textualize/rich#2119]
Hello,

When using `rich` in [`euporie`](https://github.com/joouha/euporie) (a terminal Jupyter notebook client), `rich` detects that it is running in a Jupyter notebook and not running in a TTY, and so returns HTML output.

However, you get a far superior experience when using `rich` in `euporie` by by setting the following `Console` parameters:

```python
Console(force_jupyter=False, force_terminal=True)
```

I'd like to be able to pre-configure `rich` to use these parameters by default when running in `euporie`. 

The Jupyter kernel in which `rich` runs is a separate process to `euporie`, but will almost always be a sub-process of it. This means that if the default `Console` parameters could be set using environment variables, this would allow me to pre-configure `rich` to give the best user experience when used in `euporie`.

I'm happy to take stab at implementing this.

Let me know your thoughts,
Thanks

**Comment by willmcgugan** [comment]
What are you proposing?

**Comment by joouha** [comment]
I'm proposing that the some of the default parameters values for `Console.__init__` be configurable using environment variables

**Comment by willmcgugan** [comment]
I got that, but what environment variables and what parameters?

**Comment by joouha** [comment]
I think it makes sense to be able to override the default behaviour of `force_jupyter`, `force_terminal` & `force_interactive`.

The environment variables could be called "RICH_FORCE_JUPYTER", "RICH_FORCE_TERMINAL", etc.

I've made a PR: #2122

**Comment by joouha** [comment]
Hello,

I've "fixed" my original issue by implementing `ipywidgets` support, and writing a HTML/CSS renderer for [euporie](https://github.com/joouha/euporie), so `rich`'s output is now handled in the same way as it is in JupyterLab.

It feels like a bit of an overly-complex solution, but it now means that `rich.live.Live` objects work without clearing the entire cell output, and that the HTML output of `JupyterRenderable`s / `JupyterMixin`s look good in the terminal.

So you can now do this:

[_rich.webm](https://user-images.githubusercontent.com/12154190/185574143-7e107a3f-a827-407a-acda-e9422e270395.webm)
