### ISSUE TITLE
[QUESTION] How to print multiple lines of text in Layout with Live?

### ISSUE THREAD

**Issue by cassiompf** [Textualize/rich#2120]
Hello Folks 👋, Goodnight. I have a question about the use of this library and I would like to know if there is something ready for it or if you know any way to solve it.

My question is if it is possible to print my Logs using Layout with the name of "body" in my code. I'm using Layout and always updating with Live.

The idea I want to do is similar to this gif I saw:

<img src="https://user-images.githubusercontent.com/20346767/160268564-40562825-70f0-4e6f-b33f-2b7e592512b1.gif" width="60%">

, where each newest print is displayed at the bottom and the oldest print is removed from the screen by the top of the screen (as if doing an automatic scroll)

Currently my code that I am using to test is like this:

```python
from rich import print
from rich.panel import Panel
from rich.layout import Layout
from rich.console import Console
from rich.text import Text
from rich.table import Table, Column
from rich.live import Live
from time import sleep


console = Console()
console.set_alt_screen(True)
console.clear()

layout = Layout()

logs_table = Table(Column("Logs"), expand=True)

layout.split_column(
    Layout(name="header", ratio=4),
    Layout(logs_table, name="body", ratio=6)
)

header = layout.get('header')

header.split_row(
    Layout(Panel(''), name="account-info"),
    Layout(Panel(''), name="bot-status-info")
)

live = Live(layout, refresh_per_second=1)
live_render.start(refresh=True)

for i in range(30):
    logs_table.add_row(f'Test line {i}.')

sleep(5)
```

The output result is like:

<img src="https://user-images.githubusercontent.com/20346767/160268770-5943ed95-a0b6-46c1-8b94-1f98ee91f007.gif" width="60%">

The problem is that it displays only the first rows of the table instead of displaying the most recent ones (in this case, the last rows of the table that were inserted)

**Comment by willmcgugan** [comment]
You would need to implement that yourself. Store the lines your want in a list and build a table from the lines you want.
