### ISSUE TITLE
[BUG] - Why dosent rich print my text with color when its configured properly using the Console API

### ISSUE THREAD

**Issue by StayMadYourBad** [Textualize/rich#2121]
```
from rich.console import Console

console = Console(color_system="windows")
GRINCH_LOGO = """

 ██████╗ ██████╗ ██╗███╗   ██╗ ██████╗██╗  ██╗    
██╔════╝ ██╔══██╗██║████╗  ██║██╔════╝██║  ██║    
██║  ███╗██████╔╝██║██╔██╗ ██║██║     ███████║    
██║   ██║██╔══██╗██║██║╚██╗██║██║     ██╔══██║    
╚██████╔╝██║  ██║██║██║ ╚████║╚██████╗██║  ██║    
 ╚═════╝ ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝    
                                                  
                                                  """

def title():
    console.print(GRINCH_LOGO, justify="center", style="violet")
    
title()
```

With the above code, I get the following output

https://prnt.sc/bLnutF7jgaK6

**Comment by StayMadYourBad** [comment]
It seems that the color gets properly displayed in my vscode terminal but not in my command prompt, any fix for this?

**Comment by willmcgugan** [comment]
Don't set `color_system`. Rich will auto-detect it. If you're running on the legacy windows console, you are limited to 16 colors, the closest color to violet may be this light grey color. Try the new WIndows Terminal to get the full color range.

**Comment by StayMadYourBad** [comment]
will test it out now

**Comment by StayMadYourBad** [comment]
so yeah you are right, at the moment trying to fix a infinite loading microsoft store bug. If I were to pack the  exe how would it show the colors on a client's screen. Would it show them how it is with violet, etc as my vscode or whatever the exe can render on their computer?

**Comment by willmcgugan** [comment]
It will use as many colors as it can. On an up-to-date Windows 10 box that will be the full 16.7 million colors.

If you want to guarantee it looks identical on all machines, you would need to restrict it to 16 colors. Run the following to see those colors.

```
python -m rich.color
```

**Comment by StayMadYourBad** [comment]
So I did python -m rich.color on the machine that I had this error on and its able to print all the colors https://prnt.sc/bLnutF7jgaK6

I had developed the following code to call my file when there is an error and I manually triggered it with cntrl c, on the second time it calls the file all the colors are fine, any idea why?

import os
from subprocess import call

```
while True:
    try:
        call(["python", "main.py"])
    except:
        os.system('cls')
        continue```

**Comment by StayMadYourBad** [comment]
![image](https://user-images.githubusercontent.com/83351519/160293449-b00466b8-e09f-4a16-b5c6-4d4519084d85.png)
