### ISSUE TITLE
[BUG] Bad print on Google Colab

### ISSUE THREAD

**Issue by peppocola** [Textualize/rich#2126]
When using rich on google colab, I get bad tables print:
![image](https://user-images.githubusercontent.com/45401861/160504947-72e19f38-c0e2-4040-8e00-c211d9893845.png)
While it should be like this:
![image](https://user-images.githubusercontent.com/45401861/160505006-24ec7439-c758-4c9b-b591-4e6f17b001ce.png)

Code used to create the table, given a pandas dataframe:
```python
import pandas as pd
from rich import box
from rich.table import Table, Column

COLORS = {"red", "green", "yellow", "blue", "magenta", "cyan", "white"}
BRIGHT_COLORS = set(['bright_' + c for c in list(COLORS)])
def create_rich_table(table: pd.DataFrame, title: str, box_style: box = box.ROUNDED, show_lines: bool = True):
    colors = BRIGHT_COLORS.copy()
    header = [Column(header=Name, justify='right', style=colors.pop(), no_wrap=True) for Name in table.columns]
    rich_table = Table(title=title, box=box_style, header_style='bold', show_lines=show_lines, title_style='bold', *header)
    for row in table.values:
        rich_table.add_row(*[str(x) for x in row])
    return rich_table
```

**Comment by willmcgugan** [comment]
You've set every column to `no_wrap` and there is not enough space to fit every column in. I'd suggest allowing the name column to wrap.
