### ISSUE TITLE
How to clear the progress bar after it's run its course

### ISSUE THREAD

**Issue by ma-sadeghi** [Textualize/rich#2134]
The following script:

```python
from time import sleep
from rich.progress import Progress

print("Begin...")

with Progress() as progress:
    pbar = progress.add_task("Performing X", total=100)
    for i in range(100):
        sleep(0.005)
        progress.update(pbar, advance=1)
    progress.remove_task(pbar)
progress.console.clear()

print("End...")
```

produces the following output:

```bash
Begin...

End...
```

Is there a way to entirely get rid of the line containing the progress bar after it's done? (see below)

```bash
Begin...
End...
```

**Comment by willmcgugan** [comment]
https://rich.readthedocs.io/en/stable/progress.html#transient-progress

**Comment by ma-sadeghi** [comment]
Yes, indeed :) 

Just bought you a humble cup of coffee :) although `rich` is worth thousands of cups of coffee! Thanks once again!
