### ISSUE TITLE
[QUESTION] How to override markdown header justification?

### ISSUE THREAD

**Issue by philwareublox** [Textualize/rich#2137]
Hello, 
Can I override the classes inside the markdown module?
I'd like to change the Heading class, specifically I'd like to override the text.justify = "center" in the markdown Heading class. 
How can I do this?

Many thanks,
Phil.

**Comment by willmcgugan** [comment]
It's not documented, but the Markdown class is easy to extend. There is a classvar called `elements`, which maps a markdown block on a class. You can use this to replace the `Heading` class with your own custom version.

**Comment by philwareublox** [comment]
Thanks for the tip. 
I simply created a new `class myHeader(TextElement):` with my own style and replaced the default one by:

`Markdown.elements['heading'] = myHeading`

**Comment by ssbarnea** [comment]
To be honest, I do find the default decision to center bit weird as almost everyone working with markdown does not do centered titles. Look at Google Docs, Git markdown, all of them indent to left, even on generic webpage documents title is not centered by default and most authors do not opt-in for picking centered. There are reasons related to readability that made most switch to this, as 100 years ago centering was standard.

When it comes to terminal, centering is even more damaging to readability, so how about considering now centering by default? WDYT? How about opening a poll on discussions about the subject?

**Comment by willmcgugan** [comment]
Headers are typically rendered larger than the body text in HTML. You can't do that in the terminal. If headers were all aligned to the left they would be indistinguishable from body text, even with bold / underline.

Centered headings are perfectly readable.

**Comment by hek2mgl** [comment]
I'm using `python -m rich.markdown` in a shell script. When possible, I would like to avoid extending the Python class and keep using the vanilla version of rich.

The result looks great! I only admit that I'm also thinking that the centered headlines breaking the flow of text a bit for me.

@willmcgugan you made a good point that there is no option to render the headers larger than the body at the terminal and therefore the options are somewhat limited.

I'm wondering if an option to render the headlines like `man` does might be an option? Like this, the headers are indented to the left:

```
$ man cat | cat
CAT(1)                                                        User Commands                                                       CAT(1)

NAME
       cat - concatenate files and print on the standard output

SYNOPSIS
       cat [OPTION]... [FILE]...

DESCRIPTION
       Concatenate FILE(s) to standard output.

       With no FILE, or when FILE is -, read standard input.
```

**Comment by jluna** [comment]
> Centered headings are perfectly readable.

@willmcgugan For what it's worth, here's an example of centered headers that make the content much less readable.

![Image](https://github.com/user-attachments/assets/7f21c769-5859-4657-b8b7-00eadcb39bad)

**Comment by willmcgugan** [comment]
Have a look at markdown.py, and change it how you see fit.

**Comment by jvdillon** [comment]
To those googling this,

```
from rich.console import Console, ConsoleOptions, RenderResult
from rich.markdown import Heading, Markdown

class LeftJustifiedHeading(Heading):
    def __rich_console__(
        self,
        console: Console,
        options: ConsoleOptions,
    ) -> RenderResult:
        yield from console.render(self.text, options=options.update(justify="left"))


class CustomMarkdown(Markdown):
    elements = {
        **Markdown.elements,
        "heading_open": LeftJustifiedHeading,
    }


Console(width=80).print(CustomMarkdown(open("file.md").read()))
```

**Comment by microfx** [comment]
so can we make a push/pull request or something? This is drviving  me crazy - cool tool but this should be an option. 

If you want I can vibe-code it! /s

**Comment by ocervell** [comment]
@microfx apparently the maintainers don't really care, even though left-aligned markdown headers is now an industry-standard basically (much more readable), meh.. I guess just implement your own override.
