### ISSUE TITLE
Async rich

### ISSUE THREAD

**Issue by ItsWoid** [Textualize/rich#2145]
Can I use rich asynchronously? For example create a `Prompt` without blocking.

**Comment by UltraStudioLTD** [comment]
As far as I know **rich** isn't implemented in asynchronous style so probably no

**Comment by UltraStudioLTD** [comment]
And also this isn't a **issue** so please move this question to [**Discussions**](https://github.com/Textualize/rich/discussions) and create **Q&A** type

**Comment by willmcgugan** [comment]
Prompt uses input under the hood which will block. You would need to run it in a thread if you want to combine it with async
