### ISSUE TITLE
[BUG] print progress bars on stderr

### ISSUE THREAD

**Issue by nschloe** [Textualize/rich#2151]
Right now, progress bars are printed to stdout. I would suggest changing this to stderr (by default). For reference, see [this stackexchange discussion](https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout).

Quoting:

> Printing spinners and the like to stdout together with the results is a safe way to make the results useless. If you ever need to pipe the results to some other program, said program would need to separate the results from the spinners. [...]

And:

> POSIX [defines standard error as](http://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html)
>
> > for writing diagnostic output
>
> This doesn't limit its use to error messages only. I would consider progress information as diagnostic output, so it belongs on standard error.

For a previous discussion of this, see https://github.com/Textualize/rich/issues/374.

**Comment by willmcgugan** [comment]
Rich will remove spinners and progress bars when piping the output.

**Comment by nschloe** [comment]
Alright, thanks for the info!
