### ISSUE TITLE
[BUG] commonmark dependency is unmaintained

### ISSUE THREAD

**Issue by The-Compiler** [Textualize/rich#2155]
The [commonmark repository](https://github.com/readthedocs/commonmark.py) reads:

> This repository has been archived by the owner. It is now read-only.

and

> [![No Maintenance Intended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)

and

> **Warning:** commonmark.py is now deprecated. We recommend using [markdown-it-py](https://github.com/executablebooks/markdown-it-py) for a commonmark parser going forward. See https://github.com/readthedocs/commonmark.py/issues/308 for background and discussion.

Which might mean it should be replaced at some point or another - unless the way it's used in rich makes this situation not a problem.

*(took the freedom to delete the issue template - I usually don't do that, but here, nothing of it really applies)*

**Comment by willmcgugan** [comment]
We do have plans to replace it with a more modern parser, which supports tables and more features. commonmark seems a fairly solid bit of code, so I don't anticipate any problems in the short term.

**Comment by The-Compiler** [comment]
Thanks for the quick answer! :+1:  FWIW I can second their recommendation of `markdown-it-py` - I've used it in a project for a bit of markdown parsing (calculating student grades based on a Markdown checklist, also using Rich by the way!), and I've been happy with it.

**Comment by willmcgugan** [comment]
Will track it here. https://github.com/Textualize/rich/issues/2156
