### ISSUE TITLE
Rich Live display not updating the terminal 

### ISSUE THREAD

**Issue by Tobi-De** [Textualize/rich#2158]
Hi, I hope everyone is ok, I am trying to display multiple progress bars with Rich. My program uses python concurrent.futures.ProcessPoolExecutor to run multiple tasks at the same time. I am using a table to display the progress bars, the table and progress bars are displayed correctly in the terminal, but all progress bars remain at zero until the end.

```python
import concurrent.futures

task_progress = Progress(
    "{task.description}",
    SpinnerColumn(),
    BarColumn(),
    TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
)



def process_chunk(
    chunk: list[tuple, None, None],
    comparison_indexes: list[int],
    rows: list[tuple[str]],
    rate: int,
    task_id: TaskID,
) -> list[list[tuple[str]]]:
    for row in chunk:
    ...
        for task in task_progress.tasks:
            task_progress.advance(task_id)
            if not task.finished:
                task_progress.advance(task_id)
           # task_progress.advance(task_id)
    return groups




def main():
    ...
    chunks = [...] # a list of Iterable
    ...
    tasks_ids = [
        task_progress.add_task(description="Processing...", total=len(chunk))
        for chunk in chunks
    ]
    progress_table = Table.grid()
    progress_table.add_row(
        Panel.fit(task_progress, title="[b]Jobs", border_style="red", padding=(1, 2))
    )
    ...
     with Live(progress_table, refresh_per_second=10):
        with concurrent.futures.ProcessPoolExecutor() as executor:
            groups = executor.map(
                process_chunk,
                chunks,
                tuple(itertools.repeat(comparison_indexes, chunks_len)),
                tuple(itertools.repeat(rows, chunks_len)),
                tuple(itertools.repeat(args.rate, chunks_len)),
                tasks_ids,
            )
```

**Comment by willmcgugan** [comment]
Hi,

I'm afraid it's not that easy with multiprocessing. Each process will get a new Progress instance, but only one instance is started. You will need to feed back progress information from the subprocesses via a queue or pipe. Search closed issues for "multiprocessing" for examples.

**Comment by Tobi-De** [comment]
> Hi,
> 
> I'm afraid it's not that easy with multiprocessing. Each process will get a new Progress instance, but only one instance is started. You will need to feed back progress information from the subprocesses via a queue or pipe. Search closed issues for "multiprocessing" for examples.

Ok thanks, How are you so fast on issues ? It's incredible
