### ISSUE TITLE
[BUG] Rich 12.1.0 throws an exception when importing

### ISSUE THREAD

**Issue by markmelvin** [Textualize/rich#2164]
The latest version of rich (12.1.0) fails to import for me with the following traceback.

```
Traceback (most recent call last):
  File "xxxxxx.py", line 24, in <module>
    from rich.progress import Progress, BarColumn, TimeRemainingColumn, track
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/progress.py", line 43, in <module>
    from .console import Console, JustifyMethod, RenderableType, Group
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/console.py", line 46, in <module>
    from ._log_render import FormatTimeCallable, LogRender
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/_log_render.py", line 5, in <module>
    from .text import Text, TextType
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/text.py", line 5, in <module>
    from rich.emoji import EmojiVariant
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/emoji.py", line 4, in <module>
    from .jupyter import JupyterMixin
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/jupyter.py", line 4, in <module>
    from .segment import Segment
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/segment.py", line 19, in <module>
    from .cells import (
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/cells.py", line 6, in <module>
    from ._lru_cache import LRUCache
  File "xxxx/my_venv/lib/python3.8/site-packages/rich/_lru_cache.py", line 8, in <module>
    from typing_extensions import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (xxxx/my_venv/lib/python3.8/site-packages/typing_extensions.py)
```

Rich 12.0.1 works fine for me.

This is on Ubuntu 20.04

**Comment by markmelvin** [comment]
Looks like I have `typing-extensions` 3.7.4.3 installed.

```
Requirement already satisfied: typing-extensions~=3.7.4 in ./my_venv/lib/python3.8/site-packages (from tensorflow==2.5.0->untether-ml==0.1.dev0) (3.7.4.3)
```

**Comment by michellekarunaratne** [comment]
Getting the same error

python version 		    - 3.7.12
rich version 		            - 12.1.0
typing-extension version    - 3.7.4.3

> Traceback (most recent call last):
> 
> File "xxxx/airflow", line 8, in <module>
> sys.exit(main())
> File "xxxx/python3.7/site-packages/airflow/__main__.py", line 40, in main
> args.func(args)
> File "xxxx/python3.7/site-packages/airflow/cli/cli_parser.py", line 47, in command
> func = import_string(import_path)
> File "xxxx/python3.7/site-packages/airflow/utils/module_loading.py", line 32, in import_string
> module = import_module(module_path)
> File "xxxx/python3.7/importlib/__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
> File "<frozen importlib._bootstrap>", line 983, in _find_and_load
> File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
> File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
> File "<frozen importlib._bootstrap_external>", line 728, in exec_module
> File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> File "xxxx/python3.7/site-packages/airflow/cli/commands/user_command.py", line 26, in <module>
> from airflow.cli.simple_table import AirflowConsole
> File "xxxx/python3.7/site-packages/airflow/cli/simple_table.py", line 22, in <module>
> from rich.console import Console
> File "xxxx/python3.7/site-packages/rich/console.py", line 46, in <module>
> from ._log_render import FormatTimeCallable, LogRender
> File "xxxx/python3.7/site-packages/rich/_log_render.py", line 5, in <module>
> from .text import Text, TextType
> File "xxxx/python3.7/site-packages/rich/text.py", line 5, in <module>
> from rich.emoji import EmojiVariant
> File "xxxx/python3.7/site-packages/rich/emoji.py", line 4, in <module>
> from .jupyter import JupyterMixin
> File "xxxx/python3.7/site-packages/rich/jupyter.py", line 4, in <module>
> from .segment import Segment
> File "xxxx/python3.7/site-packages/rich/segment.py", line 19, in <module>
> from .cells import (
> File "xxxx/python3.7/site-packages/rich/cells.py", line 6, in <module>
> from ._lru_cache import LRUCache
> File "xxxx/python3.7/site-packages/rich/_lru_cache.py", line 8, in <module>
> from typing_extensions import OrderedDict
> ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (xxxx/python3.7/site-packages/typing_extensions.py)

**Comment by willmcgugan** [comment]
Please try v12.2.0 which bumps typing_extensions

**Comment by jaredwelch1** [comment]
rich 12.3.0 appears to re-introduce this bug at least for me
