### ISSUE TITLE
Centering console.input()

### ISSUE THREAD

**Issue by StayMadYourBad** [Textualize/rich#2174]
How would I center console.input() ? I tried justify = "center" but it resulted in an error

**Comment by willmcgugan** [comment]
In what way do you want it to be centered. Do you want to prompt to be centered, or the text you type?

**Comment by StayMadYourBad** [comment]
hmm, I think both would be best. Where the prompt is centered and when the user inputs his/her answer that is in the center too right after the prompt
Something like
                                                                            What is your name? >> Safeer

**Comment by willmcgugan** [comment]
Rich uses the builtin `input()` function, and that's not something it is capable of.
