### ISSUE TITLE
[QUESTION] Possible to "undim" a specific table column ?

### ISSUE THREAD

**Issue by Kraymer** [Textualize/rich#2184]
I'm coding a cli tool to visualize chess games results

![Selection_595](https://user-images.githubusercontent.com/84227/162684656-760cbe15-13f3-492a-ad5e-a953755423e2.png)

I picked a `Table` configured with `row_styles=["dim", ""]` for the main layout, but would like the dim effect to not apply for the first column as I use unicode symbol to represent user side (black or white), having the white pawn becoming grey on every other row is an undesired behaviour.

It's easy to "dim" a whole column by applying `style="dim"` when calling `add_colum` but is the reverse operation possible and setting a style that cancel the eventual dim of the rows for a specific column ?

**Comment by wasi-master** [comment]
Maybe try using a different style when printing that specific column. Try using `default on default` to use the default text style

**Comment by wasi-master** [comment]
yeah that's better

**Comment by Kraymer** [comment]
@willmcgugan not working :  

~~~
    table = Table(
        row_styles=["dim", ""],
    )
    table.add_column("1", style="not dim")
    table.add_column("2")
    for idx in range(5):
        table.add_row("plop", "plip")
    console.print(table)
~~~
![Selection_596](https://user-images.githubusercontent.com/84227/162689176-d14a3b2f-5cfe-4898-896c-4e7e9500066f.png)

**Comment by willmcgugan** [comment]
@wasi-master 's suggest is good. Alternatively you could do the zebra stripping yourself.
