### ISSUE TITLE
[BUG] Table formatting messed up when Console width is setup on log, but not print

### ISSUE THREAD

**Issue by EntilZha** [Textualize/rich#2186]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

When the console width is set, If I show a table via `console.log` the formatting is messed up, but `console.print` works as expected.

For example:
```python
from rich.console import Console
from rich.table import Table

table = Table()
cols = ["key", "mean", "std", "min", "max", "count"]
for c in cols:
    table.add_column(c)
table.add_row('reward', '0', '1', '2', '0.00', '1000')
# Same issue with different widths, eg 750 and 1000 and
console = Console(width=500)
console.print(table)
console.log(table)
```

Print:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/1382460/162795624-852dee30-4188-4404-b34c-af2a20d353d7.png">

Log:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/1382460/162795938-4a42ff4d-f2fd-42d3-a853-3e03a281719c.png">

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
Mac latest, kitty terminal via eternal terminal + tmux. Output is going to a logfile in the end, but testing interactively.

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich # 12.2.0
```

</details>

**Comment by willmcgugan** [comment]
When you call `log` it will expand to the full width of the console to fit in the filename column. Because you've set the width of your console to 500 (?) it will wrap because your terminal is clearly much less than 500 characters wide.

**Comment by EntilZha** [comment]
I don't think that is the issue, as mentioned in the code comment, I also tried with longer console widths, For example, with `Console(width=2000)` which should be more than large enough, I get this display on a 1440p monitor
![image](https://user-images.githubusercontent.com/1382460/164543704-9f3322a6-dc73-4102-a5c8-5c01e9bb7c39.png)

If I decrease to 1000, it is very similar, but you can see where thee max width is:
![image](https://user-images.githubusercontent.com/1382460/164543859-64d53bbb-abad-4738-82ef-689757d4fe23.png)


Still though, the table is being rendered incorrectly. My guess is that the table lines are interspersed with other newlines for some reason.

**Comment by willmcgugan** [comment]
I guess you have assumed that width is pixels. It’s not, it’s measured in characters. You generally don’t need to see it, as Rich can detect the width automatically.

**Comment by EntilZha** [comment]
I was fairly sure that the width was in characters, but I mentioned the monitor pixels plus screenshots to confirm it didn't matter either way (that is to say, the bug doesn't seem to be an issue with not having enough space).

The reason I was setting the width is a combination of (1) I run my programs on a compute cluster so the logs are typically saved for stderr/stdout (slurm cluster) and (2) I typically launch programs from a vertical monitor terminal, so I wasn't certain if this was affecting the width or not. 

Regardless, it seems to me that one should be able to set the width of the terminal (in characters) and have the table print correctly when using `.log()` versus `.print()`. At the moment, it looks to me that setting a console width breaks table rendering when using `console.log()` regardless of width.

**Comment by willmcgugan** [comment]
The table rendering is not broken.

What's happening is when you do `log()` it will create lines as long at the Console width to accommodate the filename on the right of the "screen". When displayed on a terminal that is much less wide, each line of output will be forced to wrap on to subsequent lines, creating the blank space that breaks up the output.

If you are writing this out to a file, you probably don't want to use log, since it will only look correct on a terminal the same width as the output.

**Comment by EntilZha** [comment]
Part of my goal is that the log file looks fine in regular terminal (i.e., when I test locally), but shows up fine when run as a job logging stderr/out to a file (i.e., when I run on cluster). Hence, I would like to be able to set the console width when submitting to cluster versus running locally.

I still don't understand what you are saying about the terminal width being the issue. I tried for a variety of widths and the same issue still persists, even when it looks like there is more than enough room (e.g., prior screen shots). Moreover, if terminal width were the issue, then there should be a terminal width where this issue doesn't occur, but I tested on a range of terminal widths and had the same issue regardless.

My suspicion is that somewhere there is an issue where adding a fixed width forces a calculation between the table size and the extra information in `log`, but not in `print`. The table size gets computed as too small so then gets wrapped when it shouldn't get wrapped.

**Comment by willmcgugan** [comment]
I think you have a fundamental misunderstanding of what the width parameter on Console does. It doesn't change the width of the terminal, it just informs Rich of the maximum width of what it can render.

If you don't explicitly set the width it will render just fine.
