### ISSUE TITLE
[BUG] Exception when rending large tables into columns

### ISSUE THREAD

**Issue by StewAlexander-com** [Textualize/rich#2190]
Getting an error when attempting to use the column function within a for loop

![image](https://user-images.githubusercontent.com/48565067/163245214-910cffcc-d85f-4918-8caa-a178a2d5f501.png)

---

Runs for awhile without issue, then at some random point an exception error occurs, I tried to catch it but it keeps breaking, there's about 2,000 or so iterations on this particular for loop.

Not sure what a ```__rich_console__``` method means in this context

**Comment by willmcgugan** [comment]
Columns accepts strings or Rich renderables, but you are passing it an integer with value 500.

PS That's not how you catch multiple exceptions.

**Comment by StewAlexander-com** [comment]
Ah ok, so I have to type the data as an int first...

I was attempting to try to catch your exception, I just didn't know what to catch it on

**Comment by StewAlexander-com** [comment]
Thanks for the heads up, closing
