### ISSUE TITLE
[QUESTION] It is possible to save a Live Display to a file?

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [Textualize/rich#2196]
I've connected Rich to a discord bot and I need to send the terminal output of a Live to a discord channel. Seems like export_text and save_svg does not show any content for lives.

**Comment by willmcgugan** [comment]
Rich removes dynamic stuff from export, because it generally doesn't make sense to have multiple frames exported.

To export a single frame, you could construct a new console with `record=True` then print the Layout object, and export.
