### ISSUE TITLE
[BUG] Round brackets do not escaped

### ISSUE THREAD

**Issue by Vadim2S** [Textualize/rich#2199]
rich.markup.escape do not work with round brackets

I am want print string (filename) in one color. String contains round brackets
code:
`print(f'[yellow]{rich.markup.escape(img_filename)}[/yellow]')`
result:
![изображение](https://user-images.githubusercontent.com/84853762/163942284-8de8d4c1-bff0-48c6-9f95-811c5bc706c3.png)
or:
code:
`print(rich.markup.escape(img_filename))`
result:
![изображение](https://user-images.githubusercontent.com/84853762/163960322-b9714653-d2f4-41bc-b144-f0f4627a201b.png)

expected:
all-single-color filename

environment:
Windows 10 Home, Python 3.10, Rich 12.2.0, MS Windows Terminal Preview, CMD console.

**Comment by willmcgugan** [comment]
Round brackets have no special meaning in console markup. The color is added by highlighting. See [the docs](https://rich.readthedocs.io/en/latest/highlighting.html) for how to disable it.
