### ISSUE TITLE
Missing whitespace in traceback

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2206]
In tracebacks sometimes there is a missing blank line between traceback frames. Not sure what causes it.

**Comment by DrBenton** [comment]
I'm still trying to reproduce the bug, but so far all the tracebacks I can display seem to be correctly formatted - (too) good job Rich! :sweat_smile:

**Comment by willmcgugan** [comment]
It's a weird one, doesn't always occur. It may be related to the number of frames. Try with 2 frames.
