### ISSUE TITLE
[REQUEST] Additional columns appended to `track` function

### ISSUE THREAD

**Issue by YYYasin19** [Textualize/rich#2208]
Hey,
 this is just a small feature that would be a great convenience, as I (and some others I've talked to) have come across this issue a few times.

_If there already was a discussion about this that I missed, I am sorry and would welcome a link. As this is my first issue so far, I'm more than thankful for any hints regarding the process, if I have missed something._

**How would you improve Rich?**

I would like to add a keyword argument `additional_columns` to the `track(...)` function. Here, the user can pass just any of `rich`s plenty and feature-rich `ProgressColumn`-objects without having to go and create a separate progress bar and update a task. These additional columns will just be appended to the default columns.

**What problem does it solve for you?**

Currently, using `track(...)` is a very easy and convenient way to track the progress of various tasks without delving too much into the library. However, often one needs to display additional measures or visualizations - most of which are already available as columns. Unfortunately, creating a progress bar with custom columns requires a lot more lines of code, while most of the time you only want to add one or two custom columns.

Currently
```python3
with Progress(
    BarColumn(
                style=style,
                complete_style=complete_style,
                finished_style=finished_style,
                pulse_style=pulse_style,
            ),
     TaskProgressColumn(),
     TimeRemainingColumn(),
     SpinnerColumn() # the only thing that should be added, for example
) as progress:

    task1 = progress.add_task("[red]Downloading...", total=1000)
    
    for n in range(n):
        progress.update(task1)
```

New
```python3
for n in track(range(n), description="Processing...", addtionial_columns=[SpinnerColumn()]):
    do_work(n)
```

**Proposed Change**
The required changes would - as far as I know - only a **three** new lines of code.
This has not been tested yet, but as the columns will just be passed to `Progress(...)` I would not expect this to have a lot of bug-potential.

```python3
def track(
    sequence: Union[Sequence[ProgressType], Iterable[ProgressType]],
    # all the other arguments
    additional_columns: Optional[List["ProgressColumn"]] = None # --- NEW ---
) -> Iterable[ProgressType]:
  
# ... docs

    columns: List["ProgressColumn"] = (
        [TextColumn("[progress.description]{task.description}")] if description else []
    )
    columns.extend(
        (
            BarColumn(
                style=style,
                complete_style=complete_style,
                finished_style=finished_style,
                pulse_style=pulse_style,
            ),
            TaskProgressColumn(),
            TimeRemainingColumn(),
        )
    )
    # --- NEW ---
    if additional_columns:
        columns.extend((*additional_columns, ))

```

**Comment by willmcgugan** [comment]
`additional_columns` wouldn't give you the ability to put them at the start, or arrange them how you like.

But it's not all that bad if you use `Progress.default_columns()`:

```python
with Progress(*Progress.default_columns(), SpinnerColumn()) as progress:
    ...
```

If you find yourself requiring more of `track`, it probably means you should use the Progress class directly which offers the full range of features.

**Comment by YYYasin19** [comment]
Hey, thanks for the feedback, that makes sense!
