### ISSUE TITLE
[REQUEST] Add `__version__` attribute.

### ISSUE THREAD

**Issue by Erotemic** [Textualize/rich#2218]
[Pep8](https://peps.python.org/pep-0008/#module-level-dunder-names
) suggests adding a `__version__` attribute to top level module `__init__.py` files 

**How would you improve Rich?**

This gives people a quasi-standard way for a user to inspect the version of the rich package at runtime without any external libraries.

**What problem does it solve for you?**

I like using a bash alias to inspect package versions:

```bash
pyversion () 
{ 
    __doc__="
    Display the version of a Python module

    Example:
        pyversion six
    "
    PYVERSION_COMMAND="import $1; print('$1.__version__ = ' + str($1.__version__))";
    echo "python -c \"${PYVERSION_COMMAND}\"";
    python -c "$PYVERSION_COMMAND"
}
```

This assumes that packages define the `__version__` attribute, and most of them do. Adding this to rich would be helpful to me.

I do notice the version currently seems to be defined in `pyproject.toml`, which might make this tricky as it is not ideal to have multiple places that specify the version. I typically use the `__version__` in `__init__.py` as the single source of truth and then have my `setup.py` statically parse it out via the ast module, but that won't work in this case. One alternative might be to use `setup.py` to generate a version file based on pyproject.toml into the rich package, which is then read and exposed by `__init__.py`. But that is only one of the possible ways to address the issue.

**Comment by Czarified** [comment]
Pyproject.toml can reference the `__version__` attribute defined in `__init__.py`. I'm curious as to why Will/Textualize.io do not already have it defined this way. Are there advantages to static definition in the toml? Is there a version function somewhere, like some other libraries have? Admittedly I'm drawing a blank on an example.

**Comment by wasi-master** [comment]
The rich docs' `conf.py` uses the following snippet to get the version 

https://github.com/Textualize/rich/blob/7519ba1846d48b10f031696067af13e7f2784e67/docs/source/conf.py#L32-L33

🤔

**Comment by DrBenton** [comment]
> Pyproject.toml can reference the `__version__` attribute defined in `__init__.py`

@Czarified I double-checked [PEP 440](https://peps.python.org/pep-0440/), but I could not find a description of such a machinery? Would you have a link describing it? :slightly_smiling_face:

**Comment by Czarified** [comment]
@DrBenton , Sorry. I think I misspoke. You can put it in the `setup.cfg` with the format:

```
[metadata]
version = attr: <module_name>.__version__
```

(Obviously, as long as the attribute is defined in whatever module.)

I'm not sure what PEP it is defined in, sorry... I have worked on another open-source package that uses this schema, though: [sectionproperties](https://github.com/robbievanleeuwen/section-properties/blob/master/setup.cfg).

**Comment by DrBenton** [comment]
@Czarified Ah, I see, thanks for the clarification! :slightly_smiling_face: 
It seems to be managed by the setuptools package under the hood:
> https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html?highlight=attr#dynamic-metadata

It looks to be an interesting machinery for sure, but unfortunately it doesn't seem supported by Poetry itself :pensive:
