### ISSUE TITLE
Investigate Mypyc for Rich

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2235]
It may be feasible to compile part of all of Rich with mypyc. We should investigate that.

From what I understand, a mypyc Rich wouldn't support `"python -m rich.*"` which would be a deal-breaker since that's a much loved feature. However we could get much of the benefits from a mypyc version of some critical files, like segment.py.

**Comment by darrenburns** [comment]
@willmcgugan  Should we close this?
