### ISSUE TITLE
SVG export colors wrong

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2237]
When exporting syntax to SVG the color for the numbers and guide lines were incorrect. In the terminal they are a mid grey, but in the export they are closer to pure white. If I was to guess I would say that the dim attribute isn't respected here.

<img width="1167" alt="terminal" src="https://user-images.githubusercontent.com/554369/166105631-2d9e95c2-deb9-4561-8e29-434c67bf7712.png">

<img width="1563" alt="svg" src="https://user-images.githubusercontent.com/554369/166105624-81a0cb1c-9f76-42c6-826f-3fa11976e889.png">

**Comment by pawamoy** [comment]
It seems markup is interpreted as well when exporting to SVG. Example: http://localhost:8000/markdown-exec/gallery/#build-an-svg-image-from-code-snippets-with-rich

While the output in the terminal is correct:
![rich_svg](https://user-images.githubusercontent.com/3999221/166117028-fb3cd24a-e4c4-4b1b-8479-09a77fed6c3f.png)

**Comment by willmcgugan** [comment]
Should be fixed by https://github.com/Textualize/rich/pull/2242
