### ISSUE TITLE
[BUG] Style embedded in SVG breaks parent page styling

### ISSUE THREAD

**Issue by pawamoy** [Textualize/rich#2239]
**Describe the bug**

Not sure this can be considered a bug.
Embedding an SVG file generated by Rich into an HTML page has the potential to break the current styling.
I'm looking at plain `span` and `a` CSS selectors particularly.
Would it be possible to restrict the selected elements using ids and classes, just like the other selectors using `#terminal`?

To see it in action, go to https://pawamoy.github.io/markdown-exec/gallery/ and take a look at the "Source" tabs.

**Comment by willmcgugan** [comment]
You're using an older version of Rich. This was recently fixed.

**Comment by pawamoy** [comment]
Ah, thanks, and sorry for the noise, I actually installed `rich` yesterday and naively thought I'd get the latest version, but maybe there's another dependency that capped it.

**Comment by willmcgugan** [comment]
No worries! Might have been a recent upgrade to typing_extensions. If a dependancy requires an older version of this it might not pull in the latest Rich.
