### ISSUE TITLE
[BUG] docs+intersphinx objects.inv is broken for latest

### ISSUE THREAD

**Issue by cognifloyd** [Textualize/rich#2243]
**Describe the bug**

Also, the rich reference generation seems to be broken for `latest`.
Compare these pages:
https://rich.readthedocs.io/en/stable/reference/syntax.html
https://rich.readthedocs.io/en/latest/reference/syntax.html <-- this page is empty

I discovered this because `rich.syntax.Syntax` is missing in `objects.inv` with the `latest` version of the docs (not `stable`).

Given this intersphinx config:
```
intersphinx_mapping = {
    # ...
    "rich": ("https://rich.rtfd.io/en/latest", None),
}
```

This is the warning printed by sphinx:
```
/home/runner/work/ansible-lint/ansible-lint/src/ansiblelint/color.py:docstring of ansiblelint.color.render_yaml:: WARNING: py:class reference target not found: rich.syntax.Syntax
```

You can see this line here:
https://github.com/ansible/ansible-lint/runs/6266148079?check_suite_focus=true#step:7:123

**Comment by willmcgugan** [comment]
Those pages seem to be fine now. A glitch perhaps?

**Comment by cognifloyd** [comment]
I reran that old failing workflow and now it's passing. Go figure. I guess I'll close this now.
