### ISSUE TITLE
[REQUEST] Replit

### ISSUE THREAD

**Issue by Shkeffy** [Textualize/rich#2250]
Consider posting in https://github.com/willmcgugan/rich/discussions for feedback before raising a feature request.

Have you checked the issues for a similar suggestions?

**How would you improve Rich?**

Making this work in Replit?

**What problem does it solve for you?**

People can then use it in Replit! (Ie, me).

**Comment by willmcgugan** [comment]
Rich works in Replit as far as I can tell. Did you install the package?

**Comment by Shkeffy** [comment]
Yeah.

**Comment by willmcgugan** [comment]
Help me out here. What have you tried. And what didn't work?

**Comment by UltraStudioLTD** [comment]
**rich** walks in replit.com without issues. I have never encountered any problem in any part of it wherever it is static (colored strings, static tables and panels) or dynamic (progress bar, status, live display) content.

**Comment by Shkeffy** [comment]
Yeah, it works now.

**Comment by Shkeffy** [comment]
> Did I solve your problem?
> 
> Why not buy the devs a [coffee](https://ko-fi.com/textualize) to say thanks?

Tf did *you* do??
