### ISSUE TITLE
[BUG] Text wrapping edge case

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2273]
Discovered a possible edge case with text wrapping, probably connected to when a "word" is greater than the available width.

Consider the following:

```python
console.print("Hello, World...123 ", width=10)
```

This produces:

```
Hello, Wor
ld...123
```

I think this occurs because "World...123" doesn't fit in to 10 characters, so folds on to the next line.

I would expect there to be an additional new line after the Hello, like this:

```
Hello,
World...12
3
```

**Comment by DrBenton** [comment]
I guess we could replicate what Jinja does for example, with its `break_long_words` and `break_on_hyphens` options? :slightly_smiling_face:  
(more versatile maybe than Django's `wordwrap` for example)
https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.wordwrap

**Comment by willmcgugan** [comment]
Rich has a concept of "overflow", which captures this. Although we don't do hyphens as I thought the rules were complex and language specific.

**Comment by DrBenton** [comment]
Right, I've read the issue too quickly! - and misunderstood the problem as a result :sweat_smile: 
We would likely need advanced hyphenisation to solve this indeed - which can of course be quite a tough topic to solve if we want to do it correctly.
And the fact that the rules are language specific, like you were saying, implies that we would have to choose what language to use by default (potentially relying on the system's locale?) and how to allow users to customise the language they want their Textual app to use for hyphenisation?

I did a quick try with Pyphen, but it doesn't seem to hyphenise this test text correctly? :thinking: 
![Screenshot from 2022-05-12 15-50-12](https://user-images.githubusercontent.com/722388/168104124-53c0ff77-a9cd-42a7-9f7e-0061180cbe2a.png)

**Comment by willmcgugan** [comment]
I don't think we need hyphenation right now. Maybe one day, but I don't think there is much of a demand for it.

In the short term, I think a tweak to `wrap.py` would satisfy this.
