### ISSUE TITLE
[REQUEST] Add a [minimal] version of rich without commonmark and pygments

### ISSUE THREAD

**Issue by tonybaloney** [Textualize/rich#2277]
Rich comes with 2 required dependencies: commonmark and pygments.

CommonMark for Markdown parsing and rendering. Pygments for code syntax highlighting.

I'm often pulling in rich for colorised outputs, tables, and progress bars. None of these require those libs.

It would be nice to have a "minimal" version of rich that doesn't itself have dependencies, e.g.:

```console
$ pip install rich[minimal]
```

Thanks for your consideration

**Comment by willmcgugan** [comment]
I've had the same point myself, but AFAIK the extras can't subtract dependencies, only add them.

An alternative might be to have a new package called `rich-minimal`.

**Comment by UltraStudioLTD** [comment]
Or second option is to rewrite **rich** and **setup.py** to optionally install syntax highlight and markdown render

**Comment by willmcgugan** [comment]
That's not an option, since it will break people's code.

**Comment by UltraStudioLTD** [comment]
@willmcgugan I have a question.
Why don't vendor every dependency **rich** has locally? It would reduce size since it would be possible to remove unwanted functions and variables.

**Comment by hanxiao** [comment]
@willmcgugan one solution is using env variable in pip to control the "subtracted" dependency, example

https://github.com/jina-ai/jina/blob/c056fad074ae6f46a61b193fd89af6b7f0751be8/setup.py#L135

**Comment by willmcgugan** [comment]
There doesn't seem ti be a great deal of appetite for this. Let me know if anyone wants to take the lead on it.
