### ISSUE TITLE
[BUG] Bold does not clear when using [default] style

### ISSUE THREAD

**Issue by unparalleled-js** [Textualize/rich#2280]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

`[default]` does not clear bold.

**Platform**
macOS
Both out-of-box and Pycharm terminals
I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

Titles like

```python
f"[bold green]Header - [default] sub text that does not need bold"
```

The green goes away but the bold does not.

<img width="325" alt="Screen Shot 2022-05-16 at 17 11 18" src="https://user-images.githubusercontent.com/19540978/168690761-bbfe0864-54e6-40ba-92b2-e7520dd38278.png">

**NOTE**: I am using `rich==11.2` currently due to a dependency conflict

**Comment by willmcgugan** [comment]
Console markup is like HTML. You need to close tags.

```
"[bold green]Header - [/] sub text"
```

**Comment by unparalleled-js** [comment]
> Console markup is like HTML. You need to close tags.
> 
> ```
> "[bold green]Header - [/] sub text"
> ```

TIL

thank you
