### ISSUE TITLE
[REQUEST] tab_size=None keeps and doesn't replace tab-characters

### ISSUE THREAD

**Issue by fjellvannet** [Textualize/rich#2298]
Have you checked the issues for a similar suggestions? I have googled, but couldn't find any discussion naming this issue.

I have found no way to set tab_size in the console to None, meaning that tab-characters should not be replaced and kept as-is.

Give as much detail as you can. Example code of how you would like it to work would help.

What I'd like to achieve is the ability to print a csv-table with tabulators as delimiters. Yet I have found no way to do that using rich - all tabulator-characters are replaced with a varying amount of spaces.

```python
>>> from rich.console import Console
>>> c = Console(tab_size=None)
>>> c.print("a\tb")
a       b
>>> print("a\t")  # I'd like to have an option to get this output from rich as well
a\tb
```

What problem do you have that this feature would solve? I may be able to suggest an existing way of solving it.

In rich text it should be possible to print a tab-character as-is :).

**Comment by willmcgugan** [comment]
Why do you want a literal tab character?
