### ISSUE TITLE
[BUG] Named backreference not supported in highlighter regex

### ISSUE THREAD

**Issue by tomers** [Textualize/rich#2299]
**Describe the bug**

I created the following highlight regex:
```python3
# Calendar date (e.g. 2008-08-30 or 20080830). The hyphens are optional.
# This regex uses a capturing group and a backreference to match
# YYYY-MM-DD or YYYYMMDD, but not YYYY-MMDD or YYYYMM-DD
r"^(?P<year>[0-9]{4})(?P<hyphen>-?)(?P<month>1[0-2]|0[1-9])(?P=hyphen)(?P<day>3[01]|0[1-9]|[12][0-9])$",
```
This regex was matched in `test_highlighter.py` against the following string: `"2008-08-30"`.
The expected result is:
```python3
[
  Span(0, 4, 'iso8601.year'),
  Span(4, 5, 'iso8601.hyphen'),
  Span(5, 7, 'iso8601.month'),
  Span(7, 8, 'iso8601.hyphen'),
  Span(8, 10, 'iso8601.day')
]
```
Actual result:
```python3
[
  Span(0, 4, 'iso8601.year'),
  Span(4, 5, 'iso8601.hyphen'),
  Span(5, 7, 'iso8601.month'),
  Span(8, 10, 'iso8601.day')
]
```
I need a way to highlight multiple hyphens and colons, which are common in ISO8601, e.g. in `"2008-08-30T01:45:36.123Z"`.

**Comment by tomers** [comment]
Note this is not relevant anymore, since I don't need to tag hyphens and colons separately. It is just some issue I've observed. Feel free to close if you don't really think it is neccessary.

**Comment by willmcgugan** [comment]
I'm no expert in regex, but I can see from the Python API that a backreference matches but doesn't capture anything.

The Highlighter API is flexible enough that you could implement highlighting with any string parsing techniques, if you needed to.
