### ISSUE TITLE
Broken display when using the curses library 

### ISSUE THREAD

**Issue by max-l** [Textualize/rich#2300]
I want to respond the a keyboard key stroke, and have tried the curses library,

and when the function  curses.initscr() is called, the display gets broken.
 

```
import curses

with Live(refresh_per_second=2) as live:
    window = curses.initscr()    
    live.update(_draw_status_table())
    key = window.get_wch()
    ....
```

Is there a proper way that the two libraries can work together ? 

Or is there a better library that can intercept keystrokes that is compatible with Rich ?

**Comment by willmcgugan** [comment]
Afraid not. They are mutually incompatible. You might be interested in Textual.
