### ISSUE TITLE
[BUG] Questionable documentation for progress

### ISSUE THREAD

**Issue by njr0** [Textualize/rich#2313]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

The documentation for progress in 12.4.4 (https://rich.readthedocs.io/en/stable/progress.html) starts with this: 

    from rich.progress import track

    for n in track(range(n), description="Processing..."):
        do_work(n)

It feels like `n` is being used for two different things there. Maybe you mean:

    from rich.progress import track

    for i in track(range(n), description="Processing..."):
        do_work(i)

or something?

**Comment by willmcgugan** [comment]
Yes, you're right. That ideally be a complete working piece of code. But it wasn't my full time job then!

**Comment by njr0** [comment]
Of course.

I think just using a different variable for the loop and the range would get people 90% of the way there.

**Comment by darrenburns** [comment]
How about this? https://github.com/Textualize/rich/pull/2327
