### ISSUE TITLE
[BUG] Wrapping issue when using RichHandler when stdout *and* stderr *and* stdin are redirected

### ISSUE THREAD

**Issue by alexprengere** [Textualize/rich#2316]
First of all, a big thanks for developing rich, I use it all the time 😉 
I have a wrapping issue when using RichHandler, it especially appears when running within a Jenkins job, but I could build a small reproducer:

```python
import logging
from rich.logging import RichHandler
from rich.console import Console

console = Console()
logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(console=console)],
)

logging.error("A" * 100)
```

My terminal width is more than 100 characters. Now, when executing this directly, I have no issues, meaning no wrapping occurs:

```bash
$ python test.py
[10:40:50] ERROR    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA         test.py:13
```

When redirecting the output to a file, no issue either:

```bash
$ python test.py > out
$ cat out
[10:41:40] ERROR    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA         test.py:13
```

If I do not redirect the output to a file, but I set stdin, still no issues:

```bash
$ echo "" | python test.py
[10:42:23] ERROR    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA         test.py:13
```

I am going to skip a bit over the other cases and jump to the conclusion. When redirecting stdout, stderr and stdin, and only in that case, a wrapping at 80 chars occurs:

```bash
$ echo "" | python test.py > out 2> /dev/null
$ cat out
[10:46:53] ERROR    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA test.py:13
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                    AA
```

Perhaps this is working as intended, but I thought I would report it. The same issue occurs with `Console(stderr=True)`. The example might look a bit contrived, but when running a script in Jenkins and looking at the console logs of a build, this is exactly what shows.

**Comment by willmcgugan** [comment]
In the case you describe there is no way to auto detect the terminal width, since the process is not connected to a terminal. You can force the width by setting the `COLUMNS` env var.

However, the RichHandler is designed for a terminal. It's use is limited when writing to a file, and you might want to use a stream handler or similar for production / CI environments.

**Comment by alexprengere** [comment]
Your answer totally makes sense, and thanks for the `COLUMNS` tip! You are right, RichHandler should not be used for CI environments. I would think there is some space within rich to provide another logging handler for those use cases, but I will let you be the judge of that. Thanks!
