### ISSUE TITLE
[REQUEST] Can "print" output object like json.dumps?

### ISSUE THREAD

**Issue by Erimus-Koo** [Textualize/rich#2317]
Use double quote ["] instead of single quote ['], and do not break line.
Is that any way to do it?

**Comment by willmcgugan** [comment]
JSON doesn't support single quotes. I suspect you aren't printing json. Perhaps you can paste some code and I can offer suggestions.

**Comment by willmcgugan** [comment]
To print JSON you have two options:

`console.print(json.dumps(my_object))`

Or

`console.print_json(my_object)`

**Comment by Erimus-Koo** [comment]
> To print JSON you have two options:
> 
> `console.print(json.dumps(my_object))`
> 
> Or
> 
> `console.print_json(my_object)`

Thanks for your advise, and I've tried "print_json", that looks good for printing json.

```
data = {'a': [123, 456], 'b': {'x': 1, 'y': 2, 'z': 3}, 'c': 'long text ' * 100}

from rich import print_json
print_json(data=data)
```

---

But there still some inconvenient point:
1. There are 2 diff func, "print" & "print_json", and the arg name "data=" is necessary.
2. I also use the syntax, like f-string, or some diff part combine with comma in one "print".

```
from rich import print
print('data: ', data)  # I wish write it like this
print(f'data: {data}')  # even use f-string
```
If I use "print_json" or "json.dumps":
```
# print json (2 lines)
print('data: ')
print_json(data=data)

# json.dumps (ensure_ascii for Asia characters, it's long.)
print(f'data: {json.dumps(data, ensure_ascii=False, indent=2)}')
```
I know I can define a function "dumps", but it still complex, because of some special object what json not supported directly, need print "__repr__". And I have wrote one, but I hope all "print" in "rich", instead of several different methods.

---

And back to why I have these needs,
- "no break line", for count the lines number correct. My console can "auto break line", so is that a config/setting can turn break line off. And some  time I copy text from console, there's too many "\n" be created.
- "double quote" for copy json from console to some other json "prettier" tools or copy json as config to other app, "break line" and "single quote" will make the json unreadable. And the problem of "print_json" or "dumps" as I mentioned earlier.

I am very appreciate and willing to use "rich" print, but is there any way to make the above two points easier?
Is there some setting/config/function/args I missed?

**Comment by Erimus-Koo** [comment]
```
data = {'a': [123, 456], 'b': {'x': 1, 'y': 2, 'z': 3}, 'c': 'long text ' * 100}
print('data:', data)

> output
data: {
    "a": [
        123,
        456
    ],
    "b": {
        "x": 1,
        "y": 2,
        "z": 3
    },
    "c": "long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text long text "
}
```
Syntax simple, output can be copy (as json/txt), with line break originally, print with color, and indent 4 space.

**Comment by willmcgugan** [comment]
Your `data` dict is not JSON, it's a dict. If you `print` it, you will get a representation of a Python dict which is also *not* JSON.

If you want to print JSON you will first have to encode your data as JSON. This is what the `data` argument of `print_json` does.

Rich won't help you product fragments of JSON that may be copied from the terminal. If that's what you need, you will probably have to implement that yourself.
