### ISSUE TITLE
Allow using [] in console.print function

### ISSUE THREAD

**Issue by knassar702** [Textualize/rich#2323]
Hello team, I'm trying to print a XPATH pattern by using `console.print()` function but this function priting only the first part of the pattern 

```python
pattern = '//img[@src="x"][@onerror="`2`"]'
console.print(f":meg: XPATH Searcing pattern:  {pattern}")
```

output:

```
🔍 XPATH Searcing pattern:  '//img' 
```

how can I fix that?

thanks

**Comment by willmcgugan** [comment]
You can set `markup=False`. See also the docs on [Console Markup](https://rich.readthedocs.io/en/latest/markup.html), particularly escaping.
