### ISSUE TITLE
Use plugin to populate __version__

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2335]
So tired of issues asking about `__version__`. This plugin should solve it once and for all, while allowing us to keep the same work-flow.

https://github.com/tiangolo/poetry-version-plugin

**Comment by DrBenton** [comment]
It turns out that the plugin itself is in alpha version at the moment, and relies on a beta version of Poetry 1.2.x - so we'd better wait for these 2 tools to be released in proper versions before using them :slightly_smiling_face:
