### ISSUE TITLE
Investigate this broken test

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2336]
https://github.com/Textualize/rich/pull/2292

**Comment by darrenburns** [comment]
By setting the `max_width` to `1`, we end up with trouble aligning it. We subtract 4 from it inside `rule.py` when center aligning it, and ultimately try to truncate it to a width of -3. Inside `set_cell_size` we go into the binary search `while` loop and spin infinitely.

We could update [this check](https://github.com/Textualize/rich/blob/1586c3e628f7b3e87d37f87d0b03a8b1710a0790/rich/cells.py#L83) to be `if total <= 0`, and it would fix the issue, but I don't understand the consequences of doing that, so will need guidance.

**Comment by willmcgugan** [comment]
Ah ok. I can reproduce it with this:

```python
from rich.console import Console
from rich.rule import Rule
console = Console()
console.print(Rule("foo"), width=4)
```

I think the fix is in rule.py We should probably treat it as having no title, if the width is <=4

I think the check in truncate is probably also a good idea, but more of a sanity check.

**Comment by darrenburns** [comment]
With the `__rich_measure__` returning 1 for width, if we set the text of a spinner to a rule, the rule has width 1. Are we okay with this?

**Comment by willmcgugan** [comment]
Honestly, I can't even think what anyone would expect to see when setting the spinner text to a Rule. I'm happy for it just to not crash.
