### ISSUE TITLE
Style.render cache

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2340]
The Style.render method is very cachable. It's tempting to add a @lru_cache and be done with it. The problem is that may use up a significant amount of memory since the string sizes could be arbitrarily large.

However the performance win is too tempting to overlook, and will have the greatest benefit for Textual.

I think we should have a `render_cache` on the Console object that is disable by default, but in Textual we can set that to an LRUCache.

**Comment by DrBenton** [comment]
Maybe we could have something like a `optimize_for_performance` config flag somewhere, which would allow one (or a package such as Textual) to opt-in for such performance optimisations opt-in at a global level, at the cost of a higher memory consumption?

**Comment by willmcgugan** [comment]
After some experimentation, it turns out we cannot beat the builtin `lru_cache` which has a C implementation.

The current caching behaviour is pretty good.
