### ISSUE TITLE
[REQUEST] Add `rich.inspect` argument to prevent `@property` attributes from being computed

### ISSUE THREAD

**Issue by AaronBeaudoin** [Textualize/rich#2351]
When using `rich.inspect` to see the attributes of a method, `@property` attributes are all immediately computed. On a huge object with lots of `@property` attributes, or if any of them are expensive to compute, it can slow the whole thing down to a crawl. Or if a `@property` attribute is causing a call to a database or something it may be causing load that I might want to avoid.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/26592486/174318594-bc4ba346-3ffc-4e1e-950e-ca1a06713554.png">

**How would you improve Rich?**

I would add an argument to `rich.inspect` to allow me to prevent from computing all the `@property` attributes on an object. I think this should come as an `exclude` argument or something with a list of object attributes to exclude from the `inspect` output. That way, if someone has added some magic to a class to compute attributes when they are accessed without even using `@property`, we can keep those out of the output as well.

**What problem does it solve for you?**

In cases where inspecting an object would cause expensive calculations to be run, I would now have a way to prevent those expensive calculations by hiding the offending object attributes from my `inspect` output.

**Comment by willmcgugan** [comment]
If a property is too "expensive" to evaluate when inspecting an object, it's probably an indication it shouldn't be exposed as a property. Python is too dynamic to be sure if you are evaluating code when accessing an attribute, as apposed to pulling something out of the dict.
