### ISSUE TITLE
Tree does not render the file extension properly.

### ISSUE THREAD

**Issue by rubenbb85** [Textualize/rich#2363]
If the file name contains more than one dot, the text after the first dot will be rendered as part of the extension.

Python version: 3.10.5
Rich version: 12.4.4
Windows Terminal version: 1.13.11431.0

![rich-extension](https://user-images.githubusercontent.com/54094318/175814156-b76b17a6-5d05-45be-8222-1ea63eb06e0c.png)

**Comment by willmcgugan** [comment]
The highlight is applied with a regex in `listdir.py`. Since listdir is example code and not part of the core library, there is little reason to change it. However I would accept a PR if you want to change it.
