### ISSUE TITLE
The progress bar is always next to the log Infos

### ISSUE THREAD

**Issue by KarhouTam** [Textualize/rich#2389]
I like the form of `rich.progress.track()`. But when I use `Console.log()` to log sth in the for-loop that is decorated by `track()`, the log Infos shown on the terminal being like that 
![image](https://user-images.githubusercontent.com/82705454/178701716-c738ff7b-9b10-4421-bdd1-cd6d1f29db34.png)

How can I split the bar and the log Infos away, let them in two different rows? 
What argument do I need to give? 👀

**Comment by willmcgugan** [comment]
Both `track` and `log` will need to use the same console object . You can do this by passing in your console to track. e.g. `track(console=console)`

**Comment by KarhouTam** [comment]
Wow! thx for your reply! It is working like what I expected. Thx you again!👍
