### ISSUE TITLE
[BUG] Inconsistency across spinners

### ISSUE THREAD

**Issue by brechtm** [Textualize/rich#2395]
Some spinners, notably the ones built using emojis, include a trailing space. An extra space is inserted between the spinner and the spinner's text. I would argue that this is one space too much.

This difference is easy to see when running `python -m rich.spinner`.

**Comment by willmcgugan** [comment]
Can you cut and paste it, and count the spaces?

**Comment by brechtm** [comment]
Here are two from `python -m rich.spinner`:
```
 ◵ 'circleQuarters'
 🕘  'clock'
```

The frames in _spinners.py clearly include the spaces.

**Comment by willmcgugan** [comment]
The spinners are inherited from another project, and I suspect they are there to compensate for differences in how emojis are rendered on different platforms.

**Comment by willmcgugan** [comment]
I’d consider a PR but since you’re the first to notice, it’s very low priority.
