### ISSUE TITLE
Interactive CLI with tab-completion possible?

### ISSUE THREAD

**Issue by kusibornhauser** [Textualize/rich#2406]
Hi

I really love Rich ❤️. I want to create an interactive CLI application (I don't know if that's the correct term), much like a CLI on a Cisco network device or similar. The Python Cmd2 project is pretty much what I mean - but I want to use rich because it's really beautiful.

Is it possible to create such CLI applications with rich? So that I have a command prompt, and can use tab completion to complete known commands? If so are there examples I can check?

Many thanks!

**Comment by willmcgugan** [comment]
Rich doesn't do this. But you can use cmd2 to handle the prompt and write any output with Rich.

**Comment by kotfu** [comment]
@kusibornhauser: I'm one of the maintainers of https://github.com/python-cmd2/cmd2. We have an [open issue](https://github.com/python-cmd2/cmd2/issues/1216) to investigate how we might make `cmd2` more friendly to use with `rich`. I've done some preliminary work on the [rich](https://github.com/tomcatmanager/tomcatmanager/tree/rich) branch of [tomcatmanager](https://github.com/tomcatmanager/tomcatmanager) to see what it would be like to have an application that used both `cmd2` and `rich`. So far, all the basics work fine with no changes to `cmd2` required.

If you have specific items you are interested in having better support/integration for beyond the tab completion you mentioned above, please feel free to join the discussion on https://github.com/python-cmd2/cmd2/issues/1216.
