### ISSUE TITLE
Provide an ability to mask/exclude certain keys when printing `show_locals=True`

### ISSUE THREAD

**Issue by datajoely** [Textualize/rich#2408]
Hello! We've just started our journey of adopting rich on [kedro](http://github.com/kedro-org/kedro), the first part of this journey introduced the rich logging handler + pretty tracebacks.

We've just had a user, quite rightly, highlight that `show_locals` has printed out some [credentials](https://github.com/kedro-org/kedro/issues/1712#issuecomment-1190071071) in plain text. The immediate fix for this is to set `show_locals=False`, which we will fix quickly. 

My question is as follows, would you accept a PR where we allow the user to exclude certain keys when printing out the stack trace?  I think it would go somewhere in this dictionary comprehension:

https://github.com/Textualize/rich/blob/aea574a215823a7f05e088399745cee00f959324/rich/traceback.py#L376

Thanks!

**Comment by willmcgugan** [comment]
Agree in principal. Another (possibly complimentary) option might be to have a specially crafted local attribute with a set of keys to exclude from locals.

Something like:

```python
def get_password(self):
    _rich_exclude_locals = {"password"}
```

This would be more granular than a global black list.

If we were to add a blacklist, perhaps it should accept a list of regexes?

**Comment by willmcgugan** [comment]
That would be possible with atomic data structures. For other objects you can't really know what attributes will be displayed in the `repr`. It would also be unwise to iterate over the attributes on an object as Rich may end up invoking arbitrary code via properties etc.

It would be possible for Rich to omit arbitrary `__repr__` calls to prevent user code from leaking credentials. You may miss out on some useful debugging information, but that might be a reasonable compromise.

**Comment by danielgafni** [comment]
+1, this seems like a big security issue for production

**Comment by willmcgugan** [comment]
I'd still accept a PR if anyone proposes an elegant solution, but frankly showing locals is a debug aid, and should always be disabled in production.
