### ISSUE TITLE
[BUG] Github source release has wrong version

### ISSUE THREAD

**Issue by bnavigator** [Textualize/rich#2410]
The tag https://github.com/Textualize/rich/releases/tag/v12.5.1 references the wrong commit, where pyproject.toml still has 12.5.0, this results in the wrong source tarball.

The release should have referenced https://github.com/Textualize/rich/commit/cde23ed0a1ecad8c63436148c7e1fb6f0073fca8

**Comment by arjan-s** [comment]
I recently encountered this in NixOS where one of my packages depends on rich 12.5.1. But pip fails due to the Github tag referencing a commit that says it's version 12.5.0. Are there any plans to fix this issue?

**Comment by willmcgugan** [comment]
What error did you get?

Happy to fix it if you can suggest how.

**Comment by arjan-s** [comment]
Pip shows the following error:
```
> ERROR: Could not find a version that satisfies the requirement rich<13.0.0,>=12.5.1 (from pls) (from versions: none)
> ERROR: No matching distribution found for rich<13.0.0,>=12.5.1
```
The easiest fix would be to simply delete the current tag and recreate it at the correct commit.

**Comment by willmcgugan** [comment]
AFAIK git tags have nothing to do with Pip.

**Comment by arjan-s** [comment]
True, mine is a nix-specific issue. The nix package for rich is built from Github tags (source tarballs). [Proof here](https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/development/python-modules/rich/default.nix#L26).
This is different from normal pip behaviour, because by default it uses the package from Pypi, which somehow did get the correct version number.

**Comment by exarkun** [comment]
Issuing a new release, 12.5.2, with consistent package metadata (which nixpkgs could then switch to) should also fix it.

**Comment by exarkun** [comment]
> Issuing a new release, 12.5.2, with consistent package metadata (which nixpkgs could then switch to) should also fix it.

Or to elaborate on @arjan-s 's comment - a new git tag for a revision with consistent metadata would give nixpkgs something it could easily switch to and which would produce an installed package with consistent metadata.

**Comment by arjan-s** [comment]
@exarkun is correct, both options would fix the issue.
@willmcgugan would you be willing to do either of them?

**Comment by arjan-s** [comment]
@willmcgugan I see you closed this as completed, but I don't see a new tag/release and the existing tag isn't fixed either... Could you please take a look again? Thanks!

**Comment by willmcgugan** [comment]
I ran the command you suggested.

If you are saying that a new release will fix it, then one is just around the corner.

**Comment by arjan-s** [comment]
Ah, maybe you forgot to push after the tag command?
```
git push --tags
```
