### ISSUE TITLE
[BUG] Table title's padding has a background color by default in some tmux configs.

### ISSUE THREAD

**Issue by pcroland** [Textualize/rich#2415]
A friend of mine showed me that tables generated by rich has a background for the padding of the title if he uses tmux. On the left you can see how it looks in tmux and on the right how it looks without tmux.

![img](https://i.kek.sh/hKNxzzN25Pp.png) ![img](https://i.kek.sh/RNqddsdKxWE.png)

Code:
```py
summary = Table(title='[not italic bold magenta]Encoding summary')
summary.add_column('[bold cyan]Version\nLatest', style='green')
summary.add_column(f'[bold color(231)]{prog_version}\n{latest_version}', style='color(231)')

summary.add_row('[bold yellow]Output')
summary.add_row('Format', 'TrueHD' if aformat == 'thd' else aformat.upper())
summary.add_row('Channels', channel_number_to_name(outchannels))
summary.add_row('Bitrate', 'N/A' if aformat == 'thd' else f'{str(bitrate)} kbps')
summary.add_row('Dialnorm', 'auto (0)' if args.dialnorm == 0 else f'{str(args.dialnorm)} dB', end_section=True)

summary.add_row('[bold yellow]Input')
summary.add_row('Channels', channel_number_to_name(channels))
summary.add_row('Bit depth', str(bit_depth), end_section=True)
summary.add_row('[bold yellow]Other')
summary.add_row('Files', str(len(filelist)))
summary.add_row('Max threads', str(threads))
summary.add_row('Delay', delay_print)
print(summary)
```
platform: Linux (WSL)</br>
version: latest

**Comment by willmcgugan** [comment]
tmux interprets italic as reverse video for some reason. Not much Rich can do about that, but you could not use italic by setting `header_style=""` on the table.

**Comment by pcroland** [comment]
Isn't it possible to set non italic for every space character?

**Comment by willmcgugan** [comment]
No

**Comment by pcroland** [comment]
Oh, so the line is italic, and the non italic is only applied to the string if i understand correctly. For some reason I thought the non italic tag is applied after the padding. Thanks for the feedback
