### ISSUE TITLE
[question] Using `loguru` & `rich`

### ISSUE THREAD

**Issue by joe733** [Textualize/rich#2416]
> ref: https://github.com/Delgan/loguru/issues/444#issuecomment-1193158638

To use both `rich` & `loguru`, here's what I tried:

### Setup 1: Rich & Loguru on separate sinks.

```py
console = Console()
logger.remove()
logger.add(
    sys.stderr,
    level='TRACE',
    format='<green>{time:YYYY/MM/DD HH:mm:ss}</green> | {level.icon}'
    + '  - <level>{message}</level>',
    colorize=True,
)
````

> **_Problem_:** Live updates are not properly cleared.
> 
> ![image](https://user-images.githubusercontent.com/38415384/180614035-8b431e64-3596-4ab0-b67f-aa3df9a99f8e.png)

### Setup 2: Rich & Loguru on the same sink - with Rich's color system

```py
console = Console()
logger.remove()
logger.add(
    lambda _: console.print(_, end=''),
    level='TRACE',
    format='[not bold green]{time:YYYY/MM/DD HH:mm:ss}[/not bold green] | {level.icon}'
    + '  - [level]{message}[/level]', # NOTE: change in bracket style
    colorize=True,
)
````

> **_Problem_:** Log _messages_ are not dynamically colored.
>
> ![image](https://user-images.githubusercontent.com/38415384/180615418-db4e35eb-527b-4267-a790-09612cb15b65.png)

### Setup 3: Rich & Loguru on the same sink - disabling Rich's color system

```py
console = Console(color_system=None)
logger.remove()
logger.add(
    lambda _: console.print(_, end=''),
    level='TRACE',
    format='<green>{time:YYYY/MM/DD HH:mm:ss}</green> | {level.icon}'
    + '  - <level>{message}</level>',
    colorize=True,
)
````

> **_Problem_:** I lose the colors for non-logging statements.
> 
> ![image](https://user-images.githubusercontent.com/38415384/180614006-19d226f2-f75d-4ae4-b2a5-c913f048f3c6.png)

- Is there a way to change color dynamically for each level of log message (for Setup `#2`)?
- Or use  `loguru` colors & styles to create a new `rich` color scheme or theme?

**Comment by joe733** [comment]
I think I've finally made it. Here's the setup:

```py
console = Console()
logger.remove()

def _log_formatter(record: dict) -> str:
    """Log message formatter"""
    color_map = {
        'TRACE': 'dim blue',
        'DEBUG': 'cyan',
        'INFO': 'bold',
        'SUCCESS': 'bold green',
        'WARNING': 'yellow',
        'ERROR': 'bold red',
        'CRITICAL': 'bold white on red'
    }
    lvl_color = color_map.get(record['level'].name, 'cyan')
    return (
        '[not bold green]{time:YYYY/MM/DD HH:mm:ss}[/not bold green] | {level.icon}'
        + f'  - [{lvl_color}]{{message}}[/{lvl_color}]'
    )


logger.add(
    console.print,
    level='TRACE',
    format=_log_formatter,
    colorize=True,
)
```

Preserves `rich`'s colors and gives dynamic colors to logs.

![image](https://user-images.githubusercontent.com/38415384/180738008-058c0c76-9c01-44ed-bfcc-ff649dacb267.png)

> A good to have would be to preserve the url and number format style. If anyone gets an idea, please go comment below.

**Comment by tumbleintoyourheart** [comment]
@joe733 Hi Joe, have you figured out any ways to make loguru's `logger` to work with rich's `Table`?

**Comment by joe733** [comment]
> @joe733 Hi Joe, have you figured out any ways to make loguru's `logger` to work with rich's `Table`?

Hi @tumbleintoyourheart, no I haven't used it in such a way yet.

**Comment by Ravencentric** [comment]
Thank you for this

**Comment by Asthestarsfalll** [comment]
> @joe733 Hi Joe, have you figured out any ways to make loguru's `logger` to work with rich's `Table`?

Hi, have you figured this out?

**Comment by kureta** [comment]
@yozachar This is almost perfect but rich progress bar keeps redrawing. What I mean is it goes back to 0% and picks up where it left of. Constant flickering between the actual progress and 0%.

**Comment by amas127** [comment]
@yozachar So the key idea is to format by `logoru` and to render by `rich`, but this lost the "compression" or "retention" or other logging options compared to vanilla   `loguru`.

My suggestion is that we should define two sinks:
- whenever you go to the terminal or console, use colorizing as you suggested;
- whenever you go to the consistency choices, files or whatever, use a no-color sink and leave it to loguru itself.

**Comment by NovaViper** [comment]
@nandgator does this work with hex codes with foreground and backgrounds? I made a little theme of hex codes for each log level I want to declare but I can't get Rich to format the logs with the colors I declare. nor does it format the timestamp to the color either

````
def initialize_logger():
    # fmt: off
    DEFAULT_LEVELS = {
        # builtin levels only require the colors
        "debug":    {"fg": "#FF00FF",  "bg": None,      "no": None}, 
        "info":     {"fg": "#FFFFFF",  "bg": None,      "no": None},    
        "success":  {"fg": "#00FF00",  "bg": None,      "no": None},    
        "warning":  {"fg": "#FFA500",  "bg": None,      "no": None},    
        "error":    {"fg": "#FFC0CB",  "bg": None,      "no": None},    
        "critical": {"fg": "#FFFFFF",  "bg": "#C80064", "no": None}, 
        "trace":    {"fg": "#00FFFF",  "bg": None,      "no": None},   
        # custom levels need both the color and level number for loguru
        "notice":   {"fg": "#006400",  "bg": "#90EE90", "no": 25},   
        "start":    {"fg": "#ADD8E6",  "bg": None,      "no": 22},
    }
    # fmt: on

    level_colors = {
        k: f"{v['fg']}{f' on {v["bg"]}' if v['bg'] else ''}"
        for k, v in (DEFAULT_LEVELS).items()
    }
    print(level_colors)
    console = Console()

    def _log_formatter(record) -> str:
        lvl_color = level_colors.get(record["level"].name.lower(), "#FFFFFF")
        return f"<fg #41605e>[{{time:HH:mm:ss}}]</fg #41605e> <fg {lvl_color}>[{{level}}]	{{message}}</fg {lvl_color}>"

    logger.remove(0)  # Remove default logger
    logger.add(
        # sys.stderr,
        console.print,
        format=_log_formatter,
        # format="<fg #41605e>[{time:HH:mm:ss}]</fg #41605e> <level>[{level}]	{message}</level>",
        diagnose=False,
        level="TRACE",
    )
    # Register all custom levels with loguru (case-insensitive)
    for name, conf in DEFAULT_LEVELS.items():
        name = name.upper()
        fg = conf.get("fg", "#FFFFFF")
        bg = conf.get("bg")
        color = f"<fg {fg}>" + (f"<bg {bg}>" if bg else "")
        no = conf.get("no")
        logger.level(name, no=no, color=color)
````

level_colors outputs as this:
```
{'critical': '#FFFFFF on #C80064',
 'debug': '#FF00FF',
 'error': '#FFC0CB',
 'info': '#FFFFFF',
 'notice': '#006400 on #90EE90',
 'start': '#ADD8E6',
 'success': '#00FF00',
 'trace': '#00FFFF',
 'warning': '#FFA500'}
```

**Comment by NovaViper** [comment]
Additionally, does this way also let you utilize Rich's traceback feature or loguru's? I noticed any and all tracebacks vanish as soon as I started using `console.print` as the sink
