### ISSUE TITLE
[BUG] Outdated documents about rich for jupyter

### ISSUE THREAD

**Issue by royess** [Textualize/rich#2426]
**Describe the bug**

In [installation instructions](https://rich.readthedocs.io/en/stable/introduction.html#installation), `pip install rich[jupyter]` is suggested for one who wants to use rich in jupyter. But it does not work in my platform because it is not registered.  And directly `import rich.jupyter` works instead. I suppose the documents are outdated here.

**Platform**
<details>
<summary>
Ubuntu 20.04. Python 3.9.
</summary>

</details>

**Comment by willmcgugan** [comment]
What exactly isn't working for you? Do you have tracebacks / error messages you could paste?

**Comment by royess** [comment]
`pip install rich[jupyter]` is not working for me.

```bash
(base) ➜  .ssh pip install rich[jupyter]
zsh: no matches found: rich[jupyter]
```

**Comment by willmcgugan** [comment]
I think zsh does something with square brackets. Try `pip install "rich[jupyter]"`
