### ISSUE TITLE
[question] overhead of rich.progress?

### ISSUE THREAD

**Issue by Freed-Wu** [Textualize/rich#2444]
In tqdm's README.rst:

> Overhead is low – about 60ns per iteration (80ns with tqdm.gui), and is unit tested against performance regression. By comparison, the well-established ProgressBar has an 800ns/iter overhead.
> In addition to its low overhead, tqdm uses smart algorithms to predict the remaining time and to skip unnecessary iteration displays, which allows for a negligible overhead in most cases. 

So, how about rich.progress? I cannot found any information in <https://rich.readthedocs.io/en/stable/progress.html>. If there exists a test bench (rich.progress, tqdm, prompt-toolkit.progress, etc), it will be greater.

Thanks.

**Comment by willmcgugan** [comment]
Rich uses similar techniques. The tqdm project keeps [benchmarks](https://tqdm.github.io/tqdm/#benchmarks.track_alternatives) which includes Rich.

**Comment by Freed-Wu** [comment]
It looks like rich.progress is fastest. Great!
