### ISSUE TITLE
[BUG] When use pudb to debug, rich.progress.track will output incorrectly

### ISSUE THREAD

**Issue by Freed-Wu** [Textualize/rich#2445]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

Edit this with a clear and concise description of what the bug.

```python
from rich.progress import track
from tqdm import tqdm

for i in tqdm(range(5)):
    print(i)

for i in track(range(5)):
    print(i)
```

Then `pudb3 test.py`, when the current line in the tqdm's for loop, no progress occur
![Screenshot from 2022-08-04 18-30-30](https://user-images.githubusercontent.com/32936898/182826693-71aa3b01-0263-4550-8624-fee849d2c366.png)

press `!` to enter repl, progress occurs:
![Screenshot from 2022-08-04 18-30-38](https://user-images.githubusercontent.com/32936898/182826702-b7e6e1c5-3231-4dae-830b-1a6d56118486.png)

Press `<CR>`, you can input in repl:
![Screenshot from 2022-08-04 18-30-50](https://user-images.githubusercontent.com/32936898/182826725-ed9cda61-6a3a-4ac1-87ae-3867b75bfce6.png)

press `<C-D>`, you can return pudb interface.

HOWEVER, in track's for loop:
![Screenshot from 2022-08-04 18-32-50](https://user-images.githubusercontent.com/32936898/182826752-01b004f5-fac0-4c8e-8a5f-1b51be75842e.png)

Press `!`
![Screenshot from 2022-08-04 18-33-00](https://user-images.githubusercontent.com/32936898/182826770-c564f5bd-9321-4a5f-acdb-5f5423f3cb28.png)

Press `<CR>`
![Screenshot from 2022-08-04 18-33-13](https://user-images.githubusercontent.com/32936898/182826812-bdf13120-bbea-4210-9ebe-84c3e167f3c8.png)

Press `<C-D>`, and press `j` or `k` to move down and up:
![Screenshot from 2022-08-04 18-33-20](https://user-images.githubusercontent.com/32936898/182826823-9a4bef7f-294b-41dc-ac03-355805a60d11.png)

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
Linux 5.18.15, kitty

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich

╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=196 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 52                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=196, height=52),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=196,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=52,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=196, height=52)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 196                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'tmux-256color',       │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'tmux',        │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
rich==12.5.1
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by willmcgugan** [comment]
Rich progress bars auto-refresh features uses a thread to ensure spinners / time remaining works, even if you don't explicitly call refresh. This will conflict with terminal based debuggers that also write to stdout. We don't have a solution for this, and we usually recommend disabling scrollbars while debugging. You're using `tqdm` which I don't think provides a way of exposing that.

**Comment by Freed-Wu** [comment]
> We don't have a solution for this, and we usually recommend disabling scrollbars while debugging. You're using tqdm which I don't think provides a way of exposing that.

So, this bug cannot be fixed, the only solution is use tqdm to replace rich, right?

Thanks!

**Comment by Freed-Wu** [comment]
Is there any method to disable rich.progress when user uses pudb to debug? Such as when pudb is used, it convert rich.progress to invisable? @inducer

**Comment by Freed-Wu** [comment]
when pudb try to debug a file, pudb will set sys.argv[0] to 'pudb', so rich.progress can detect pudb then disable progress. Just my 2c.

**Comment by stdedos** [comment]
I went with the `if "pdb" in sys.modules or "pudb" in sys.modules`

**Comment by Freed-Wu** [comment]
> if "pdb" in sys.modules or "pudb" in sys.modules

Does rich accept PR of this type or have better solution?
