### ISSUE TITLE
[REQUEST]Please add "no_wrap" to Panel object

### ISSUE THREAD

**Issue by MaZED-UP** [Textualize/rich#2454]
`no_wrap= True` works well in Table objects and it will be great if you add that parameter to Panel objects, too.

**Comment by willmcgugan** [comment]
What Label object? The only labels in Rich are in the Tree? is that what you mean?

**Comment by MaZED-UP** [comment]
Sorry, Panel not Label

**Comment by willmcgugan** [comment]
Ah. Try this:

```python
Panel(Text("Hello, World! " * 10, no_wrap=True))
```

**Comment by MaZED-UP** [comment]
Thanks!

**Comment by MaZED-UP** [comment]
> What Label object? The only labels in Rich are in the Tree? is that what you mean?

Tree isn't leaving yet 😅

This line `tree_panel = Panel(Text(tree, no_wrap=True), box=box.HEAVY, width=50)` gave me this error:
`AttributeError: 'Tree' object has no attribute 'translate'`.

Is there any workaround?

**Comment by willmcgugan** [comment]
The `Text` constructor takes a string. I'm guessing you have given it a Tree ??

**Comment by MaZED-UP** [comment]
Yes. Some tree branches are long and I need `no_wrap=True` or the `overflow='ellipsis'`.
I can think of applying `Text(branch_text, no_wrap=True)` to every branch or making a function and using `eval` but I believe both are not ideal.

**Comment by willmcgugan** [comment]
Setting Tree labels to Text objects is a good solution.

**Comment by MaZED-UP** [comment]
So far so good, but there's one thing:

`tree.add(Text(f':file_folder: Documents', style='bold', no_wrap=True, overflow='ellipsis'))` 
When I print the tree I find `:file_folder:` (as it is) not `📁`.

I know I can use the actual emoji `"📁"`, but I want to know how I can implement `":file_folder:"` inside `Text()`?

**Comment by willmcgugan** [comment]
You can use `Text.from_markup` which will also process console markup. Or you can do `Emoji.replace`

**Comment by MaZED-UP** [comment]
But there is no `no_wrap` parameter in `Text.from_markup`, so the `Emoji.replace` solution will work.
Lastly, I appreciate your time and help.
