### ISSUE TITLE
[BUG] Console(no_color=True) does not work on Windows 10

### ISSUE THREAD

**Issue by pirxthepilot** [Textualize/rich#2457]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

The "no_color=True" Console parameter does not seem to do anything on Windows 10. I tested on both Cmder and native cmd.exe terminals and got the same results. See screenshots below.

Cmder:
![richbug01](https://user-images.githubusercontent.com/7690118/183566141-724f7390-f9f9-4063-bf31-b0144e391975.PNG)

cmd.exe
![richbug02](https://user-images.githubusercontent.com/7690118/183566181-5ef45bf6-366c-4c69-b6f8-6ad25d5aff41.PNG)

for reference, this is what it looks like from my Ubuntu laptop:

![richbug-linux-ok](https://user-images.githubusercontent.com/7690118/183566308-62bbd545-1c90-4345-bd3c-a228ea0f5f35.png)

Also happy to help fix this if you can point me in the right direction. Thank  you!

**Platform**
<details>
<summary>Click to expand</summary>

OS: Windows 10

**Cmder:**

┌───────────────────────── <class 'rich.console.Console'> ─────────────────────────┐
│ A high level console interface.                                                  │
│                                                                                  │
│ ┌──────────────────────────────────────────────────────────────────────────────┐ │
│ │ <console width=155 ColorSystem.WINDOWS>                                      │ │
│ └──────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                  │
│     color_system = 'windows'                                                     │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 83                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = True                                                          │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=155, height=83),             │
│                        legacy_windows=True,                                      │
│                        min_width=1,                                              │
│                        max_width=155,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=83,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=155, height=83)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 155                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
┌─── <class 'rich._windows.WindowsConsoleFeatures'> ────┐
│ Windows features available.                           │
│                                                       │
│ ┌───────────────────────────────────────────────────┐ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ └───────────────────────────────────────────────────┘ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
└───────────────────────────────────────────────────────┘
┌────── Environment Variables ───────┐
│ {                                  │
│     'TERM': 'cygwin',              │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': '157',              │
│     'LINES': '83',                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
└────────────────────────────────────┘
platform="Windows"

**cmd.exe**

┌───────────────────────── <class 'rich.console.Console'> ─────────────────────────┐                                    │ A high level console interface.                                                  │                                    │                                                                                  │                                    │ ┌──────────────────────────────────────────────────────────────────────────────┐ │                                    │ │ <console width=119 ColorSystem.WINDOWS>                                      │ │                                    │ └──────────────────────────────────────────────────────────────────────────────┘ │                                    │                                                                                  │                                    │     color_system = 'windows'                                                     │                                    │         encoding = 'utf-8'                                                       │                                    │             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │                                    │           height = 30                                                            │                                    │    is_alt_screen = False                                                         │                                    │ is_dumb_terminal = False                                                         │                                    │   is_interactive = True                                                          │                                    │       is_jupyter = False                                                         │                                    │      is_terminal = True                                                          │                                    │   legacy_windows = True                                                          │                                    │         no_color = False                                                         │                                    │          options = ConsoleOptions(                                               │                                    │                        size=ConsoleDimensions(width=119, height=30),             │                                    │                        legacy_windows=True,                                      │                                    │                        min_width=1,                                              │                                    │                        max_width=119,                                            │                                    │                        is_terminal=True,                                         │                                    │                        encoding='utf-8',                                         │                                    │                        max_height=30,                                            │                                    │                        justify=None,                                             │                                    │                        overflow=None,                                            │                                    │                        no_wrap=False,                                            │                                    │                        highlight=None,                                           │                                    │                        markup=None,                                              │                                    │                        height=None                                               │                                    │                    )                                                             │                                    │            quiet = False                                                         │                                    │           record = False                                                         │                                    │         safe_box = True                                                          │                                    │             size = ConsoleDimensions(width=119, height=30)                       │                                    │        soft_wrap = False                                                         │                                    │           stderr = False                                                         │                                    │            style = None                                                          │                                    │         tab_size = 8                                                             │                                    │            width = 119                                                           │                                    └──────────────────────────────────────────────────────────────────────────────────┘                                    ┌─── <class 'rich._windows.WindowsConsoleFeatures'> ────┐                                                               │ Windows features available.                           │                                                               │                                                       │                                                               │ ┌───────────────────────────────────────────────────┐ │                                                               │ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │                                                               │ └───────────────────────────────────────────────────┘ │                                                               │                                                       │                                                               │ truecolor = False                                     │                                                               │        vt = False                                     │                                                               └───────────────────────────────────────────────────────┘                                                               ┌────── Environment Variables ───────┐                                                                                  │ {                                  │                                                                                  │     'TERM': None,                  │                                                                                  │     'COLORTERM': None,             │                                                                                  │     'CLICOLOR': None,              │                                                                                  │     'NO_COLOR': None,              │                                                                                  │     'TERM_PROGRAM': None,          │                                                                                  │     'COLUMNS': None,               │                                                                                  │     'LINES': None,                 │                                                                                  │     'JUPYTER_COLUMNS': None,       │                                                                                  │     'JUPYTER_LINES': None,         │                                                                                  │     'JPY_PARENT_PID': None,        │                                                                                  │     'VSCODE_VERBOSE_LOGGING': None │                                                                                  │ }                                  │                                                                                  └────────────────────────────────────┘                                                                                  platform="Windows"  

rich==12.5.1

</details>

**Comment by pirxthepilot** [comment]
Update: Seems to work if I explicitly set `legacy_windows=False`:

![richbug-windows-legacy-false-ok](https://user-images.githubusercontent.com/7690118/183599105-eb43f1e8-935e-46f3-8eef-7ad63ea53335.png)

**Comment by MarkZH** [comment]
The bug also does not occur when running cmd.exe within [windows terminal](https://docs.microsoft.com/en-us/windows/terminal/install).

**Comment by darrenburns** [comment]
It was an issue with rendering on "legacy" terminals on Windows, so would only affect people using older versions of cmd.

In legacy rendering, Rich calls Win32 APIs directly, rather than using the same codepath as on Linux/MacOS. Turns out that code didn't consider `no_color` at all!

Fixed as part of https://github.com/Textualize/rich/pull/2458, so this should be resolved in the next release of Rich. Keep an eye out for the next release and let us know if you hit any further issues with it 🙂

**Comment by pirxthepilot** [comment]
Thanks so much for fixing in a timely manner!
