### ISSUE TITLE
[BUG] Console has No attribute save_svg

### ISSUE THREAD

**Issue by Pranav4399** [Textualize/rich#2465]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/willmcgugan/rich/issues).

**Describe the bug**

I'm trying to save the table created in the console using rich as SVG image using save_svg function but encountering the above error mentioned in the title. Please find my code and error below.

![image](https://user-images.githubusercontent.com/28348429/184615704-08a20a26-c893-4ea9-bb18-d42d0d0205b6.png)

![image](https://user-images.githubusercontent.com/28348429/184615767-5656c246-56dd-40c9-8051-319c136ab6bd.png)

**Platform**
OS - Windows.
Python Version - 3.10.0

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```
![image](https://user-images.githubusercontent.com/28348429/184616068-57cce6f2-dca3-464f-8470-8e475e78df7e.png)

**Comment by Samjith888** [comment]
Same issue. 

`AttributeError: 'Console' object has no attribute 'save_svg'`

**Comment by willmcgugan** [comment]
You will need to update your version of Rich.

```
pip install rich -U
```
