### ISSUE TITLE
creating default configuration for Tables

### ISSUE THREAD

**Issue by shahzebsiddiqui** [Textualize/rich#2471]
So i have a general question, i use `Tables` to print output through several python modules and i would like to have a default configuration set for tables to include `no_wrap=False` and `overflow="fold"` for the columns which would be applied to all tables. The thing is that this is an option for `table.add_column` so i dont want to specify the column name but rather just use some globally defined column that i can use.

Is this possible, am i suppose to use define a global instance of Column class https://rich.readthedocs.io/en/stable/reference/table.html#rich.table.Column and import it throughout the codebase. Its not clear to me.

My main objective is to get all tables to have `overflow=fold` and `no_wrap=False` since this causes some issue with output when i am running jobs in CI where `COLUMNS` is causing some output to get messed up. I have to update this across many files and it easy to miss one table section so i want to apply this for all columns.

Can you please advise how i should go about this, preferably with some example.

**Comment by willmcgugan** [comment]
Write a function that creates a table to your requirements.
