### ISSUE TITLE
[BUG] `no_wrap` doesn't work for Chinese(maybe all CJK) text in Table Column

### ISSUE THREAD

**Issue by liushuaikobe** [Textualize/rich#2494]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2098020/187029668-56c4bde1-003c-44fc-adb7-29667fc57a2d.png)

**Platform**
macOS Monterey 12.5.1
iTerm2 Build 3.4.16 & System Terminal 2.12.7(445)

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/2098020/187029622-787f81cd-d4a6-47e9-92b8-fc61a88065b1.png)

![image](https://user-images.githubusercontent.com/2098020/187029591-cb2907be-f19e-487a-93d2-d312493f37bb.png)

</details>

**Comment by willmcgugan** [comment]
Rich isn't aware of the rules regarding wrapping Chinese, and will wrap on spaces only. However, you can set `overflow="fold"` which will hopefully be close enough.
