### ISSUE TITLE
[BUG] progress can not display immediately in os.execvp().

### ISSUE THREAD

**Issue by HugeTimor** [Textualize/rich#2496]
**Describe the bug**

progress can not display when i run it at the process which created by `os.execvp().`

here my code:
```
# code in main.py
def do(param):
    time.sleep(1)
    msg = '%d in %d' % (param, os.getpid())
    # print(msg)
    return msg


def parallel_execute(params, func):
    results = []

    progress = Progress(TextColumn("[progress.description]{task.description}"),
                        BarColumn(),
                        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
                        TimeElapsedColumn(),
                        console=Console(file=sys.stdout),
                        transient=False,
                        refresh_per_second=5)
    task_id = progress.add_task("[cyan]Working...", total=len(params))

    progress.start()
    with multiprocessing.Pool(processes=4) as pool:
        for result in pool.imap(func, params):
            results.append(result)
            progress.advance(task_id)
    progress.stop()
    return results


if __name__ == '__main__':
    print('main pid: %d' % os.getpid())

    tasks = []
    for x in range(12):
        tasks.append(x)

    results = parallel_execute(tasks, do)
    print(results)
```

run it directly, it work perfectly.  But when i run it in os.execvp() the progress not display in immediately.

![image](https://user-images.githubusercontent.com/8110701/187055977-809d3a9e-4243-4368-9702-f04e727daaa1.png)

code run in execvp()
```
me = [sys.executable, '/path/main.py', '--']
print('trigger pid: %d' % os.getpid())
print('run os.execvp()')
os.execvp(me[0], me)
```

result of run in execvp()
![image](https://user-images.githubusercontent.com/8110701/187056067-9c9a78ea-20b5-4920-b56a-1a2413efb24f.png)

**Platform**
<details>
<summary>Click to expand</summary>

platform: Mac; terminal: iTerm2

I am using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```
python -m rich.diagnose:
![image](https://user-images.githubusercontent.com/8110701/187056241-2d3af6da-f9c6-490a-9403-95e25b6b123b.png)
![image](https://user-images.githubusercontent.com/8110701/187056266-72e63d99-955c-4169-a69f-960e64873c3b.png)

pip freeze | grep rich:
`rich==12.5.1`

</details>

**Comment by willmcgugan** [comment]
I suspect you need to copy environment variables in the `execvp` call. Not an issue with Rich per se.
