### ISSUE TITLE
[REQUEST]How to make chat room in console?

### ISSUE THREAD

**Issue by dolaCmeo** [Textualize/rich#2503]
Is there some how to make chat room in console.
the key point is, How to make output with none-blocking input at same time?

**I wish it will be like:**
+ Message area display like output logs.
+ Input area always at the console bottom, wait for some input. 
when press <kbd>Enter</kbd>, will targer some function

- - -
ps: `threading.Thread` will blocking console output, when other thread run for `while True: input()`

**Comment by willmcgugan** [comment]
Rich isn't designed to do this. You could look at Textual.
