### ISSUE TITLE
[BUG] Unable to use pager with long table

### ISSUE THREAD

**Issue by tonycombocurve** [Textualize/rich#2506]
I have created a table as per the documentation and it works as expected when I do the following:

```
console.print(table)
```

Since the table is fairly long, I tried to page it as follows:

```
while console.pager():
   console.print(table)
```

Unfortunately, what happens is that it repeatedly prints the table in a loop. How can I page my table?

<details>
**Platform**

Edition Windows 10 Pro
Version 21H2
Installed on ‎4/‎16/‎2022
OS build 19044.1889
Windows Feature Experience Pack 120.2212.4180.0
Python 3.9.13

Environment Variables:

'TERM': None,
'COLORTERM': None,
'CLICOLOR': None,
'NO_COLOR': None,
'TERM_PROGRAM': None,
'COLUMNS': None,
'LINES': None,
'JUPYTER_COLUMNS': None,
'JUPYTER_LINES': None,
'JPY_PARENT_PID': None,
'VSCODE_VERBOSE_LOGGING': None

rich==12.5.1

</details>

**Comment by willmcgugan** [comment]
Use the “with” keyword, not “while”

**Comment by tonycombocurve** [comment]
Will,

Thanks for catching that. When I print is without paging, this is what I see (abbreviated):

***@***.***

When I use the pager, this is what I see:

***@***.***

Any idea how to resolve this?

Thanks again for your prompt response!

-Tony

**Comment by willmcgugan** [comment]
Does it make any difference if you set the env var PYTHONIOENCODING to utf-8?

**Comment by tonycombocurve** [comment]
Makes no difference. Thanks again for your help.

Have a wonderful weekend.

-Tony

**Comment by AndreasPantle** [comment]
Why is this issue closed? The print_json is also not working when using it in an `with console.pager():` context.

**Comment by willmcgugan** [comment]
@AndreasPantle If you think there is a problem, open a new issue.
