### ISSUE TITLE
[REQUEST] How do I obfuscate secret strings in output?

### ISSUE THREAD

**Issue by red8888** [Textualize/rich#2516]
I want to obfuscate secret strings so they are dumped to the console.

Pythons logger has formatters so I could use that for this: https://stackoverflow.com/questions/48380452/mask-out-sensitive-information-in-python-log

How can I pass a formatter with a list of strings to obfuscate (replace with "******") to `console.print()`

I'm sure this is possible, but I'm not sure how best to accomplish this with rich.

**Comment by willmcgugan** [comment]
Rich doesn't have any such functionality. I'd suggest extending Console and overriding `print`.
