### ISSUE TITLE
[BUG] Level Name Repeat

### ISSUE THREAD

**Issue by aress31** [Textualize/rich#2522]
For some reason using `logging` with a `Rich` `handler` causes the level name to be repeated, see:

![image](https://user-images.githubusercontent.com/11601622/189872694-dc1b97ab-d219-44cd-9ba2-14ed0720124e.png)

Relevant code:

```python
def init_logger(log_level: str, console: Console):
    logging.basicConfig(
        level=log_level,
        format="%(levelname)s %(message)s",
        datefmt="[%X]",
        handlers=[RichHandler(
            rich_tracebacks=True,
            console=console
        )]
    )
```

```python
if __name__ == "__main__":
    try:
        args = init_args()
        console = Console()
        init_logger(args.log_level, console)

        with console.status("[bold green]In progress..."):
            main(args, console)

    except KeyboardInterrupt:
        pass
```

```python
def main(args: ArgumentParser, console: Console):
    logger = logging.getLogger('rich')

    logger.debug(args)

    logger.info("Test")

    --- SNIP ---
```

Does anyone know how can I fix that?

EDIT: Additionally, style markups are not recognise and result in something like:

![image](https://user-images.githubusercontent.com/11601622/189878005-4ae2c42b-e41c-41c9-ae65-5e17cc50dc85.png)

**Comment by willmcgugan** [comment]
The Rich handler puts the level name in by default, so you don't need it in `format`

You can enable markup with markup=True in the handler. 

Both issues can be found in the docs, btw.
