### ISSUE TITLE
Rich Live display specified console, but the style of console is not used.

### ISSUE THREAD

**Issue by LampV** [Textualize/rich#2542]
Edit:  `live = Live(auto_refresh=False, console=console) doesn't work .

```python
from rich.text import Text

from rich.console import Console
from rich.live import Live

console = Console(style="blue on white")
live = Live(auto_refresh=False, console=console)
live.start()

console.print(Text("Hello from console"))
live.update(Text("Hello from live\n"), refresh=True)
```
<img width="584" alt="截屏2022-09-23 22 47 03" src="https://user-images.githubusercontent.com/38694199/191989171-c095be37-30c7-43cb-8d91-7ed1c7e7aa2b.png">

---

I'm using Live display to output and update in the specified area of my screen.
I use `Live` like this, and I found that when I specified `console`, `live.update` won't use style of that console:
```python
from rich.text import Text

from rich.console import Console
from rich.live import Live

console = Console(style="blue on white")
live = Live(auto_refresh=False)
live.start()

console.print(Text("Hello from console"))
live.update(Text("Hello from live\n"), refresh=True)
```
The result like this:
<img width="433" alt="截屏2022-09-23 20 33 39" src="https://user-images.githubusercontent.com/38694199/191961146-199442e4-0251-4bd3-a195-22be7609c89c.png">

I believe the reason is `LiveRender` don't have `style` prop and won't pass it to `_live_render.renderable`.
Is such behavior expected?

**Comment by willmcgugan** [comment]
Pass your console in to the `Live` constructor.

**Comment by LampV** [comment]
Sorry I forgot to add it to the demo, but in fact it still doesn't work
<img width="584" alt="截屏2022-09-23 22 47 03" src="https://user-images.githubusercontent.com/38694199/191988606-1c4abab1-8424-49af-8157-013e76fc2b0b.png">

**Comment by willmcgugan** [comment]
The console style affects anything printed, but it won't affect `live.update`

You should also be using the Live context manager, or call `live.stop()`

**Comment by LampV** [comment]
Thanks for your reply. I noticed that RichRender has prop `style`, passing console.style to it works well.  
I wonder if you are considering making Live also affected by the console style.
```python
from rich.text import Text
from rich.console import Console
from rich.live import Live
from rich.live_render import LiveRender


class StyledLive(Live):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._live_render = LiveRender(
            self.get_renderable(), style=self.console.style if self.console.style else "", vertical_overflow=kwargs.get("vertical_overflow")
        )

console = Console(style="blue on white")

with StyledLive(auto_refresh=False, console=console) as live:
    console.print(Text("Hello from console"))
    live.update(Text("Hello from styled live\n"), refresh=True)
```
<img width="194" alt="截屏2022-09-27 12 00 30" src="https://user-images.githubusercontent.com/38694199/192428892-0634dd15-7912-4aea-959a-1441bd713077.png">
