### ISSUE TITLE
[BUG] Numbers get printed differently

### ISSUE THREAD

**Issue by StayMadYourBad** [Textualize/rich#2545]
```
from rich.console import Console

console = Console()

console.print(f"[Task 30] ==> On Webpage", style = f"bold bright_yellow")

```

Using the following code, the number 30 gets printed in a cyan/blue color rather than a bold bright yellow

![Screenshot_7](https://user-images.githubusercontent.com/83351519/191992174-13183418-ce6c-437f-b3ab-2a52d325c7cb.png)

**Comment by willmcgugan** [comment]
Please see [docs on highlighting](https://rich.readthedocs.io/en/latest/highlighting.html)
