### ISSUE TITLE
Bolding not available in the command prompt

### ISSUE THREAD

**Issue by StayMadYourBad** [Textualize/rich#2546]
When I run the following code in the vscode terminal, it is bolded as such

```
from rich.console import Console
console = Console(highlight = False)
console.print(f"[Task 30] ==> Something", style = f"bold pale_turquoise1")
```

![Screenshot_9](https://user-images.githubusercontent.com/83351519/192059276-0b8d1358-0517-4c34-add0-39f3c47ad521.png)

However when I run it in the command prompt, the bold color does not seem to apply.
![Screenshot_8](https://user-images.githubusercontent.com/83351519/192059292-ddba7b6b-6e88-4b8a-9ae3-4bbfd897ceaa.png)

**Comment by willmcgugan** [comment]
Windows legacy doesn't support bold. Try the new Windows Terminal.
