### ISSUE TITLE
RichHandler file/line info malformed on GitLab CI runner

### ISSUE THREAD

**Issue by awgymer** [Textualize/rich#2551]
I am not sure if this is an issue with the GitLab CI runner or `rich` and I assume it may be the former but perhaps there is some setting in rich I can adjust?

When using the logging handler the filename and line number are displayed as follows, rather than as the filename and line number in grey. Something with the ansi code seems borked? 
The output looked normal when run locally on Mac. 
```
INFO     Test passed  [✔]                                            d=144076;file:///usr/local/lib/python3.10/site-packages/tools/build.py2mbuild.py:d=781518;file:///usr/local/lib/python3.10/site-packages/tools/build.py#852m85
````

EDIT: I tried adding `PYTHONIOENCODING=utf8` which was mentioned in an older issue but this had no impact.

**Comment by willmcgugan** [comment]
Looks like it is GitLib that is borked. It is stripping ansi codes for links incorrectly. You could set the env vat TERM=dumb to not write escape codes.

**Comment by jzenoz** [comment]
TERM=dumb didn't work for me with FORCE_COLOR set despite what it says in the console api page (doesn't work for the logging handler?):
https://rich.readthedocs.io/en/stable/console.html#environment-variables
> If the environment variable FORCE_COLOR is set, then color/styles will be enabled regardless of the value of TERM. This is useful on CI systems which aren’t terminals but can none-the-less display ANSI escape sequences.

disabling show_path fixed this issue for me:
`handlers=[RichHandler(show_path=False, rich_tracebacks=True, tracebacks_suppress=[subprocess])],`
