### ISSUE TITLE
[REQUEST] Support FORCE_COLORS=0

### ISSUE THREAD

**Issue by hynek** [Textualize/rich#2562]
**How would you improve Rich?**

The latest version added support for the env variable FORCE_COLORS env variable ([without documenting it 🤓](https://rich.readthedocs.io/en/stable/search.html?q=FORCE_COLORS&check_keywords=yes&area=default)) and forces colors independently from its values. Setting a variable to 0 is a common way to disable a function.

**What problem does it solve for you?**

I'm using nox for testing and I can only override variables, but not delete them.

This leads to the problem that I can't end-to-end test doc2dash with FORCE_COLORS on in CI, because there's no other way to disable ANSI codes. NO_COLORS is close, but it still does bold text etc.

**Comment by willmcgugan** [comment]
This is why I was so reluctant to add it. In some apps setting `FORCE_COLORS` to _anything_ enabled colors. In others, setting it to `0` disabled colors. So you have a situation that `FORCE_COLORS=0` would enable on some apps and disable on others.

I relented on adding it when someone did some research that in a significant majority of `FORCE_COLORS=<anything>` would enable colors. Which seems to be an emerging standard (or as close to one as you can expect).

If you want to disable all escape codes, you can do `TERM=dumb`.

I'll update the docs...

**Comment by hynek** [comment]
It would be nice if there'd be a dedicated overview of the env variables rich is working on. 🤔

**Comment by willmcgugan** [comment]
There is. I just added `FORCE_COLOR` 

https://rich.readthedocs.io/en/latest/console.html#environment-variables

**Comment by hynek** [comment]
you've got a markdownism `removes _color_ only` in there btw :)
