### ISSUE TITLE
[BUG] Hyperlinks in logger messages don't work on VS Code

### ISSUE THREAD

**Issue by ma-sadeghi** [Textualize/rich#2572]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/textualize/rich/issues).

**Describe the bug**

The hyperlinks in the logger messages don't work in VS Code.

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
Linux

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

![image](https://user-images.githubusercontent.com/14086031/195114453-0f3793ea-0eb2-44ea-926c-4f421aaba503.png)
![image](https://user-images.githubusercontent.com/14086031/195114497-84616cba-9d99-456c-a242-f57c20a137e1.png)

</details>

**Comment by willmcgugan** [comment]
If it works elsewhere and not in VScode, then it will be a VSCode issue.

**Comment by willmcgugan** [comment]
If this is still an issue, you might want to raise it with the VSCode devs.
