### ISSUE TITLE
Speed up console.log

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/rich#2577]
In Rich we use `inspect.stack`, which we now know is very slow.

I suspect if we change it to `inspect.stack(0)` it will be a lot faster. Easiest PR ever?

**Comment by darrenburns** [comment]
Wasn't `inspect.currentframe()._f_back` or whatever faster? Thought I seen that in a PR yesterday

**Comment by willmcgugan** [comment]
Yeah, its a slight improvement over stack(0) I believe. Both are a massive win over `inspect.stack()`
