### ISSUE TITLE
[REQUEST] Provide a means to replace the BarColumn with a message when the task is stopped 

### ISSUE THREAD

**Issue by hpe-ykoehler** [Textualize/rich#2582]
As in https://github.com/jedib0t/go-pretty/tree/main/progress
I would like to be able to indicate that a task is done/completed when it is not a known quantity (spinner).

on the event of a call to "progress.stop_task(task_id, message="Done.")"  I would like for the BarColumn to display the word "Done." and stop rendering any spinner/bar stuff, stop the elapsed time timer, and stop refreshing as well.  For that, the timer display may need to be moved up, so that the next render displays the task as done at the beginning and then only refresh the other progress bar under it on the next refresh interval.

example:
task 1    <spinning/bar indication>                            05:03:00
task 2    <spinning/bar indication>                            01:03:00
task 3    <spinning/bar indication>                            02:43:00

calling progress.stop_task(2, message="[green]Done") would then display

task 2    Done.                                                      01:05:00
task 1    <spinning/bar indication>                     05:05:00
task 3    <spinning/bar indication>                     02:45:00

And then stop refreshing task 2 ever, but continue to refresh any other task.

I would also like to get the possibility to replace all taskbar with 

progress.stop(mesage="[red]Aborted.")

task 2    Done.                                                       01:05:00
task 1    Aborted.                                                  05:05:00
task 3    Aborted.                                                  02:45:00

**Comment by hpe-ykoehler** [comment]
I see there is something equivalent under SpinnerColumn(finished_text).

I would also like that for a BarColumn() and I would like to be able to say BarColumn(finished_text: "[Green]${task.finished_text}") basically.

**Comment by willmcgugan** [comment]
You can customize BarColumn to your requirements. See [the docs on column customization](https://rich.readthedocs.io/en/latest/progress.html#customizing) for details.

**Comment by hpe-ykoehler** [comment]
I was able to achieve most of this using progress.console.print just before removing my task, the output is emitted at the top like I wanted.
