### ISSUE TITLE
[REQUEST] Provide an overall progress bar built-in that will always render last

### ISSUE THREAD

**Issue by hpe-ykoehler** [Textualize/rich#2583]
I would like to be able to call progress.summary_task() where I could determine the column being displayed which would be different than the other task.  Also the summary would be either always display at the top or at the bottom of any refreshed progress bar in the progress context.

task 2    Done                                                       01:05:00
task 1    <spinning/bar indication>                     05:05:00
task 3    <spinning/bar indication>                     02:45:00
[1/3]      <spinning/bar indication>                     06:04:00      <-- summary/total

The summary would use the task within the progress context as a way to indicate progress.  I would like to have the option for that count to include all tasks ever added to the progress, or just the ones that are still actively being refreshed.

The total number of task would also allow for dynamic count, so that as the system works, I can add a new task and the summary would then show [1/4] for example.

Any stopped task would increase/advance the first number.

**Comment by willmcgugan** [comment]
I'm not sure I follow 100%, but tis doesn't sound like something that should be added to the core lib. The Progress and Live class can be customized to render virtually anything.

**Comment by hpe-ykoehler** [comment]
Agree, I could figure out a way to do it, it just is not as simple as the other one I used to work with.
