### ISSUE TITLE
Link format string in docs to Python string formatting mini-language

### ISSUE THREAD

**Issue by hpe-ykoehler** [Textualize/rich#2584]
In the code we see

 text_format: str = "[progress.percentage]{task.percentage:>3.0f}%",

I would like this to be better documented or an hyperlink to where I could learn how to use that :>3.0f, I am looking for example to ensure the TextColumn text is always a fixed number of char, like 40, with an ellipsis, if it exceed, I was going to do it in Python before passing it to add_task, but I would like that pass the whole string to add_task instead and have it adjust the text output based on the "progress"  TextColumn format.

**Comment by willmcgugan** [comment]
We should link to the Python docs in that section.

**Comment by willmcgugan** [comment]
Fixed with https://github.com/Textualize/rich/pull/2761
