### ISSUE TITLE
[REQUEST] Auto-Refreshing should be done in a separate thread.

### ISSUE THREAD

**Issue by hpe-ykoehler** [Textualize/rich#2587]
I do not know the internal design of the progress bar, but I would like for the auto-refresh to occur independently of the CPU being used.  I have a task that is taking some CPU and I can see the display refreshing being slower, then faster, etc.

Using a high-priority thread (or configurable priority when creating Progress) and moving the auto-refresh to its own thread would allow for a refresh to occur at a constant speed which would be more pleasing to the eye.

**Comment by willmcgugan** [comment]
Auto refresh already happens in a thread. Python threads don't support priorities, but even so I doubt this is the cause of the behaviour you are seeing. You might want to post some example code, and I could suggest improvements.

**Comment by hpe-ykoehler** [comment]
ok, so that could be because I am saturating all cores.  Arg, that is quite a limitation in such a case.  Seems to be related to Python global lock and such.
