### ISSUE TITLE
[REQUEST] provide a means to return a read-only copy of tasks given a task id.

### ISSUE THREAD

**Issue by hpe-ykoehler** [Textualize/rich#2588]
The progress class as a function "tasks" but this one return a new list which breaks the usage of task_id.

For example, if I create add_task twice, I get task_id 0 & 1, then I call remove_task (0) and call update(1) it works, but if I do progress.tasks[1] it fails.

This is because the .tasks returns a new list where the task id 1 is not at position 0.

For performance reason, progress should get a new function such as get_task() or just task() which given a task_id return a copy of the task data for the given task_id.

**Comment by willmcgugan** [comment]
You have made an incorrect assumption about `tasks`. You can't assume anything about the order.

Your request doesn't make a great deal of sense in context. Suggest you explain what you are trying to accomplish. You might also want to read this article.

https://en.wikipedia.org/wiki/XY_problem

**Comment by hpe-ykoehler** [comment]
When a task of mine ends, I want to preserve some information such as the elapsed time.  For that, I need to access the task structure within the progress object.  I preserve the task_id as returned by add_task and using that I am trying to get the task object associated with it.  Within progress, the tasks are kept in a dictionary, meaning that adding tasks[1] will always remain at index 1, but progress.tasks return a list, meaning that the task order is unpredictable.  This required the application to then do a list lookup to find the correct task.

This list lookup is unnecessary, if the progress class would have a function such as def get_task(task_id) it could then retrieve the class from the dictionary faster and my app would not have to do a list search.
