### ISSUE TITLE
[BUG] string that contains : gets rendered with colors even after usage of escape()

### ISSUE THREAD

**Issue by hpe-ykoehler** [Textualize/rich#2589]
```
$ cat test.py

from rich import print
from rich.markup import escape

description = "ABC:def/efg:ggg 0:00:23"
print(f"{escape(description)}")
```

gets rendered with colors:

![image](https://user-images.githubusercontent.com/106683569/196245305-a649bfd8-9210-49b3-98fa-a0e88643e627.png)

I am guessing that this is something I am missing, I am using escape() but apparently that is not enough.

If I use the python print command, there are no colors emitted.

Not a Python expert, either, seeking help on this.

**Comment by willmcgugan** [comment]
See the docs on highlighting…

https://rich.readthedocs.io/en/stable/highlighting.html

**Comment by hpe-ykoehler** [comment]
Thanks
