### ISSUE TITLE
Perform a review the Rich docs

### ISSUE THREAD

**Issue by davep** [Textualize/rich#2599]
Proofread and update *all* of the Rich docs -- glancing at them I've noticed a few typos and things that need updating (OSX when it's macOS, sort of thing); so might be time for a fresh-eyes read/tidy.

See also #2584

- [ ] docs/source/prompt.rst
- [ ] docs/source/group.rst
- [ ] docs/source/index.rst
- [ ] docs/source/appendix/colors.rst
- [ ] docs/source/appendix/box.rst
- [ ] docs/source/pretty.rst
- [ ] docs/source/syntax.rst
- [ ] docs/source/markdown.rst
- [ ] docs/source/progress.rst
- [ ] docs/source/protocol.rst
- [ ] docs/source/reference.rst
- [ ] docs/source/padding.rst
- [ ] docs/source/columns.rst
- [ ] docs/source/markup.rst
- [ ] docs/source/traceback.rst
- [ ] docs/source/panel.rst
- [ ] docs/source/tree.rst
- [ ] docs/source/tables.rst
- [ ] docs/source/highlighting.rst
- [ ] docs/source/layout.rst
- [ ] docs/source/appendix.rst
- [x] docs/source/console.rst
- [ ] docs/source/logging.rst
- [ ] docs/source/style.rst
- [ ] docs/source/text.rst
- [x] docs/source/introduction.rst
- [ ] docs/source/live.rst
- [ ] docs/source/reference/prompt.rst
- [ ] docs/source/reference/emoji.rst
- [ ] docs/source/reference/json.rst
- [ ] docs/source/reference/rule.rst
- [ ] docs/source/reference/pretty.rst
- [ ] docs/source/reference/syntax.rst
- [ ] docs/source/reference/init.rst
- [ ] docs/source/reference/segment.rst
- [ ] docs/source/reference/markdown.rst
- [ ] docs/source/reference/progress.rst
- [ ] docs/source/reference/protocol.rst
- [ ] docs/source/reference/padding.rst
- [ ] docs/source/reference/styled.rst
- [ ] docs/source/reference/columns.rst
- [ ] docs/source/reference/abc.rst
- [ ] docs/source/reference/markup.rst
- [ ] docs/source/reference/traceback.rst
- [ ] docs/source/reference/align.rst
- [ ] docs/source/reference/theme.rst
- [ ] docs/source/reference/color.rst
- [ ] docs/source/reference/panel.rst
- [ ] docs/source/reference/tree.rst
- [ ] docs/source/reference/layout.rst
- [ ] docs/source/reference/progress_bar.rst
- [ ] docs/source/reference/console.rst
- [ ] docs/source/reference/status.rst
- [ ] docs/source/reference/bar.rst
- [ ] docs/source/reference/table.rst
- [ ] docs/source/reference/logging.rst
- [ ] docs/source/reference/style.rst
- [ ] docs/source/reference/text.rst
- [ ] docs/source/reference/live.rst
- [ ] docs/source/reference/highlighter.rst
- [ ] docs/source/reference/measure.rst
- [ ] docs/source/reference/spinner.rst

**Comment by wom** [comment]
https://rich.readthedocs.io/en/stable/reference/spinner.html 
docs/source/reference/spinner.rst
being empty as an example.

**Comment by rodrigogiraoserrao** [comment]
> https://rich.readthedocs.io/en/stable/reference/spinner.html docs/source/reference/spinner.rst being empty as an example.

This will be fixed with #2669
