### ISSUE TITLE
No default function for pretty Nested tables

### ISSUE THREAD

**Issue by Marin-Kitagawa** [Textualize/rich#2602]
**Describe the bug**

I want to have nested columns. But docs doesn't clearly specify how to have this feature.

![image](https://user-images.githubusercontent.com/49131888/197017017-a3fe48ce-5a7e-4d45-96a6-f417c7a38848.png)

It must be like this. I just started using rich and I referred to documentation a lot. But couldn't find a solution

Here A and B are top-level headers. C and D are sub-headers within A and E and F are sub-headers within B

This table is populated dynamically. So, markdown is not an option

If I use the following code. I get an ugly output
```python3
from rich.console import Console, Group
from rich.columns import Columns
from rich.panel import Panel
from rich.table import Table, Column


table = Table(title="Nested")
table.add_column("A")
table.add_column("B")
st = Table()
st.add_column("C")
st.add_column("D")
tt = Table()
tt.add_column("E")
tt.add_column("F")
table.add_row(st, tt)
console = Console()
console. Print(table)
```

![image](https://user-images.githubusercontent.com/49131888/197021549-d78dcb3b-be69-4054-8616-9c96d7b7f6da.png)

**Comment by willmcgugan** [comment]
This feature is called "colspan", which isn't currently supported. It might be in the future.
