### ISSUE TITLE
[BUG] rich.spinner example doesn't work as expected on Windows Terminal

### ISSUE THREAD

**Issue by erdurano** [Textualize/rich#2624]
**Describe the bug**

Spinner example creates visual artifacts due to newline errors and screen clearing issue on the terminal area. 

![image](https://user-images.githubusercontent.com/57545226/199176669-c6ed3f72-79d7-4a05-885e-43587c66d6d1.png)

**Platform**
<details>
<summary>Click to expand</summary>

Example ran with ```python -m rich.spinner``` command on Windows Terminal

![image](https://user-images.githubusercontent.com/57545226/199177279-257dec09-0efd-4c7c-930d-fc1d51e0628d.png)
![image](https://user-images.githubusercontent.com/57545226/199177335-50fe0c8b-8a5a-4eb1-85e9-a744988adb68.png)

</details>

**Comment by willmcgugan** [comment]
I'm afraid some terminals don't handle emoji's very well. Please search closed issues for an explanation.

**Comment by erdurano** [comment]
Yes, upon further inspection, I also derived the conclusion of issue is rooting from Windows Terminal's rendering of unicode emoji. I will post an issue under that repo also. But if you are interested, I can elaborate on my findings so it may be circumvented, perhaps.
