### ISSUE TITLE
A suspicious typing error in pretty.py

### ISSUE THREAD

**Issue by ksun212** [Textualize/rich#2625]
Hello, the dataclass "Node"  inside pretty.py has a field "key_separator" untyped, which makes this field actually a class attribute. I think this is uncommon for a dataclass. Is this field deliberately kept untyped, or simply a coding error? 

Thanks in advance!

**Comment by willmcgugan** [comment]
It probably should be typed. Although coincedantaly it has still having the desired effect. Would you like to PR?

**Comment by ksun212** [comment]
> It probably should be typed. Although coincedantaly it has still having the desired effect. Would you like to PR?

Sure, I created a PR.
