### ISSUE TITLE
Allow Custom Terminator for RichHandler [REQUEST]

### ISSUE THREAD

**Issue by felixy12** [Textualize/rich#2633]
Currently, the `RichHandler` emits through `self.console.print(log_renderable)`. 
By default, the `console.print` function ends the string with `"\n"`, and this is not modifiable through the handler from the user end.

In contrast, native python logging handlers use the `handler.terminator` property to determine how to end the string. By default, this property is `"\n"`, but can be modified directly to change the behavior of the handler. (see [here](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler.terminator) for documentation).

I'd like to request the same feature for the RichHandler, with the console print line to be changed to `self.console.print(log_renderable, end=self.terminator)`. This will give feature parity with the native logger in this regard, while not changing the default behavior of the RichHandler.

Example of current behavior, where I change the terminator to `""` instead of `"\n"`:
```
import logging
from rich.logging import RichHandler

logging.basicConfig()

native_logger = logging.getLogger("native")
native_logger.setLevel(logging.INFO)
native_logger.addHandler(logging.StreamHandler())
native_logger.propagate = False

rich_logger = logging.getLogger("rich")
rich_logger.setLevel(logging.INFO)
rich_logger.addHandler(RichHandler(show_time=False, show_path=False))
rich_logger.propagate = False

def main():
    for name, logger in zip(["Standard", "Rich"], [native_logger, rich_logger]):
        print(f"Using {name} logger")
        print("Pre-terminator change")
        logger.info("blah1")
        logger.info("blah2")

        for handler in logger.handlers:
            handler.terminator = ""
        print("Post-terminator change")
        logger.info("blah1")
        logger.info("blah2")
        print()
        print()

if __name__ == "__main__":
    main()
```

Output:
```
Using Standard logger
Pre-terminator change
blah1
blah2
Post-terminator change
blah1blah2

Using Rich logger
Pre-terminator change
INFO     blah1
INFO     blah2
Post-terminator change
INFO     blah1
INFO     blah2
```
As you can see, for the default handler, the newline character is no longer appended after the terminator changes, while nothing happens for the rich handler.

**Comment by willmcgugan** [comment]
Why do you need this?

**Comment by felixy12** [comment]
To get into the thick of it, I'd like to pipe `stdout` outputs from Keras model fitting over to my logger object through `contextlib.redirect_stdout`. I've explored multiple options on how to get the outputs to go through the logger, and this was the most straightforward way.

This Keras model fitting outputs a progress bar which I would like to keep. I do not have access to the 3rd party package code to modify these progress bars. Since these bars are designed such that they end with `"\r"`, the redirect currently puts each progress bar update on a new line because Rich automatically adds a `"\n"` to it. By changing the terminator to "", I'd be able to avoid this.

**Comment by willmcgugan** [comment]
Not 100% certain I follow, but if you are trying to integrate a progress bar with carriage returns its going to break, regardless if you use new lines or not.

Can you post some code so I can understand what you are implementing?

**Comment by felixy12** [comment]
Sure! Apologies for the long code block, but this is runnable on your own machine if you have Keras installed.
```
import numpy as np
import logging
from contextlib import redirect_stdout

from rich.logging import RichHandler
from rich.console import Console
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Loggers copied over from previous sample
logging.basicConfig()

native_logger = logging.getLogger("native")
native_logger.setLevel(logging.INFO)
native_logger.addHandler(logging.StreamHandler())
native_logger.propagate = False

rich_logger = logging.getLogger("rich")
rich_logger.setLevel(logging.INFO)
rich_logger.addHandler(RichHandler(show_time=False, show_path=False, console=Console(stderr=True)))
rich_logger.propagate = False

logger = native_logger

# Generate some dummy data
num_samples = 1000
num_features = 10
X = np.random.random((num_samples, num_features))
Y = np.random.random((num_samples,))

# Set up simple model
model = Sequential()
model.add(Dense(1, input_shape=(num_features,), activation='relu'))
model.compile(loss='mse', optimizer='adam')

# Set up stdout redirect to logger and fit model
for handler in logger.handlers:
    handler.terminator = ""
logger.write = lambda msg: logger.info(msg) # Hacky, better way is to have a wrapper class around logger
logger.flush = lambda: None
with redirect_stdout(logger):
    model.fit(X, Y, epochs=1, batch_size=10)
# Reset terminators back to original values
for handler in logger.handlers:
    handler.terminator = "\n"
```

The relevant part is the last section: I'm redirecting the `keras.model.fit` outputs to the logger, which has either a native handler or rich handler, with the terminator of the handler set to `""`. When the handler is the native handler (set with `logger = native_logger`, this is the output:
```
100/100 [==============================] - 1s 1ms/step - loss: 0.2008
```
where the progress bar overwrites itself properly with carriage returns.
When `logger = rich_logger`, the output is instead:
```
INFO       1/100 [..............................] - ETA: 1:12 - loss: 0.4154
INFO      40/100 [===========>..................] - ETA: 0s - loss: 0.3213
INFO      83/100 [=======================>......] - ETA: 0s - loss: 0.3241
INFO     100/100 [==============================] - 1s 1ms/step - loss: 0.3247
```
where the progress bar does not overwrite itself (I think intermediate steps are lost because this dummy example runs through the iterations too quickly, and Keras doesn't print out all steps in the bar in that case).

**Comment by maharshi95** [comment]
I believe I tumbled across a similar issue too.

I am trying to rich_print a log file that has tqdm progress bar logs. I tried to replace all the `'\n'` after the tqdm logline with `'\r'`. However, `rich_print` seems to strip away all the control characters. Is there any way to conditionally disable this for a one-off rich_print invokation ?

**Comment by felixy12** [comment]
@maharshi95, when you say you tried replacing all `\n` with `\r`, did that include passing in `end=\r` to `rich.print`? https://rich.readthedocs.io/en/stable/reference/init.html?highlight=print#rich.print

**Comment by willmcgugan** [comment]
I can't seem to run that due to no tensorflow for macOS.

Changing the separator for the RichHandler isn't going to help you though. You may be able to parse the output, and use a Rich progress bar.

**Comment by felixy12** [comment]
Sounds good, I'll find an alternative solution. Thanks for your time!
