### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by imadjamil** [Textualize/rich#2637]
**Describe the bug**

I noticed an issue when using f string while printing an array cotaining bytes, reproducable as shown below. Nothing is printed when using f string.

```
imad@ubuntu64: ..udp (master *) I python
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> b = [b'\xfe\x80\x00\x00\x00\x00\x00\x00', 64]

>>> print(b)
[b'\xfe\x80\x00\x00\x00\x00\x00\x00', 64]
>>> print(f"{b}")
[b'\xfe\x80\x00\x00\x00\x00\x00\x00', 64]

>>> from rich import print
>>> print(b)
[b'\xfe\x80\x00\x00\x00\x00\x00\x00', 64]
>>> print(f"{b}")

>>> print(b)
[b'\xfe\x80\x00\x00\x00\x00\x00\x00', 64]
>>>
```

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
```
imad@ubuntu64: ..udp (master *) I uname -a
Linux ubuntu64 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

imad@ubuntu64: ..udp (master *) I python -m rich.diagnose
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=252 ColorSystem.EIGHT_BIT>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = '256'                                                         │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 67                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=252, height=67),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=252,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=67,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=252, height=67)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 252                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────── Environment Variables ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮        │ {'TERM': 'screen-256color', 'COLORTERM': None, 'CLICOLOR': None, 'NO_COLOR': None, 'TERM_PROGRAM': None, 'COLUMNS': None, 'LINES': None, 'JUPYTER_COLUMNS': None, 'JUPYTER_LINES': None, 'JPY_PARENT_PID': None, 'VSCODE_VERBOSE_LOGGING': None} │        ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯        platform="Linux"

imad@ubuntu64: ..udp (master *) I pip freeze | grep rich
rich==12.5.1
rich-cli==1.6.1
rich-click==1.2.1
rich-rst==1.1.7
```

</details>

**Comment by willmcgugan** [comment]
Your string or being interpreted as Console markup. See the docs for how to escape or disable markup. https://rich.readthedocs.io/en/stable/markup.html

**Comment by imadjamil** [comment]
Shame on me, I should have read more of the docs instead of raising this, sorry.
