### ISSUE TITLE
[DOC] recommendation of creating own console objects as globals creates confusion for pytest integration

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [Textualize/rich#2639]
the documentation currently recommends to create own rich console objects per application

this creates a point of contention for integrating with pytest stdio capture (pytest replaces sys.stdout/err for each test/test phase)

while its a big help that a console object itself ensures late binding of those globals (thus passing over pytests changed ones when sensible)
its creating points of contention on what console objets to use for testing an applciation and/or when to use them

additionally any console object created with explicit fd passover will not partake in late binding, thus break in combination with stdio capture of pytest

i would consider the following points helpful

1. a decorator/contextmanger to ensure a "console context" for an application in a controlled manner that allows testrunner overrides (very nice if one wants toseed a different console into a click appliation)
2. ensuring the documentation is very clear on better using the boolean flag for stderr/out switching for the late binding
3. potentially retireing the recommendation for global console objects

**Comment by willmcgugan** [comment]
Hi Ronny,

You seem to be under the impression I know what issues you have been dealing with. But you haven't told me what those are. Thus I can't properly evaluate those suggestions.

Rich isn't descriptive about how you test. I generally advise people *not* to test the output, which can change according to the platform / environment. Better to check what you print, and not what gets written to stdout.

Rich also doesn't have much control over how an app choses to use Consoles. Which makes it very difficult to provide a one size fits all solution.

If this answer isn't satisfactory, let me know what issues you run up against. Post some code. Explain how / what you are testing and what you felt was deficient. I will try to offer suggestions, and I'm open to updating the docs to help future devs.

Will

**Comment by RonnyPfannschmidt** [comment]
I have a rough idea of our perspective issues, itll take a while to manifest it in a more concrete manner

As what you just outlined gave me an additional perspective that I did not consider well enough before
