### ISSUE TITLE
[BUG] rich.print("[bright_blue uu]" + message) crashes with NotImplementedError

### ISSUE THREAD

**Issue by eblis** [Textualize/rich#2645]
**Describe the bug**

I'm trying to do a print statement on Windows environment using `rich` and I get an exception.
```python
rich.print("[bright_blue uu]" + message)
```

Provide a minimal code example that demonstrates the issue if you can. If the issue is visual in nature, consider posting a screenshot.

Windows 10 x64
Faust streaming application.
I'm using the terminal emulated by PyCharm.

From what I can tell the error is in console.py, around here:
```python
                            try:
                                use_legacy_windows_render = (
                                    self.file.fileno() in _STD_STREAMS_OUTPUT
                                )
                            except (ValueError, io.UnsupportedOperation):
                                pass
```

![image](https://user-images.githubusercontent.com/540188/201923182-00576526-9c65-48f5-a1b0-36573c4ed6c9.png)

The error doesn't appear in the main application, it appears in a library that uses `rich`.
If I write the same console message from my main application, before the library does it then it works ok.
But if the library wants to write the message it fails with the exception mentioned above.

**Comment by eblis** [comment]
I think the code should also ignore NotImplementedError as well:
```python
                            except (ValueError, io.UnsupportedOperation, NotImplementedError):
                                pass
```

Changing the `console.py` code to this allows the messages to be written to console.

**Comment by willmcgugan** [comment]
That would certainly fix it, although `fileno` should not raise a `NotImplementedError`. You might want to raise this with the library that is supplying the file-like object.

**Comment by eblis** [comment]
In my main application the `self.file` member is initialized to this: 
![image](https://user-images.githubusercontent.com/540188/201923960-f7a13f5e-45bd-4a8a-b74d-f329fce48181.png)

But later, in my library, it's (re?)initialized to this:
![image](https://user-images.githubusercontent.com/540188/201924384-49cd642e-099b-4ab1-b1e1-ad44c48654d8.png)

I didn't initialize it to this value, it was probably Faust (or I don't know who) who modified the file object.
I'm initializing a rich console like this:
```python
        self.rich_console = rich.console.Console(color_system="256", force_terminal=True, file=None, quiet=quiet)
```

And then writing the message like so:
```python
self.rich_console.print("[bright_blue uu]" + message)
```
