### ISSUE TITLE
[BUG] `RichHandler(show_path=False)` emits trailing whitespace up to terminal width

### ISSUE THREAD

**Issue by OddBloke** [Textualize/rich#2647]
**Describe the bug**

When `show_path=False` is passed to `RichHandler`, it does not need to emit any content beyond the end of the log message, but it still pads out the content with spaces up to the console's width. This (a) makes it annoying to copy/paste as an end user, (b) means that resizing ones terminal/font size results in "blank" whitespace-only lines appearing in already-emitted log output, and (c) means that setting an explicitly high console width to avoid wrapping (which our CLI's integration tests do) results in huge amounts of whitespace in the output.

With the below script and `sed`, we can demonstrate this:

```
$ python reproducer.py | sed 's/ /_/g'
2022-11-15_10:33:11_INFO_____Logging_initialised_____________________________________________________________________________________________________________________________
```

```py
import logging

from rich.logging import RichHandler


def init_logging() -> logging.Logger:
    handler = RichHandler(show_path=False)

    logging.basicConfig(
        datefmt="%Y-%m-%d %H:%M:%S",
        format="%(message)s",
        handlers=[handler],
        level=logging.INFO,
    )
    logging.info("Logging initialised")


init_logging()
```

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

Ubuntu 20.04, GNOME Terminal

```
$ python -m rich.diagnose
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=173 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 43                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=173, height=43),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=173,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=43,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=173, height=43)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 173                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
```

```
$ pip freeze | grep rich
rich==12.6.0
```
</details>

**Comment by OddBloke** [comment]
This diff fixes my problem:

```diff
--- a/rich/_log_render.py
+++ b/rich/_log_render.py
@@ -44,13 +44,15 @@ class LogRender:
         from .table import Table
 
         output = Table.grid(padding=(0, 1))
-        output.expand = True
+        output.expand = False
         if self.show_time:
             output.add_column(style="log.time")
         if self.show_level:
             output.add_column(style="log.level", width=self.level_width)
         output.add_column(ratio=1, style="log.message", overflow="fold")
         if self.show_path and path:
+            # Set expand=True so the path cell is right-aligned
+            output.expand = True
             output.add_column(style="log.path")
         row: List["RenderableType"] = []
         if self.show_time:
```

But it causes tests to fail. Specifically, `test_justify`: with `.expand = False`, the width in which it right-justifies is the width of the text, instead of the width of the console as before:

```py
    def test_justify():
        console = Console(width=20, log_path=False, log_time=False, color_system=None)
        console.begin_capture()
        console.log("foo", justify="right")
        result = console.end_capture()
>       assert result == "                 foo\n"
E       AssertionError: assert 'foo\n' == '                 foo\n'
E         -                  foo
E         + foo
```

I couldn't figure out a way to expand the table in this case, as the right-justification is specified within the `renderables` we get passed. (Given that, we could presumably be passed other objects which would right-justify somehow: we'd have to handle all of those for this approach to work, I think.)

For now, I'm working around this issue by passing an instance of this `Console` subclass to `RichHandler`:

```py
class WhitespaceStrippingConsole(Console):
    def _render_buffer(self, *args, **kwargs):
        rendered = super()._render_buffer(*args, **kwargs)
        newline_char = "\n" if rendered[-1] == "\n" else ""
        return "\n".join(line.rstrip() for line in rendered.splitlines()) + newline_char
```

**Comment by willmcgugan** [comment]
RichHandler is designed with one goal in mind: to look nice in the terminal.

If you don't want the path. And you want it to soft wrap. Then you don't want RichHandler. Best roll your own logging handler using just the features you want.

**Comment by OddBloke** [comment]
> RichHandler is designed with one goal in mind: to look nice in the terminal.
> 
> If you don't want the path. And you want it to soft wrap. Then you don't want RichHandler. Best roll your own logging handler using just the features you want.

Hi @willmcgugan, I'm a little confused by this response. `RichHandler` explicitly has support for excluding the path with `show_path=False`. I'm reporting that using this documented option means that log output does _not_ "look nice in the terminal" if that terminal is resized to be smaller (e.g. by increasing its font size) after the log lines are emitted: the trailing whitespace causes _every_ line to wrap.

For avoidance of doubt, here is the same log output before and after incrementing my terminal's font size:

![before-resize](https://user-images.githubusercontent.com/62736/205347072-0383c60c-071c-4160-91b0-bff2fe4f3181.png)
![after-resize](https://user-images.githubusercontent.com/62736/205347070-8cd532e8-5846-474d-a562-8f760ff56970.png)

(It sounds like passing `Console(..., soft_wrap=True)` might be the solution for (c) our CI output issues: thanks for the pointer!)

**Comment by OddBloke** [comment]
> (It sounds like passing `Console(..., soft_wrap=True)` might be the solution for (c) our CI output issues: thanks for the pointer!)

(For posterity, my suspicion was incorrect: the `Table` used by `LogRender` to lay out the output is what performs the wrapping. The `Console` is only asked to `print()` segments which have already been wrapped to console-width, so its wrapping configuration is immaterial. FAOD, this is orthogonal to this issue: even if I _could_ configure soft-wrapping for this case, I _want_ wrapping when emitting to user's terminals, which would therefore still have the trailing whitespace reported in this issue.)

**Comment by edemattos** [comment]
I am also experiencing the same issue. There is no reason for trailing spaces to be printed when nothing is being right-aligned, i.e. when `RichLogger(show_paths=False)`. @willmcgugan

**Comment by hugo-syn** [comment]
I'm experiencing the same issue, are you planing to fix this ? :)

**Comment by ITProKyle** [comment]
I also ran into this **bug** when transitioning a CLI to use rich. in the integration tests I inspect what is being output to stderr/stdout and found a bunch of white space being added to the end of each line. a fix for this would be greatly appreciated.

**Comment by jzenoz** [comment]
Also would be useful for GitLab CI usage as show_path needs to be disabled for that: https://github.com/Textualize/rich/issues/2551

**Comment by mrfroggg** [comment]
I have the same issue with Syntax()
I print YAML from teh data I receive from an API, the user can redirect it to a file to use as a template, put it's padded with trailling white space.
Wish there was an argument to suppress trailling whitespace

**Comment by AndydeCleyre** [comment]
I'm using rich to syntax-highlight print some configuration format content to the terminal. 

To some of those formats, trailing white space on the line is semantically different data, so it becomes inaccurate. 

This isn't a log, I'm not using `RichHandler` explicitly, just `Console` and `Syntax`. The `Syntax` docstring includes:

> padding (PaddingDimensions): Padding to apply around the syntax. Defaults to 0 (no padding).

So to add padding is a surprise. Maybe that's happening in `Console.print`, but I don't think it's documented.

This is also a problem with rich-cli, at least when using `--theme native`.
