### ISSUE TITLE
[BUG] list of string, lowercase started string in `[]` is discarded by `escape()`

### ISSUE THREAD

**Issue by copdips** [Textualize/rich#2670]
You may find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) or [issues](https://github.com/textualize/rich/issues).

**Describe the bug**

`[b]` and `[c]` are started by lowercase, which are discarded, whereas `[A]`, and `[B]` are well displayed.

```python
ipdb> from rich import print as rich_print
ipdb> from rich.markup import escape
ipdb> names = ["[A]", "[B][b]", "[c]"]

ipdb> rich_print(f"{[escape(n) for n in names]}")
['[A]', '[B]\', '\']

ipdb> rich_print(escape(f"{[escape(n) for n in names]}"))
['[A]', '[B]\\[b]', '\\[c]']
ipdb> 
```

Workaround by using `join()` in advance:

```python
ipdb> from rich import print as rich_print
ipdb> from rich.markup import escape
ipdb> names = ["[A]", "[B][b]", "[c]"]

ipdb> rich_print(f"{','.join([escape(n) for n in names])}")
[A],[B][b],[c]
```

**Platform**
 ubuntu 2004, python3.8, rich 12.6.0

**Comment by willmcgugan** [comment]
You only need to escape the string once, at the end.

```python
print(escape(','.join(names)))
```

If you print the list directly, you won't need any escaping.

```python
 print(names)
```
