### ISSUE TITLE
tqdm and rich library conflict

### ISSUE THREAD

**Issue by d139093** [Textualize/rich#2671]
I'm using both tqdm and rich libraries for my program. Rich for quickly adding colors to text, amongst other things, and tqdm for its simplistic progress bar. I have found that when I import tqdm along with  rich, the colors start to act funny. The first 16 colors from the standard colors work fine. The issue arises when I start calling other colors and styles. I trimmed some of the rich __main__.py code to show what I'm talking about. 

You can also see what I'm talking about in the images that I uploaded. One has from tqdm import tqdm commented out, and the other does not. The text file contains the __main_.py code. 

![tqdm_rich](https://user-images.githubusercontent.com/42370378/204077742-be3afea6-acb3-47c7-9513-102022dee1ce.PNG)

[rich_tqdm_issue.txt](https://github.com/Textualize/rich/files/10095854/rich_tqdm_issue.txt)

**Comment by willmcgugan** [comment]
I'm assuming you are running this on Windows?

tqdm may be using the `colorama` module which makes some global changes to stdout, and only supports 16 colors. There's not much that can Rich can do about that.

**Comment by d139093** [comment]
Thank you for getting back and clarifying for me. I ended up using Rich for my project instead of tqdm.
