### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by zdog234** [Textualize/rich#2672]
**Consider posting in https://github.com/textualize/rich/discussions for feedback before raising a feature request.**

**Have you checked the issues for a similar suggestions?**

[Yup](https://github.com/Textualize/rich/issues?q=is%3Aissue+vi)

**How would you improve Rich?**

**Give as much detail as you can. Example code of how you would like it to work would help.**

It'd be really cool to have a `keybindings: Literal["emacs", "vi"] = "emacs"` kwarg in `Console.input`, allowing developers to enable some subset of vi keyboard shortcuts. (obviously `hjkl`, but should probably also include `$`, `0`, `b`, `e`, `w`, `d`, and `c`)

It'd also probably make sense to have selection, yanking and pasting. It'd be nice for the details of the register to be hidden from the developer unless they want to interface with it directly (something like a `console.register_contents` property?).

One difficult design question that I don't have a great answer for (although maybe some half-baked ideas):

1. How do we indicate to the user that they're in insert vs normal mode? (I'm not sure if the actual `vi` does this, although it is really helpful when an app does).
    1. This *could* be done in a low-effort way by prepending hardcoded status info to the `prompt`, but it'd obviously be nice to allow developers to customize / disable this behavior

**What problem does it solve for you?**

As a *user* of a lot of cli apps, I usually enable vi keybindings whenever possible. If it's easier for developers to offer, then more apps will offer them and my life will be easier.

That being said, an alternative option for an app to offer is to open`$EDITOR` (this is the approach that the `gh` cli takes). This works pretty well if `$EDITOR` is fast, but it'll never be as fast as offering native keybinding support

**Comment by willmcgugan** [comment]
Console.input is a relative thin layer around the builtin `input`. I'm afraid that means we are unlikely to implement anything that Python itself doesn't do.
