### ISSUE TITLE
[BUG]console.print give different results when directing to a file

### ISSUE THREAD

**Issue by chunyang-wen** [Textualize/rich#2673]
**Describe the bug**

In the part of document: https://github.com/Textualize/rich#rich-library, rich can highlight code. It works perfect in the terminal.
But when I try to redirect the output to a file, it adds strange empty spaces and empty lines to the output.

output in the terminal:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/2911134/204367995-9ec8bcf8-9d5e-4783-a2e7-d0219e5609b3.png">

output when directing the output to a file
<img width="897" alt="image" src="https://user-images.githubusercontent.com/2911134/204368144-f9d9916a-55fb-4019-92d7-044c7c7f43a9.png">

after cleaning the empty spaces and additional lines:

**This is the expected result**

<img width="777" alt="image" src="https://user-images.githubusercontent.com/2911134/204368632-ce841601-50a9-4b79-9f72-8a15b2a3108c.png">

**Platform**

Macos M1max 16

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

<img width="718" alt="image" src="https://user-images.githubusercontent.com/2911134/204368425-d87128f0-53ca-47da-8bd6-3a84d3bd081d.png">

<img width="507" alt="image" src="https://user-images.githubusercontent.com/2911134/204368445-948733a5-1865-4e52-95ca-4db8f04f485a.png">

rich==12.6.0

**Comment by willmcgugan** [comment]
What output are you expecting? Rich will remove escape sequences from the output when you redirect to a file, because only the terminal can render them.

**Comment by chunyang-wen** [comment]
Well, the removal does not happen. The expected result is with additional spaces or new lines removed.

**Comment by willmcgugan** [comment]
If you want escape sequences for colour you can set the env var FORCE_COLOR. In all other respects the output when will be *exactly* the same as it would be when printed.

If you want to output something different when redirecting you can manage that programmatically.
