### ISSUE TITLE
[BUG] Cannot log Tree() output to file

### ISSUE THREAD

**Issue by JoeZiminski** [Textualize/rich#2704]
[Now solved in comment]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

I would like to print the output of the [Tree()](https://rich.readthedocs.io/en/stable/tree.html) class to a log file. The Tree outputs well with print() but the logged version is  just a string representation of the class. Maybe I have mis-understood the docs.

MRE:

This uses the [Rich example tree.py](https://github.com/Textualize/rich/blob/master/examples/tree.py)

```
from tree import walk_directory
from rich import print

import logging
from rich.logging import RichHandler
from logging import FileHandler


def get_rich_directory_tree(directory):
    tree_ = Tree(label="test")
    walk_directory(pathlib.Path(directory), tree_)
    return tree_


path_ = r"\path\to\log.log"

FORMAT = "%(message)s"
logging.basicConfig(
    level="NOTSET", format=FORMAT, datefmt="[%X]", handlers=[RichHandler(), FileHandler(path_)],
)

log = logging.getLogger("rich")

tree_ = get_rich_directory_tree(r"path\to\folder")

print(tree_)
log.info(tree_)
```

stdout using print()
```
└── rawdata
    ├── sub-001
    │   ├── ses-001
    │   │   └── behav
    │   │       └── .meta
    │   └── ses-002
    │       └── behav
    │           ├── .meta
    │           └── test_file.txt (0 bytes)
```

log file:
```
<rich.tree.Tree object at 0x000002F025701310>
```
on

Windows 10, pycharm 2022.3, python 3.10>

thanks!

**Comment by JoeZiminski** [comment]
As usual, understand the problem almost immediately after posting an issue 🤦‍♂️ My solution below, please let me know if this is not optimal. Happy to close, but can I confirm, is there a way to automatically pip RichHandler() for a file?

```
import rich
from datashuttle._vendored.rich import tree
from rich import print
from rich import get_console

import logging
from rich.logging import RichHandler
from logging import FileHandler

path_ = r"\path\to\log.log"

FORMAT = "%(message)s"
logging.basicConfig(
    level="NOTSET", format=FORMAT, datefmt="[%X]", handlers=[FileHandler(path_, encoding='utf-8')],
)

log = logging.getLogger("rich")

tree_ = get_rich_directory_tree(r"path\to\folder")

console = get_console()
with console.capture() as capture:
    console.print(tree_, markup=True)
log.info(capture.get())
```

**Comment by XingDongZhe** [comment]
I found that `log.info(msg) => logging.Record.getMessage()  => `str(self.msg)`. 

So `msg` should call `__rich_repr__` or other method, then pass to `log.info()`.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/rich/blob/master/FAQ.md#how-do-i-log-a-renderable
