### ISSUE TITLE
[BUG] REPL pretty print RecursionError

### ISSUE THREAD

**Issue by ddelange** [Textualize/rich#2713]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

Hi 👋 When rich tries to prettyprint my custom object, it hits a `RecursionError` (I won't paste the full traceback here 😅). It's easy to reproduce with a vanilla ipython REPL.

I haven't tried with `from rich import print` but it might be affected as well.

The ipython REPL builtin repr also doesn't like my object, but at least doesn't crash hard.

```python
from rich import pretty
pretty.install()

class AttrDict(dict):
    """Dict with key access via attributes."""

    def __missing__(self, key):
        value = self[key] = type(self)()
        return value

    def __getattr__(self, name: str):
        return self[name]

    def __setattr__(self, name: str, value):
        self[name] = value

obj = AttrDict()
obj.a.b.c = 'd'
print(obj.a)
print(obj['x']['y'])
print(obj) # builtin print is fine
repr(obj) # builtin repr is fine
obj['z']  # rich repr RecursionError
```

**Platform**

CPython 3.11.0:
```pytb
# SIGTERM

File ~/.pyenv/versions/3.11.0/envs/vv311/lib/python3.11/site-packages/rich/pretty.py:863, in traverse.<locals>._traverse(obj, root, depth)
    861     iter_items = islice(iter_items, max_length)
    862 for index, (key, child) in enumerate(iter_items):
--> 863     child_node = _traverse(child, depth=depth + 1)
    864     child_node.key_repr = to_repr(key)
    865     child_node.last = index == last_item_index

    [... skipping similar frames: traverse.<locals>._traverse at line 863 (2962 times)]

...
```

CPython 3.8.10:
```pytb
... last 1 frames repeated, from the frame below ...

~/.pyenv/versions/3.8.10/envs/vv/lib/python3.8/site-packages/rich/pretty.py in _traverse(obj, root, depth)
    758                         iter_items = islice(iter_items, max_length)
    759                     for index, (key, child) in enumerate(iter_items):
--> 760                         child_node = _traverse(child, depth=depth + 1)
    761                         child_node.key_repr = to_repr(key)
    762                         child_node.last = index == last_item_index

RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ddelange** [comment]
@willmcgugan I can still reproduce in ipython REPL (cp311):
<img width="386" alt="image" src="https://github.com/user-attachments/assets/12dbb7a8-56cb-43ce-95cf-979abff5e42e">

on latest rich I'm no longer getting a RecursionError, but my RAM is simply filling (3GB now) up and the python process is blasting 100% CPU

**Comment by willmcgugan** [comment]
Have you tried it in main ?

**Comment by ddelange** [comment]
yes, it's also going into eternal recursion on the latest commit:
<img width="563" alt="image" src="https://github.com/user-attachments/assets/9c44c82b-84c7-4073-9459-4963b8960b39">

**Comment by willmcgugan** [comment]
<img width="1233" alt="Screenshot 2024-08-26 at 19 33 30" src="https://github.com/user-attachments/assets/557a3db5-5f5d-476a-98ea-6b1d0803ee5f">

**Comment by ddelange** [comment]
looks like yours is also hanging, I'd expect a rich repr after `Out[1]:`

**Comment by ddelange** [comment]
cell 1:
```py
class AttrDict(dict):
    """Dict with key access via attributes."""

    def __missing__(self, key):
        value = self[key] = type(self)()
        return value

    def __getattr__(self, name: str):
        return self[name]

    def __setattr__(self, name: str, value):
        self[name] = value

obj = AttrDict()
obj.a.b.c = 'd'

obj  # works
```

cell 2:
```py
from rich import pretty
pretty.install()

obj  # hangs
```

**Comment by ddelange** [comment]
how about a short circuit in _traverse if `hasattr(obj, "__missing__")`? any class that implements that magic method will trigger infinite recursion in the current implementation.
