### ISSUE TITLE
Spinners hide sudo user prompt for password

### ISSUE THREAD

**Issue by thisismygitrepo** [Textualize/rich#2718]
My python code wrapped within a rich spinner, calls some shell commands that require elevation, however, the spinner seem to prevent this prompt from writing anything to the console (like enter password) resulting in confusing behaviour.

**Platform**
Linux

```
import os
from rich.console import Console
console = Console()
exe = "path to file"
with console.status("Installing..."):
    os.system("f"sudo mv {exe} /usr/local/bin/")  # <<<<<<<<<<<< SHOULD PROMPT FOR PASSWORD

```

The prompt is hidden by spinner.

**Comment by willmcgugan** [comment]
Both the main process and your `sudo mv` process are writing to the terminal at the same time. There's no way for Rich to detect and handle this, so I'm afraid you will have to avoid spinners when running sub-processes that write directly to the terminal.

**Comment by citosid** [comment]
I have the same issue, with code similar to this:

```python
files = [1,2,3]
with console.status("[bold green]Opening keepass databases...") as status:
    for file in files:
        password = console.input('Password: ', password=True)
```

It hides the prompt for the password

**Comment by thisismygitrepo** [comment]
@willmcgugan Are you saying what's happening is that Spinner is overwriting that prompt? if so, I guess we can close this as there is no way around it.

**Comment by willmcgugan** [comment]
Exactly that.
