### ISSUE TITLE
[REQUEST] Is it possible to print rotating `/`  in rich.progress?

### ISSUE THREAD

**Issue by avatar-lavventura** [Textualize/rich#2760]
For the Progress Display can we have something as follows:

When we install a pip package using `pip install -e .`; it shows a rotating `/` => `|` => `/` => `|` => `\`  … during in installation is in process.

ex:
```python
  Getting requirements to build editable ... done
  Installing backend dependencies ... [ / ] rotates
```

Is it possible to have somehing similiar to print a rotation line `/` in `rich.progress` also at the end of the line instead beginning of it?

**Comment by flamesjames** [comment]
Hello there! I was playing around with this in my free time and came across a cool library called [_halo_](https://pypi.org/project/halo/) that could be used for displaying loading text in your projects.

Here is an example of a rotating '/' in Python:
```from halo import Halo
import time

spinner = Halo(text='Loading', spinner='dots', placement='right')
spinner.start()

# your code here
time.sleep(6) # replace this line (for testing purposes only)

spinner.stop()
```

Notice that you can control the placement of the spinner in relation to the text, along with some other things that can be found checking the `Halo` class.

There are a lot of options for spinners that can be used with this library in case you find a better one. Some examples I gathered are:
`dots, dots2, dots3, dots4, dots5, dots6, dots7, dots8, dots9, dots10, dots11, dots12, line, pipe, simpleDots, simpleDotsScrolling, star, star2, flip, hamburger, growVertical, growHorizontal, balloon, balloon2, noise, bounce, boxBounce, boxBounce2, triangle, arc, circle, squareCorners, circleQuarters, circleHalves, squish, toggle, toggle2, toggle3, toggle4, toggle5, toggle6, toggle7, toggle8, toggle9, toggle10, toggle11, toggle12, toggle13, arrow, arrow2, arrow3, bouncingBar, bouncingBall, smilingFace, smilingFaceWithHearts, rollingEyes, hearts, clock, earth, moon, runner, pong, shark, dqpb, weather, christmas, grenade, point, layer`

Hope this helps! Cheers

**Comment by avatar-lavventura** [comment]
@flamesjames Thanks. I think rich uses `(text='Loading', spinner='dots')` by default. Like `dots` always show up at left.

 I will investigate to change that option in `rich`, do you think is it possible?

**Comment by flamesjames** [comment]
> @flamesjames Thanks. I think rich uses `Halo` under the hood but I am not 100% sure; `Halo(text='...', spinner='dots')` by default. Like `dots` always show up at left, when I use inside rich.
> 
> I will investigate to change that option in `rich`, do you think is it possible?

Sorry, I am new to Github in general. I think I read your initial question wrong...after further investigation of `rich`, it seems they do not actually use the `Halo` library mentioned above. They have declared their own custom Spinner files/animations to call from. 

I see the code that instantiates a Spinner, so I feel there will have to be some minor adjustments to control the positioning of the spinner (before or after the text it's included with)...

Thinking of forking and adding this functionality.

**Comment by avatar-lavventura** [comment]
@flamesjames No your guide was helpful thank you. Following code was what I was looking for. 

```python
#!/usr/bin/env python3

from halo import Halo
import time

with Halo(text="Loading", spinner="line", placement="right"):
    time.sleep(6)  # replace this line (for testing purposes only)

print("Loading")
```
