### ISSUE TITLE
Latex output for Rich tables

### ISSUE THREAD

**Issue by bjourne** [Textualize/rich#2763]
I know this is a little outside the scope of pretty printing in the terminal, but it would be nice if Rich could output simple Latex tables. Nothing fancy, just something to copy-paste into tex files:

```
\begin{tabular}{llc}\toprule
    header1  & header2 & header3 \\\midrule
    cell1 & cell2 & cell3\\
    ....
    \bottomrule
\end{tabular}
```
I've often had the need for this because specifying large Latex tables is tedious. Perhaps the feature could be as simple as `from rich.box import LATEX_TABLE`?

**Comment by willmcgugan** [comment]
I don't think a change to box would work as it makes different assumptions.

I have a feeling this would be better as a third-party package. But I would consider a `"write_latex" method or similar in a PR. I don't know latex, so this wouldn't be something I would attempt.
