### ISSUE TITLE
[BUG] The rich panel does not properly stretch to fit the screen width on OS Windows

### ISSUE THREAD

**Issue by snooppr** [Textualize/rich#2768]
code:
```
import os
from rich.panel import Panel
from rich.console import Console

console = Console()

#determine the width of the terminal
print('width=', os.get_terminal_size()[0])

s1 = "="*(os.get_terminal_size()[0]-4)
s2 = "="*(os.get_terminal_size()[0])

#results
console.print(Panel(s1))
print(s2)
```
The same code gives different results on OS Windows/Linux:

OS Windows 7 👎:
![win cleaned](https://user-images.githubusercontent.com/61022210/213849395-a6ef363e-8ec9-4102-869b-d0c00ab3d51a.png)

OS GNU/Linux 👍:
![lin cleaned](https://user-images.githubusercontent.com/61022210/213848974-26f20518-3e6c-4d87-a751-6f53adad3281.png)

For some reason, panel rich on OS Windows from the right edge, leaves one extra character at the end, does not work correctly (whereas it does not exist on OS GNU / Linux). With this, this place on the right character is printed without problems in the terminal (see image, `print(s2) `gives the same, correct result on all OS).

The problem is that for different OS you have to write different code for filling (unpleasantly): 
s = `"=" * (os.get_terminal_size()[0] - 5)` on Windows
and
s = `"=" * (os.get_terminal_size()[0] - 4)` in Linux

Fix Rich Panel on Windows

rich v13.0.1

**Comment by snooppr** [comment]
UPD.
### The problem affects not only panels, but also tables.

code:
```
from rich.console import Console
from rich.table import Table

console = Console()

table = Table(title="Star Wars Movies", width=80)

table.add_column("Test1", style="green")
table.add_column("Test2", style="magenta")
table.add_row("Dec 20, 2019", "Star Wars: The Rise of Skywalker", "$952,110,690")
console.print(table)
```

results

OS Win:
![win cleaned](https://user-images.githubusercontent.com/61022210/213861378-20536b04-a995-4972-b81a-75c0d11d1019.png)

OS Lin:
![lin cleaned](https://user-images.githubusercontent.com/61022210/213861386-bff47e27-1f48-45d6-8b27-98a469343ff1.png)

**Comment by willmcgugan** [comment]
Rich reduces the width by 1 on legacy Windows, to account for it inserting automatic new lines. The new Windows Terminal does not have this issue.
