### ISSUE TITLE
[REQUEST] Could we make the rainbow python a mascot of this project?

### ISSUE THREAD

**Issue by ygworldr** [Textualize/rich#2780]
**How would you improve Rich?**

The [Rainbow Python](https://reptile.guide/rainbow-python/) not only looks stunning, but is a python. It would make a fun mascot for this project. You can see a [video](https://www.youtube.com/watch?v=-hVJtrXaZho) of one in all its glory.

**What problem does it solve for you?**

None whatsoever. This is just a fun suggestion.

**Comment by willmcgugan** [comment]
That is a purdy snake!
