### ISSUE TITLE
[BUG] Console configuration for RichHandler with logging.config.DictConfig does not work

### ISSUE THREAD

**Issue by quitterie-lcs** [Textualize/rich#2782]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

The [dictConfig](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig) method from logging.config module seems to not accept a console configuration when using the [RichHandler](https://rich.readthedocs.io/en/stable/logging.html).

I want to configure a console to control the color system of the output, however the console configuration does not seem to be supported with a dictionary configuration for the logger. 

Here is an extract of the dict configuration I want to have for a logger named `ralph` and I can't find a proper definition for the console in the handler dictionary configuration.

```
"handlers": {
            "console": {
                "class": "rich.logging.RichHandler",
                "level": "INFO",
                "console": {
                    "class": "rich.console.Console",
                    "color_system": "standard", 
                    "file": "file.txt"
                }
            }
        },
"loggers": {
            "ralph": {
                "handlers": ["console"],
                "level": "INFO",
            }
}
```

When running the traceback is, as followed. 

```
File "/usr/local/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/site-packages/rich/logging.py", line 163, in emit
    if isinstance(self.console.file, NullFile):
AttributeError: 'ConvertingDict' object has no attribute 'file'
```
I can't find documentation about this topic.

What I conclude is that it is required to instantiate a console to get the configuration in the handler. The `RichHandler` seems to be only usable without having a defined console but only with stdout as the default console.

**Comment by willmcgugan** [comment]
I don't think the dict config can nest parameters like that. At least I haven't seen it.

Why do you want to change the color system?

**Comment by quitterie-lcs** [comment]
By default the color system is set to None in the project system, but I don't want to change it globally. 
As far as I understand, `rich` uses the value of the color system of the system.
That's why I want to configure the color system to `standard` with rich

**Comment by willmcgugan** [comment]
If the Console color system is None, then it likely means you aren't running in a terminal. Are you running this on CI? The better solution would be to set the environment variable `FORCE_COLOR=1` and `TERM=xterm-256`.

If you must do this via logging config, you can define a callable in your project which returns a `RichHandler` with your custom Console.

**Comment by quitterie-lcs** [comment]
The second solution you have proposed is what I have tried first, which forced me to suppress the `dictConfig` that was implemented before.

I have set the environment variables `FORCE_COLOR` and `TERM` and it works, thanks ! :tada: 
(A previous attempt of setting the environment variables has been unsuccessful, I miss `FORCE_COLOR`).
