### ISSUE TITLE
from rich import print  python 2 or 3

### ISSUE THREAD

**Issue by Framelony** [Textualize/rich#2790]
is there a way to try except : this import in python2 ? 

import sys
if sys.version_info.major == 3:
    from rich import print as rprint
else:
    print("OK ")
i have always 
SyntaxError: invalid syntax

thanks

**Comment by willmcgugan** [comment]
I don't think that will work on Python2, as `print` is a keyword.

**Comment by Framelony** [comment]
i know that doesnt work but i cant in any way by pass the import and so breaks python2  compatibility 
thanks

**Comment by willmcgugan** [comment]
Add it to another python file then do "from my_print import *"

**Comment by Framelony** [comment]
it works thanks
