### ISSUE TITLE
[BUG] Rich can't be installed in Jupyter Lite

### ISSUE THREAD

**Issue by adtzlr** [Textualize/rich#2809]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Rich can't be installed in Jupyter Lite**

In [JupyterLite](https://jupyter.org/try-jupyter/lab/) `rich` can't be installed (starting with `rich>13.0.0`).

Running `%pip install rich` gives

`ValueError: Requested 'pygments<3.0.0,>=2.14.0', but pygments==2.13.0 is already installed`.

It seems that JupyterLite only ships with `pygments=2.13.0`.

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? Windows 10, MS Edge, Python 3.10 as provided by [JupyterLite](https://jupyter.org/try-jupyter/lab/).

</details>

**Comment by willmcgugan** [comment]
Re-open if not fixed in v13.3.2
