### ISSUE TITLE
[REQUEST] Fill empty space with guiding dots in tables 

### ISSUE THREAD

**Issue by underyx** [Textualize/rich#2826]
**How would you improve Rich?**

Given code like this

```
>>> t = Table(box=box.SIMPLE_HEAD)
>>> t.add_column("Language")
>>> t.add_column("First thing", justify="right")
>>> t.add_column("Second thing", justify="right")
>>> t.add_row("Python", "123", "45")
>>> t.add_row("Go", "14", "78")
>>> t.add_row("TypeScript", "412", "3")
>>> t.add_row("Rust", "4", "771")
>>> c.print(t)
  Language     First thing   Second thing
 ─────────────────────────────────────────
  Python               123             45
  Go                    14             78
  TypeScript           412              3
  Rust                   4            771
```

I'd love to be able to do 

```
>>> t = Table(fill_rows=".", box=box.SIMPLE_HEAD)
>>> # ...
>>> c.print(t)
  Language     First thing   Second thing
 ─────────────────────────────────────────
  Python...............123.............45
  Go....................14.............78
  TypeScript...........412..............3
  Rust...................4............771
```

**What problem does it solve for you?**

This is intended for the output of [Semgrep](https://github.com/returntocorp/semgrep). I'm trying to help people visually track which number belongs to which language, without taking up extra vertical space for rendering horizontal lines between each row. Most of our users run Semgrep in CI without support for color output, so we cannot rely on alternating dimmed styles to help.

**Comment by willmcgugan** [comment]
This is a bit of an esoteric requirement (first time anyone has asked), so I probably wouldn't add it to the core library. However, you could build a renderable that wrapped a Text object and padded it with dots.
