### ISSUE TITLE
[BUG] rich progress bar display problem

### ISSUE THREAD

**Issue by shimbay** [Textualize/rich#2827]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

rich print broken in some terminal, but i don`t know why.

![image](https://user-images.githubusercontent.com/7620259/220907387-7cf8e97a-506e-44a4-ab9e-4b64555ca4fb.png)

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by willmcgugan** [comment]
It's likely an encoding problem. I would be helpful if you could fill in the issue template, or at least let me know on which terminals you are seeing this issue.

**Comment by willmcgugan** [comment]
Closing, assumed stale. Reopen if you can supply the requested info.
