### ISSUE TITLE
[BUG] HTML Report Table Output screwed

### ISSUE THREAD

**Issue by ocervell** [Textualize/rich#2831]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**
The table output in HTML reports is somewhat screwed:
![2023-02-25 20_57_10-Preview workflow_domain_recon_results_2023_02_25-07_43_54_PM html - Untitled (Wo](https://user-images.githubusercontent.com/9629314/221377063-ade054c8-d150-441e-9cb6-ac3c18a4324b.png)

Any idea what causes this ?
Also, is there any plans to support converting rich tables to HTML tables natively ?

**Comment by willmcgugan** [comment]
It is more likely to be a font issue with your browser. I would need to see the HTML to be sure.

I don't intend to add any table HTML generation.

**Comment by willmcgugan** [comment]
Closing. Reopen if you can supply requested info.
