### ISSUE TITLE
terminal left in funky state after using Progress  w/ multiple threads.

### ISSUE THREAD

**Issue by yuffington** [Textualize/rich#2837]
Wrote a script using rich Progress and ThreadPoolExecutor.   It works great!   But, most of the time upon exit, it leaves my terminal in a wonky state (no newlines, no echo), such that I need to do a "reset" command to get it working properly again.

Is there some way to force rich to return my terminal to its regular settings when complete?

I've written some simpler progress bar scripts using "track" that don't exhibit this problem.   

```
python -m rich.diagnose
pip freeze | grep rich
```
╭─────────────────────── <class 'rich.console.Console'> ───────────────────────╮
│ A high level console interface.                                              │
│                                                                              │
│ ╭──────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=80 ColorSystem.TRUECOLOR>                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│     color_system = 'truecolor'                                               │
│         encoding = 'utf-8'                                                   │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w'               │
│                    encoding='utf-8'>                                         │
│           height = 45                                                        │
│    is_alt_screen = False                                                     │
│ is_dumb_terminal = False                                                     │
│   is_interactive = True                                                      │
│       is_jupyter = False                                                     │
│      is_terminal = True                                                      │
│   legacy_windows = False                                                     │
│         no_color = False                                                     │
│          options = ConsoleOptions(                                           │
│                        size=ConsoleDimensions(width=80, height=45),          │
│                        legacy_windows=False,                                 │
│                        min_width=1,                                          │
│                        max_width=80,                                         │
│                        is_terminal=True,                                     │
│                        encoding='utf-8',                                     │
│                        max_height=45,                                        │
│                        justify=None,                                         │
│                        overflow=None,                                        │
│                        no_wrap=False,                                        │
│                        highlight=None,                                       │
│                        markup=None,                                          │
│                        height=None                                           │
│                    )                                                         │
│            quiet = False                                                     │
│           record = False                                                     │
│         safe_box = True                                                      │
│             size = ConsoleDimensions(width=80, height=45)                    │
│        soft_wrap = False                                                     │
│           stderr = False                                                     │
│            style = None                                                      │
│         tab_size = 8                                                         │
│            width = 80                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'iTerm.app',   │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Darwin"

rich==12.6.0
rich-cli==1.8.0
rich-rst==1.1.7

**Comment by willmcgugan** [comment]
If you using the Progress context manager, it will restore the terminal state. Perhaps a thread has been killed when your app exits, an the context manager never completes.

**Comment by willmcgugan** [comment]
Closing for now. Reopen if you can identify an issue in Rich.

**Comment by yuffington** [comment]
`      with progress:
          with ThreadPoolExecutor(max_workers=20) as pool:
              futures = []
              for file in filelist:
                  filename = file.split("/")[-1]
                  task_id = progress.add_task("flac2mp3", filename=filename, sta  rt=False)
                  f = pool.submit(convert_file, task_id, file)
                  futures.append(f)
          wait(futures)`

All my threads exit normally, and I even wait on them, so I'm not sure how that could be the issue.   Anyway.  Hoping this provides more data.

@willmcgugan

**Comment by Fak3** [comment]
I'm having the same issue on bash. Is there any solution?

**Comment by Fak3** [comment]
I found that my issue happened because of stdin handling in ffmpeg: https://stackoverflow.com/questions/65329483/python-subprocess-popen-ffmpeg-breaks-terminal-input
