### ISSUE TITLE
Filesize precision is not used on bytes/s

### ISSUE THREAD

**Issue by rlaphoenix** [Textualize/rich#2951]
https://github.com/Textualize/rich/blob/6d30ad0f30028210124c149811cbbe2b183711f9/rich/filesize.py#L30

On my end this is personally very annoying. If anything, I would want it to have no decimal places at all, but as it stands now the decimal places can go extremely long, e.g. `361.3816634069428 bytes/s`.

**Comment by willmcgugan** [comment]
The only way I can see that would occur is if a float was passed to `_to_str`, but it is typed as an `int`.

Can you give me a minimal reproducible example that demonstrates the problem.

**Comment by rlaphoenix** [comment]
> The only way I can see that would occur is if a float was passed to `_to_str`, but it is typed as an `int`.
> 
> Can you give me a minimal reproducible example that demonstrates the problem.

While it is true that file sizes cannot be float values, you are assuming that this `filesize.decimal` function would be used exclusively for filesize values which in my case I use it for Speed values. I also believe rich itself uses it for the Speed progress bar but I may be wrong. Also, the function does currently work just fine with float values therefore in my opinion if the function supports float, it should be typed as such.

```py
import time
from rich import filesize


downloads = 16

download_sizes = []
download_speed_window = 5
last_speed_refresh = time.time()

# ... assume logic with download_size variables and computations with time.time() against last_speed_refresh
# ... and adding then summing values in the download_sizes array to calculate a download speed.
download_speed = 512.2

print(f"Downloading at {filesize.decimal(download_speed)}/s")
```
> Downloading at 512.2 bytes/s

You can see here it does in fact accept float input and works exactly as intended, unless you change the download_speed value to something with a more precise float value like `download_speed = 512.243656789780945467` it will then print `Downloading at 512.243656789781 bytes/s` while all other units would cap at a precision of 2 decimal points.

**Comment by willmcgugan** [comment]
> if the function supports float, it should be typed as such.

That's not the purpose of typing. Typing says how the method was intended to be used, not how it could be used.

If you would like different behaviour, feel free to copy the code to your own project and modify it there.

**Comment by rlaphoenix** [comment]
Hi, while I can agree that typing can be used in that way, I did want to just bring it up as it bugs my JetBrains IDE just because I give it a float input, and the function also already assumes float input can be given considering it already does float precision cutoff on kilobytes onwards. Therefore technically it is already intended to be used on float input as well. Therefore, I do not currently agree with closing this issue.
