### ISSUE TITLE
[help] How can I change color character in console.ruler?

### ISSUE THREAD

**Issue by avatar-lavventura** [Textualize/rich#2952]
I am using https://rich.readthedocs.io/en/stable/reference/console.html, where I am unable to change the ruler's color.

```python
msg = "hello"
color = "red"
#: it does not have any color argument
console.rule(characters="+")   # goal is to print ++++++ in red
console.rule(characters="+")  # goal is to print ++++++ in yellow
```

I have tried `console.rule(characters="[red]+[/red]")` which did not help. It always print in green.

Wanting output would be printing each ruler in different color. How can I achieve it?

Thank you for your valuable help and time.

**Comment by davep** [comment]
Using the `style` argument mentioned in the documentation did it for me:

```python
>>> console.rule(characters="+", style="red")
```
