### ISSUE TITLE
[BUG] color palette isn't displaying properly on my pycharm terminal

### ISSUE THREAD

**Issue by roryai** [Textualize/rich#2959]
The color palette isn't displaying properly on my pycharm terminal:
![image](https://github.com/Textualize/rich/assets/18268474/f563fb34-cfc6-4155-ae3d-bb6411f6603a)

It is working correctly in my zsh terminal:
<img width="1419" alt="image" src="https://github.com/Textualize/rich/assets/18268474/f62eca8c-0305-408a-a24e-451adfbd9558">

Both are using different themes but it doesn't work in pycharm no matter which theme I use.

I have checked and played around with settings in `Editor > Color scheme > Console colors` but it hasn't made a difference.

I have changed my `TERM` env variable to `xterm-256color` and `xterm-color`, no difference either way.

I recognise this is likely a pycharm issue and not a rich issue.

Any help appreciated, thanks.

**Platform**
I'm running OSX Monterey 12.6
Pycharm 2022.3.2 CE

rich diagnostic output:
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=232 ColorSystem.STANDARD>                                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'standard'                                                    │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 17                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=232, height=17),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=232,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=17,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=232, height=17)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 232                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-color',         │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Darwin"
rich==13.3.5

**Comment by UmBsublime** [comment]
I've had some success in pycharm with exporting this additional envvar: `COLORTERM=truecolor`
Maybe this can help in your case too.

**Comment by roryai** [comment]
> I've had some success in pycharm with exporting this additional envvar: `COLORTERM=truecolor` Maybe this can help in your case too.

That fixed it, thank you :)

@UmBsublime
