### ISSUE TITLE
[REQUEST] Allow the pager to *stream* console output 

### ISSUE THREAD

**Issue by Jackenmen** [Textualize/rich#2962]
**How would you improve Rich?**

I would like for it to be possible for me to page the `console.print`ed input as soon as `console.print()` is called. This would help with paging text as it is received when you, for example, fetch multiple things from an API or when you're streaming output from some long-running program.

Example:
```py
import subprocess

with console.pager():
    with subprocess.Popen(["du", "/"], stdout=subprocess.PIPE, text=True) as proc:
        for line in proc.stdout:
            console.print(line)
```

Note that I'm just reusing the existing API in this example but that doesn't mean it necessarily should be that same API.

**What problem does it solve for you?**

It allows me to immediately show part of the output to the user while the program is fetching the rest of the data, as opposed to the user having to wait for *all* data to be available which could take a lot longer.

**Comment by willmcgugan** [comment]
This is probably more of the remit of Textual (https://github.com/Textualize/textual). Not something that could be easily added to Rich.
