### ISSUE TITLE
[BUG] Gallery Links broken

### ISSUE THREAD

**Issue by damienrj** [Textualize/rich#2965]
- [ X ] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [ X ] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

The links to the [ gallery section](https://github.com/Textualize/rich#projects-using-rich) broken , and return a 404 - Not found error.

**Comment by willmcgugan** [comment]
Thanks. We know, it will be fixed eventually.

**Comment by damienrj** [comment]
Thanks!
