### ISSUE TITLE
[help] How can I print color in tracebacks?

### ISSUE THREAD

**Issue by avatar-lavventura** [Textualize/rich#2973]
platform="Linux"
rich==13.3.5

I am using following example: https://rich.readthedocs.io/en/stable/traceback.html#printing-tracebacks

I observe that if the Exception text has color with square brackets it does not show up as affectin the color :-(

Example:

```python
from rich.console import Console

console = Console()

try:
    raise Exception("[red]alper[/red]")
except Exception:
    console.print_exception(show_locals=True)
```

output:

<img width="635" alt="My Screenshot 2023-05-26 at 10 55 36" src="https://github.com/Textualize/rich/assets/18537398/85c94594-68b5-4f1e-b24e-3e8848c29f54">

Wanted output be `[red]alper[/red]` as: red colored `alper`.

Thank you for your valuable time and help.

**Comment by willmcgugan** [comment]
There is no way for Rich to know you want console markup to be rendered there. It is more likely to break with exceptions that happen to contain square brackets.

**Comment by avatar-lavventura** [comment]
Can we indicate that Exception string is always console markup ? 

Sorry I didn't understand:

> break with exceptions that happen to contain square brackets.

**Comment by willmcgugan** [comment]
I'm afraid that's a bad idea, even behind a switch.

You can't be certain that any exception you get won't have something that looks like console markup. This may end up colorizing something incorrectly, hiding information, or even throwing another exception. `"[blue]text[/green]"` will raise an error.

I may at some point allow exceptions with a `__rich__` method to define how they are rendered, but Rich currently doesn't support that.
