### ISSUE TITLE
[Question] is there a way to selectively disable emoji?

### ISSUE THREAD

**Issue by takeda** [Textualize/rich#2975]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

Is there a way to selectively disable emoji? I'm surprised that `escape()` doesn't escape them.

**Comment by willmcgugan** [comment]
You can disable *emoji code* with emoji=False

**Comment by takeda** [comment]
That's what I did, I set `emoji=False` in `Console`, but that disabled it everywhere.

The problem I'm actually experiencing is when printing AWS ARN from SecretManager. That ARN is made up of a string that contains `:secret:` which is replaced by rich with an Unicode character. I don't want it to do that, but in other part of my program I do want to place emoji icons.

**Comment by willmcgugan** [comment]
You can `Text` objects to the Tree, which won't expand emoji.

Or you could disable emoji, and just cut and paste the emoji when you need it.

**Comment by takeda** [comment]
@willmcgugan I did something like that, but frankly I was hoping that one could have escape function like there's one for the control characters.
