### ISSUE TITLE
[BUG] `ModuleNotFoundError` when importing `rich.markdown`

### ISSUE THREAD

**Issue by mcdonnnj** [Textualize/rich#2979]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

I ran into this issue in a dependent projects ([ansible-lint]), but I believe this bug was introduced in https://github.com/Textualize/rich/pull/2977 and pushed out with [v13.4.0](https://github.com/Textualize/rich/releases/tag/v13.4.0). A package dependency was incorrectly implemented which results in failure when this package is used with Markdown.
<details>
<summary>Click to expand</summary>

I see the following error in [ansible-lint]:

```log
  File "/home/mcdonnnj/.pyenv/versions/python_testing/lib/python3.11/site-packages/ansiblelint/color.py", line 7, in <module>
    import rich.markdown
  File "/home/mcdonnnj/.pyenv/versions/python_testing/lib/python3.11/site-packages/rich/markdown.py", line 7, in <module>
    from typing_extensions import get_args
ModuleNotFoundError: No module named 'typing_extensions'
```

This is because https://github.com/Textualize/rich/blob/cf138826618dcabe3146b9178eaf312885ca28bb/rich/markdown.py#L7 does not import as is done elsewhere in this project such as https://github.com/Textualize/rich/blob/cf138826618dcabe3146b9178eaf312885ca28bb/rich/emoji.py#L10-L13 and because [typing_extensions] is only installed if Python <3.8 per https://github.com/Textualize/rich/blob/cf138826618dcabe3146b9178eaf312885ca28bb/poetry.lock#L359

I could be mistaken but that seems to be the most likely cause of this failure.
</details>

[ansible-lint]: https://github.com/ansible/ansible-lint
[typing_extensions]:https://github.com/python/typing_extensions

**Comment by mcdonnnj** [comment]
Yeah it looks like a fix is already on the way per https://github.com/Textualize/rich/commit/1176f81a82ddbc01d33d5f4995c01ed113baa1b5.

**Comment by willmcgugan** [comment]
Please try v13.4.1

**Comment by aroberts87** [comment]
Works like a charm for me, @willmcgugan! Thanks!

**Comment by mcdonnnj** [comment]
@willmcgugan After updating I no longer see the failure when running `ansible-lint`, thanks for the fast turnaround!
