### ISSUE TITLE
[BUG] print does not work well with DefaultDict

### ISSUE THREAD

**Issue by ZhiyuanChen** [Textualize/rich#2988]
- [ ] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [ ] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

`rich.print` inspects `__rich__` and `aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf` of object during printing. 

However, it does not inspect if the `__getattr__` of object will always returns something. 

`ipython` avoids this behaviour by checking `_ipython_canary_method_should_not_exist_` before inspecting the object. 

```python
from chanfig import Config
from rich import print as pprint


if __name__ == '__main__':
    config = Config(**{'hello': 'world'})
    print('print', config)
    pprint('rich.print', config)
    print(config.__rich__)
    print(config.keys())
```

```bash
rint Config(<class 'chanfig.config.Config'>,
  ('hello'): 'world'
)
rich.print Config(<class 'chanfig.config.Config'>,
  ('hello'): 'world'
  ('__rich__'): Config(<class 'chanfig.config.Config'>, )
  ('aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf'): Config(<class 'chanfig.config.Config'>, )
)
Config(<class 'chanfig.config.Config'>, )
dict_keys(['hello', '__rich__', 'aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf'])
```

ref: https://github.com/ZhiyuanChen/CHANfiG/issues/6

**Comment by willmcgugan** [comment]
I can't reproduce this with recent Rich:

```
print Config(<class 'chanfig.config.Config'>,
  ('hello'): 'world'
)
rich.print Config(<class 'chanfig.config.Config'>,
  ('hello'): 'world'
)
<bound method FlatDict.__rich__ of Config(<class 'chanfig.config.Config'>,
  ('hello'): 'world'
)>
dict_keys(['hello'])
```

**Comment by ZhiyuanChen** [comment]
> I can't reproduce this with recent Rich:
> 
> ```
> print Config(<class 'chanfig.config.Config'>,
>   ('hello'): 'world'
> )
> rich.print Config(<class 'chanfig.config.Config'>,
>   ('hello'): 'world'
> )
> <bound method FlatDict.__rich__ of Config(<class 'chanfig.config.Config'>,
>   ('hello'): 'world'
> )>
> dict_keys(['hello'])
> ```

Yes, since this issue wasn't responded in a long period, I did some hack in chanfig as a temporary solution. See more at https://github.com/ZhiyuanChen/CHANfiG/commit/3155769b0c806d81aac257995ee7c2494710f609.

However, this is still an issue. `rich` will have same behaviour when working with python's `collection.defaultdict`. 

<img width="854" alt="image" src="https://github.com/Textualize/rich/assets/28757366/5d678cf3-6c54-4c87-904e-b629a1c86bab">

**Comment by willmcgugan** [comment]
I'm going to need a minimal reproducible example, because Rich does work with default dict as you can see here:

```python
>>> from collections import defaultdict
>>> d=defaultdict(str)
>>> d["foo"] = "bar"
>>> from rich import print
>>> print(d)
defaultdict(<class 'str'>, {'foo': 'bar'})
```

**Comment by ZhiyuanChen** [comment]
> I'm going to need a minimal reproducible example, because Rich does work with default dict as you can see here:
> 
> 
> 
> ```python
> 
> >>> from collections import defaultdict
> 
> >>> d=defaultdict(str)
> 
> >>> d["foo"] = "bar"
> 
> >>> from rich import print
> 
> >>> print(d)
> 
> defaultdict(<class 'str'>, {'foo': 'bar'})
> 
> ```
> 

Thank you. Could you please try use chanfig <= 0.0.81?
