### ISSUE TITLE
[BUG] Console.log is documented to have an `overflow` argument, but it doesn't

### ISSUE THREAD

**Issue by yilei** [Textualize/rich#3010]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

The [API doc of Console.log](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console.log) says it supports a `overflow (str, optional) – Overflow method: “crop”, “fold”, or “ellipsis”. Defaults to None.` argument, but the [actual implementation](https://github.com/Textualize/rich/blob/8c7449f987a5c423a162aacdf969d647e6085918/rich/console.py#L1907) doesn't.

Should the `log` method be updated to also take the same `overflow` argument as `print`?

**Comment by willmcgugan** [comment]
I don't think the overflow makes sense in the context. I've removed it from the docstring. Thanks for the report.
