### ISSUE TITLE
[BUG] v13.4.2 broke mypy in my github build

### ISSUE THREAD

**Issue by erezsh** [Textualize/rich#3020]
This is the build: https://github.com/lark-parser/lark/actions/runs/5442030726/jobs/9900908047

We don't run mypy on markdown-it-py, but it broke it nonetheless.

**Comment by erezsh** [comment]
Confirmed. Adding `rich<=13.4.1` solved it.

**Comment by willmcgugan** [comment]
markdown-it-py >= 3 requires Python 3.8. But Rich is compatible with markdown-it-py >= 2.2.0 which works with Python 3.7

If you `pip install` rich, it will install compatible versions. If you want 3.7 compatibility, you could downgrade markdown-it-py to < 3
