### ISSUE TITLE
[REQUEST]Configurable size of output from inspect()

### ISSUE THREAD

**Issue by wileur** [Textualize/rich#3023]
Consider posting in https://github.com/textualize/rich/discussions for feedback before raising a feature request.

Have you checked the issues for a similar suggestions? 

Yes, didn't find anything

**How would you improve Rich?**

I would like to be able to increase the number of lines/items that inspect() can show. Right now it is hardcoded in 
_inspect.py -> class Inspect() -> _render()

At line 170 there is a call to Pretty(obj, indent_guides=True, max_length=10, max_string=60)

I propose two steps:
-Make max_length and max_string configuration parameters for the inspect module. In this way they can be configured for a project
-Make them keyword parameters to the inspect() call. Default values can be None to use the project wide setting

**What problem does it solve for you?**

I work a lot with long and deep structures on several platforms. While altering the source on one development device is doable it becomes unwieldy on all the deployed devices. I could make my own version, but would prefer to stick to the official release.

**Comment by willmcgugan** [comment]
Sorry, I don’t think there is much demand for this. You can always rich.print your object if you need to see all the data.
