### ISSUE TITLE
[REQUEST] Implement CLICOLORS / support CLICOLOR_FORCE

### ISSUE THREAD

**Issue by abesto** [Textualize/rich#3028]
**How would you improve Rich?**

According to the documentation, `rich` currently supports `NO_COLOR` and `FORCE_COLOR`. https://bixense.com/clicolors/ seems to be gaining a fair amount of traction, and specifies `CLICOLOR_FORCE`. It'd be nice if Rich respected this env var as well.

**What problem does it solve for you?**

In a polyglot environment, this would allow me to more confidently write just `CLICOLOR_FORCE=1` instead of `FORCE_COLOR=1 CLICOLOR_FORCE=1`.

**Comment by willmcgugan** [comment]
Rich will try to support standards, but I’m not convinced this is enough of a standard yet.
