### ISSUE TITLE
Are links not meant to work in trees?

### ISSUE THREAD

**Issue by AutonomousCat** [Textualize/rich#3029]
```py
nodes[current_hierarchy] = parent_node.add(f'[link={value}]{parts[i]}[/link]')
```

renders:
![image](https://github.com/Textualize/rich/assets/130127508/b24b4cac-adc1-4361-8827-ef312bdc78e7)

Doesn't work but some examples I came across definitely have links in trees.

**Comment by willmcgugan** [comment]
Links should work in trees. If you Don’t think it’s working, I’d appreciate an mre to test.

https://label.dev/articles/minimal-reproducible-example/
