### ISSUE TITLE
[BUG] svg Tables seem bugged when trying to generate an png from them 

### ISSUE THREAD

**Issue by MrMatch246** [Textualize/rich#3034]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

When exporting a table to svg and afterwards trying to generate a png from them (cairosvg and some online converters)
I get broken pictures. Maybe related or not Jetbrains cant display them which makes me think that something might be broken there too

i tried to manually fix it as shown in the attachments resulting in the expected pngs but breaking the view in the chrome browser. 

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
multiple, server/wsl 

╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=228 ColorSystem.EIGHT_BIT>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = '256'                                                         │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 41                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=228, height=41),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=228,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=41,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=228, height=41)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 228                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"

</details>

Actual:
![test](https://github.com/Textualize/rich/assets/50702646/0e44d097-c6d9-4066-85cd-a58f905790e2)

"Expected" (this ends up in a not broken png)
![test_fixed](https://github.com/Textualize/rich/assets/50702646/3180b2b8-5ae8-4aa1-9bd2-fefbe2292400)
![test](https://github.com/Textualize/rich/assets/50702646/aec5a748-f737-4aea-aadd-625b3dfb3f48)

**Comment by willmcgugan** [comment]
The issue lies with the software you are using to render the file. You could modify the template used to generate the SVG, but as it was carefully chosen to produce the best results, you may break it in other ways.

**Comment by MrMatch246** [comment]
Id be willing to give it a try anyway, could you give me some direction how i could change the font in the template? i would assume this is a matter of string replace if i would like to take the dirty way?

**Comment by willmcgugan** [comment]
See the `code_format` attribute here https://github.com/Textualize/rich/blob/master/rich/console.py#L2278
