### ISSUE TITLE
[REQUEST] How to use the Rich library to stream print the content of the current chatgpt and support markup rendering

### ISSUE THREAD

**Issue by xiaoymin** [Textualize/rich#3046]
Now，I use live.update method to display content with markdown content by HTTP SSE response ，simple code like:

```python
    console = Console()
    md_content=""
    with Live(console=console, refresh_per_second=4) as live:
        i=0
        for event in response.events():
            if event.event == "add":
                md_content=md_content+event.data
            elif event.event == "error" or event.event == "interrupted":

                md_content=md_content+event.data
            elif event.event == "finish":

                md_content=md_content+event.data
            else:

            md = Markdown(md_content)
            live.update(md)

```

Now,use like OpenAI api use sse protocol to send data is not all result at onece.so the markdown content i must be concat together and then use `Markdown` method to init .

this way can resolve my problem. But the screen keeps flashing, and the experience is very poor。

So, may I ask if there is a better way？

Thanks

**Comment by willmcgugan** [comment]
You would be better off using Textual (https://github.com/Textualize/textual) for something like this.
