### ISSUE TITLE
[BUG] Progress bar doesn't flush output

### ISSUE THREAD

**Issue by bjourne** [Textualize/rich#3055]
The progress bar doesn't automatically flush so at least in my terminal it appears stuck. MWE:

    path = Path('psn.log')
    size = path.stat().st_size
    with open(path) as f:
        with wrap_file(f, size, description = 'Parsing...') as f:
            for line in f:
                #print('', end = '', flush = True)
                pass

Uncommenting the print makes the progress bar work, but makes the code run very slow since the terminal is updated once for every line. I only want to update the progress bar when the completion percentage changes. My workaround is to write this:

            for i, line in enumerate(f):
                if i % 10_000 == 0:
                    print('', end = '', flush = True)

But it would be nicer if rich handled it automagically.

**Comment by willmcgugan** [comment]
Please repost with the issue template filled in and an MRE. https://label.dev/articles/minimal-reproducible-example/

**Comment by bjourne** [comment]
See the snippet in the first comment. The non-flushing happens all the time with the `wrap_file` progress bar.
