### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by KDot227** [Textualize/rich#3068]
Please add a way to center/align the Progress module. Currently from what I've seen it can only align to the left but I would love for it to be able to be centered.

**Comment by willmcgugan** [comment]
You can extend `get_renderable()` and wrap the result in a `rich.align.Align`

**Comment by KDot227** [comment]
> You can extend `get_renderable()` and wrap the result in a `rich.align.Align`

does this also work with the spinners?
