### ISSUE TITLE
Width measurement of align object

### ISSUE THREAD

**Issue by Aradhya-Tripathi** [Textualize/rich#3075]
**Describe the bug**

```__rich_measure__``` returns invalid measurement for an Align object, the object width shouldn't just be the passed in renderable width

<img width="782" alt="Screenshot 2023-08-05 at 5 54 36 PM" src="https://github.com/Textualize/rich/assets/67282231/518151c9-896c-4ac1-a232-d70ac83e318f">

**Comment by Aradhya-Tripathi** [comment]
I think Ideally the measurement of align object should just be ```Measurement(0, console.options.max_width)```

**Comment by willmcgugan** [comment]
This is the expected behavior. You may have a misunderstanding in what it means to measure renderables...
