### ISSUE TITLE
[BUG] Progress Display Overwrites Separate Console Output and Repeats Past Tasks

### ISSUE THREAD

**Issue by Johnserf-Seed** [Textualize/rich#3086]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

## Describe the bug

When utilizing the `Progress` class from the `rich` library to showcase progress for downloading content across different pages, I've noticed repeated task outputs on my terminal. Specifically, as my program fetches and processes data from subsequent pages, the progress display seems to refresh and reflect past tasks. I've ensured there is no repetition in my data or within the tasks themselves in `rich`.

this is first-page download

![image](https://github.com/Textualize/rich/assets/40727745/68c8abe2-f069-4058-b312-134440565758)
![image](https://github.com/Textualize/rich/assets/40727745/2735f77e-0d71-417b-a123-c4dbb9f86d03)

When I step-by-step debugged it, I found that the page-flip download redraws the terminal causing a lot of duplicate output for many tasks

![image](https://github.com/Textualize/rich/assets/40727745/249cd6f9-da31-4c9b-824d-048247819f6a)
![image](https://github.com/Textualize/rich/assets/40727745/86b6f3e8-bb54-4a89-becd-3d9ed54d1df1)

The task_ids and tasks are not duplicates.

## To Reproduce

Part of the code uses the example's code https://github.com/Textualize/rich/blob/master/examples/downloader.py
A brief code snippet is as follows:

```python
import os
import asyncio
from rich.progress import (
    BarColumn,
    DownloadColumn,
    Progress,
    TaskID,
    TextColumn,
    TimeRemainingColumn,
    TransferSpeedColumn,
)
from rich.console import Console

console = Console(width=150) 
console = rich.console.Console(color_system="truecolor")


class Download:
    def __init__(self, config, progress):
        self.config = config
        self.progress = progress

    async def AwemeDownload(self, aweme_data):
        download_tasks = []
        for aweme in aweme_data:
            ctime_f = Util.time.strftime('%Y-%m-%d %H.%M.%S', Util.time.localtime((aweme['create_time'])))
            base_path = aweme['path']
            subdir_name = f'{ctime_f}_{aweme["desc"]}'
            desc_path = Util.os.path.join(base_path, subdir_name)
            os.makedirs(desc_path, exist_ok=True)
            if self.config['music'].lower() == 'yes':
                try:
                    music_url = aweme['music_play_url']['url_list'][0]
                    music_file_name = f'{ctime_f}_{aweme["desc"]}_music'
                    music_file_path = f'{music_file_name}.mp3'
                    music_full_path = os.path.join(desc_path, music_file_path)
                    music_state = os.path.exists(music_full_path)
                    if music_state:
                        task_id = self.progress.add_task(description="[  skip  ]:",
                                                        filename=self.trim_filename(music_file_path, 50),
                                                        total=1, completed=1)
                        self.progress.update(task_id, completed=1)
                    else:
                        task_id = self.progress.add_task(description="[  music  ]:",
                                                        filename=self.trim_filename(music_file_path, 50),
                                                        start=False)
                        console.print('example print')
                        download_task = asyncio.create_task(self.download_file(task_id, music_url, music_full_path))
                        download_tasks.append(download_task)
                        await asyncio.sleep(0)
                except IndexError:
                    pass
         await Util.asyncio.gather(*download_tasks)

class Profile:
    def __init__(self):
        self.process_console = Console(width=150)
        self.progress = Progress(
                Util.TextColumn("{task.description}[bold blue]{task.fields[filename]}", justify="left"),
                Util.BarColumn(bar_width=25),
                "[progress.percentage]{task.percentage:>3.1f}%",
                "•",
                Util.DownloadColumn(),
                "•",
                Util.TransferSpeedColumn(),
                console=self.process_console
        )
        self.download = Download(self.config, self.progress)

    async def get_Profile(self, count: int = 20) -> None:
       ......
        with self.download.progress:
            await self.download.AwemeDownload(aweme_data)
```

Another problem is that I'm using a different console object but progress still overwrites its output.

## Expected behavior

1. For the progress display, only tasks pertinent to the current page should be shown.
2. The separate Console object's outputs should remain unaffected by the Progress display.

## Actual behavior

1. Old tasks from prior pages are redrawn atop my terminal.
2. Console messages printed using the separate Console object are overwritten by the Progress display.

This is my project https://github.com/johnserf-seed/tiktokdownload

**Comment by willmcgugan** [comment]
You will need to use the same console object throughout your code if you want to combine printing with scrollbars.

**Comment by Johnserf-Seed** [comment]
> You will need to use the same console object throughout your code if you want to combine printing with scrollbars.

When I change console=self.process_console to console=console for progress, it still doesn't work. This is because the downloader.py that I referenced from examples at the beginning did not set the console property. When the terminal print overrides the terminal progress bar output I asked gpt3.5 and it told me that the output and the progress bar output can be separated. Of course, again they don't work.
I forgot to mention my version, py version ```3.11.1``` rich is up to date.

**Comment by willmcgugan** [comment]
I'm afraid I didn't follow that. You will need to use the same Console object. Please trust me over GPT.

**Comment by Johnserf-Seed** [comment]
> I'm afraid I didn't follow that. You will need to use the same Console object. Please trust me over GPT.

I didn't use 2 console objects at first, I used the downloader.py that you provided

**Comment by Johnserf-Seed** [comment]
Now with the console object declaration deleted, the progress override is still there. I used python's print and console.print still. Everything works fine on the first page, when I call 
```python
with progress:
    await AwemeDownload(aweme_data)
```
again, the output is overwritten and repeated

**Comment by willmcgugan** [comment]
The issue is most likely in your code, and not Rich itself. I suspect you are writing to stdout somewhere, and not going through the Progress console object. It could also be related to the way you have fixed the console width, rather than let Rich auto-detect it.

If you need further help, please narrow down the problem to a short piece of code I can test against.

https://label.dev/articles/minimal-reproducible-example/

**Comment by Johnserf-Seed** [comment]
So do I need to use progress.console.log to control the output, but I checked my code and the list given to copy_url has no duplicate tasks

**Comment by dmdhrumilmistry** [comment]
> I'm afraid I didn't follow that. You will need to use the same Console object. Please trust me over GPT.

This worked for me. It turned out that my logging config was using stderror which caused the issue. I used `rich.logging.RichHandler` and passed `console` as arg.

```python
logging.basicConfig(
    format="%(message)s",
    datefmt="[%X]",
    handlers=[RichHandler(
        console=console, rich_tracebacks=True, tracebacks_show_locals=True)],
)
```
