### ISSUE TITLE
[BUG]Table(expand=True) does not work when rendered inside a textual.RichLog

### ISSUE THREAD

**Issue by sjoerdtimmer** [Textualize/rich#3093]
A rich.table.Table() with the expand=True set, should expand to take up full width. 
This works when rendering to a console, but not when rendering to a textual.RichLog

Here is a small non-working example:
https://pastebin.com/naic2VK1
![image](https://github.com/Textualize/rich/assets/633834/8d696b19-fe23-4577-86ce-54af69937b36)

I have included a custom Ruler renderable that does exhibit the expected behaviour, demonstrating that the Console and ConsoleOptions passed into __rich_console__ and __rich_measure__ are correct (so I assume this issue is with the rich Table, rather than the textual.RichLog)

Python 3.11.4
rich 13.5.2
textual 0.33.0

rich.diagnose:
https://pastebin.com/CkTbLShW

**Comment by willmcgugan** [comment]
RichLog will calculate the optimal size of for a renderable by default. 

You can add `expand=True` to [`write`](https://textual.textualize.io/widgets/rich_log/#textual.widgets._rich_log.RichLog.write) to allow the renderable to expand beyond its optimal size.
