### ISSUE TITLE
[BUG] Rich markdown printed to console only shows a single link in a column/ table cell

### ISSUE THREAD

**Issue by cwerner** [Textualize/rich#3115]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

I use Rich to format a pandas data frame with multiple links in some column to markdown and show it in the terminal. However, when there are more than a single link in a column rich only shows the last one?

```python
from rich.console import Console
from rich.markdown import Markdown

import pandas as pd

md_table = pd.DataFrame(
    {
        "links": ["[page1](https://www.example.com/page1), [page2](https://www.example.com/page2)"]
    }
).to_markdown()

console = Console()
console.print(Markdown(md_table))
```

Output:
```bash
      links  
 ━━━━━━━━━━━ 
  0   page2  
```

Expected
```
      links  
 ━━━━━━━━━━━ 
  0   page1, page2  
```

If I write the markdown to a file I get the expected table with multiple links...

**Platform**

platform="Darwin"
rich==13.5.2

</details>

**Comment by willmcgugan** [comment]
Could you post the Markdown it generates?

**Comment by cwerner** [comment]
```
|    | links                                                                          |
|---:|:-------------------------------------------------------------------------------|
|  0 | [page1](https://www.example.com/page1), [page2](https://www.example.com/page2) |
```

**Comment by cwerner** [comment]
I actually discovered that the problem is that if there is a link in a table, only the link (and in case of multiple links the last one) is rendered.

For instance:

```python
from rich.console import Console
from rich.markdown import Markdown

import pandas as pd

md_table = pd.DataFrame(
    {
        "links": ["some text [page1](https://www.example.com/page1 )"]
    }
).to_markdown()

console = Console()
console.print(Markdown(md_table)) 
```

will result in:
```bash
      links  
 ━━━━━━━━━━━ 
  0   page1  
```

Thus, swallowing "some text" that was also present in this table cell. Not sure if this gives a clue about what might be wrong?

**Comment by willmcgugan** [comment]
This may also be present in Textual.

**Comment by davep** [comment]
> This may also be present in Textual.

If I'm reading the issue correctly, it seems to be working fine in Textual (as seen via Frogmouth):

![Screenshot 2023-08-31 at 13 13 57](https://github.com/Textualize/rich/assets/28237/3a6e2c59-6b87-4816-8a8b-134b7c36c065)

viewing this Markdown:

```markdown
| One                                                        | Two       | Three                                 |
|------------------------------------------------------------|-----------|---------------------------------------|
| Some test [and then a link](https://textualize.io/)        | Just Text | [Just a link](https://textualize.io/) |
| Text [then a link](https://blog.davep.org/) then more text | Just Text | Some final text                       |
```

**Comment by willmcgugan** [comment]
Good to know. We must be doing something different in Rich.

**Comment by cwerner** [comment]
Oh nice. Wondering: Can I use `textual` to render my Markdown before I hand it over to `console.print()`until this bug is fixed?

**Comment by rodrigogiraoserrao** [comment]
Consider this markdown file:

```md
[page 1](https://mathspp.com)

| links |
| - |
| asdfasdf  [page 1](https://mathspp.com) |
```

Running `python -m rich.markdown file.md` will show the first link just fine but the one on the table doesn't:

```
page 1 (https://mathspp.com)


  links
 ━━━━━━━
  )
```

Putting text on the right of the table link makes the link go away and only displays that text:

<details>
<summary <code>file.md</code> with text on the right. </summary>

```md
[page 1](https://mathspp.com)

| links |
| - |
| asdfasdf  [page 1](https://mathspp.com) right |
```
</details>
<details>
<summary> Output of <code>python -m rich.markdown file.md</code> </summary>

```
page 1 (https://mathspp.com)


  links
 ━━━━━━━━
   right
```

</details>

---

Running with `--hyperlinks` does a slightly better job, but it still drops things.

### With text on the right

<details>
<summary <code>file.md</code> with text on the right. </summary>

```md
[page 1](https://mathspp.com)

| links |
| - |
| asdfasdf  [page 1](https://mathspp.com) some text |
```

</details>
<details>
<summary> Output of <code>python -m rich.markdown file.md -y</code> </summary>
(The “page 1” has the proper link in the terminal)

```
page 1


  links
 ━━━━━━━━━━━━
   some text
```
</details>

---

### Without text on the right

<details>
<summary <code>file.md</code> without text on the right. </summary>

```md
[page 1](https://mathspp.com)

| links |
| - |
| asdfasdf  [page 1](https://mathspp.com) |
```
</details>
<details>
<summary> Output of <code>python -m rich.markdown file.md -y</code> </summary>
(The output has the proper links in the terminal)

```
page 1


  links
 ━━━━━━━━
  page 1
```
</details>

**Comment by rodrigogiraoserrao** [comment]
Turns out we're seeing this interesting interaction with a bunch of inline styles in markdown.

The markdown below gets rendered into the output shown after that:

```md
| stuff |
| - |
| asdfasdf  [page 1](https://mathspp.com) some text |
| This is `some code` here |
| This is `some code` |
| Can I set this to _italics_? |
```

```
  stuff
 ━━━━━━━━━━━━
   some text
   here
  some code
  ?
```
