### ISSUE TITLE
[BUG] Log warning in sublime text

### ISSUE THREAD

**Issue by Erimus-Koo** [Textualize/rich#3119]
**Describe the bug**

- I have two files: `rich_log.py` and `config.py`.
- In `rich_log`, I set up a logger and run a build in Sublime Text, everything is good.
- In `config`, I import the log from `rich_log` and then run it, but there's a warning message.

<img width="672" alt="image" src="https://github.com/Textualize/rich/assets/17139670/edb41d99-d68b-4284-a8a2-41f9d4d6252e">

## rich_log.py

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import logging
import os

from rich.logging import RichHandler


def set_log(logger_name='rich') -> logging.Logger:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)

    # rich handler
    rh = RichHandler()
    logger.addHandler(rh)

    # file handler
    # ...

    return logger

log = set_log(__name__)


if __name__ == '__main__':

    from rich import inspect
    inspect(log)
    log.debug("Log message")
    log.info("Log message")
    log.error("Log message")
    log.warning("Log message")
    log.critical("Log message")
```

The file builds without any warnings in Sublime Text.

## config.py

```
from rich_log import set_log, test_log

from rich import inspect

log = set_log()
inspect(log)
log.debug("Log message")
log.info("Log message")
log.error("Log message")
log.warning("Log message")
log.critical("Log message")
```

<img width="672" alt="image" src="https://github.com/Textualize/rich/assets/17139670/edb41d99-d68b-4284-a8a2-41f9d4d6252e">

## Platform

- MacOS
- SublimeText 4152
- Python 3.11
- rich 12.6.0

**Comment by Erimus-Koo** [comment]
I noticed that when I added `rh = RichHandler(show_time=False)` in `rich_log.py`, it caused a change in the warning message in `config.py`. This leads me to believe that there may be something related to the rich library.

<img width="675" alt="image" src="https://github.com/Textualize/rich/assets/17139670/1592a2eb-cdb1-49bf-9fb1-5338d69faabf">

**Comment by Erimus-Koo** [comment]
And if I set a logger from logging, there's no warning.

```
# rich_log.py
log1 = logging.getLogger()
```

```
# config.py
from utils.logging_lite import set_log, log1
```

<img width="674" alt="image" src="https://github.com/Textualize/rich/assets/17139670/d31a766c-ea63-4a7d-ae60-c01fcd9d6f44">

Does "rich" do something special or return something?

**Comment by willmcgugan** [comment]
Nothing to do with Rich. It is something your editor is doing.
