### ISSUE TITLE
how do i get rid of this thing

### ISSUE THREAD

**Issue by qrdlgit** [Textualize/rich#3127]
This package is driving me insane as it's screwing with stack traces to the point that they're useless and some libraries import it even though I don't ask them to. 

Drives me batty.

It's like the tqdm nightmare all over again.   This should not be default behavior and should never be bundled - it creates bugs and instability everywhere.

**Comment by willmcgugan** [comment]
I'm sorry you are batty, but it is nothing to do with Rich.
