### ISSUE TITLE
[BUG] Markdown does not render "markdown" code blocks correctly!

### ISSUE THREAD

**Issue by gagb** [Textualize/rich#3128]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

Rich's markdown rendering fails on the following example.

Example:

```python
from rich.panel import Panel
from rich.markdown import Markdown
from rich.console import Console, group, Group
from rich.text import Text

content = "Sure, here is the information in a markdown table:\n\n```markdown\n| Rank | River Name | Length (km) |\n| --- | --- | --- |\n| 1 | Nile | 6,650 |\n| 2 | Congo | 4,700 |\n| 3 | Niger | 4,180 |\n| 4 | Zambezi | 2,574 |\n| 5 | Ubangi | 2,270 |\n```"

print(content)

panel_content = Markdown(content)

console = Console()
console.print(panel_content)

```

Running this code results in:
<img width="363" alt="image" src="https://github.com/Textualize/rich/assets/13227607/110747e3-347e-42cb-ad3e-5167288e28f8">

**Platform**
MacOS 13.5.1 (22G90)
Python 3.11.4
rich==13.5.2
iTerm2 (Build 3.4.16)

**Comment by davep** [comment]
What output would you expect? For example, if I take your input document and included it in this comment, which will render it with GitHub's own Markdown rendering engine, it looks pretty much the same:

---
Sure, here is the information in a markdown table:

```markdown
| Rank | River Name | Length (km) |
| --- | --- | --- |
| 1 | Nile | 6,650 |
| 2 | Congo | 4,700 |
| 3 | Niger | 4,180 |
| 4 | Zambezi | 2,574 |
| 5 | Ubangi | 2,270 |
```
---

Or, if I preview it with the [online markdown-it demo](https://markdown-it.github.io/), it also appears the same:

<img width="773" alt="Screenshot 2023-09-11 at 08 27 00" src="https://github.com/Textualize/rich/assets/28237/0240f9bf-e83e-4ee6-bf86-ff6df301a22b">

What incorrect rendering are you seeing?

**Comment by rodrigogiraoserrao** [comment]
I'm pretty sure there's a bit of confusion here between the table that was pasted inside the triple backticks, which is supposed to represent “markdown source ”””code””””, and the pretty table representation one gets from markdown tables.

@gagb `Markdown` will render markdown. If you want a table to be rendered, you shouldn't put it inside a code block.
I.e., use this code:

```py
from rich.panel import Panel
from rich.markdown import Markdown
from rich.console import Console, group, Group
from rich.text import Text

content = "Sure, here is the information in a markdown table:\n\n| Rank | River Name | Length (km) |\n| --- | --- | --- |\n| 1 | Nile | 6,650 |\n| 2 | Congo | 4,700 |\n| 3 | Niger | 4,180 |\n| 4 | Zambezi | 2,574 |\n| 5 | Ubangi | 2,270 |\n"

print(content)

panel_content = Markdown(content)

console = Console()
console.print(panel_content)
```

**Comment by gagb** [comment]
You are correct @rodrigogiraoserrao -- your response helped clarify my confusion about the semantics of the renderer. Thank you!

**Comment by rodrigogiraoserrao** [comment]
> Thank you!

I'm glad I could help.
