### ISSUE TITLE
[BUG] Status and console width change

### ISSUE THREAD

**Issue by Heisenbeeerg96** [Textualize/rich#3148]
- [ ] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [ ] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

I'm testing this code:
`python -m rich.status`

which is presented on git repo description. The issues I get is when I do the change of the terminal width, the status/spinner gets moved into new line, and "freeze" status left above it. I know that the wrapping these ways is "normal" but the issue appears even when I do the width reduce by 1, like if the status is padded to be the full width of the terminal. Is there any parameter to set or anything to bypass this? I used Windows Terminal, PowerShell, it behaves the same.
![rich](https://github.com/Textualize/rich/assets/24758140/03a1b9a8-c4f7-4ab2-84c6-9ee00cb5a8ce)

**One more thing**, to not open one more discussion, using `with console.status(""):` together with `console.print("text",end="")`, it prints nothing until the string passed has "\n" in it, is this expected?
**Platform**
![image](https://github.com/Textualize/rich/assets/24758140/92b986a7-681d-409f-a804-9800b7e3dce4)

**Comment by willmcgugan** [comment]
Wrapping of the status is expected if you change the size of the terminal.

Prints will be line buffered (i.e. it will wait for a \n) while the status is running.
