### ISSUE TITLE
[REQUEST] Convert text to ANSI string

### ISSUE THREAD

**Issue by ocervell** [Textualize/rich#3152]
Is there anyway currently to take a markup-formatted string and render it as an ANSI string replacing the markup by the right ANSI codes ?

Basically:
```python
my_text = '[bold green]My[/][bold red]awesome[/][bold yellow]text[/]'
text = Text.from_markup(my_text)
ansi_string = text.to_ansi() # <-- something like this ?
print(ansi_string)  # using Python's print function would work
```

My use case: I'm saving colored output as I go and saving it in a database. Later I want to show it on a web interface that can display colors using ANSI codes only.

Thanks for this great library !

**Comment by willmcgugan** [comment]
I'm guessing you want to [capture output](https://rich.readthedocs.io/en/latest/console.html#capturing-output)?

**Comment by ocervell** [comment]
Nope, simply want to convert `rich`'s markup to ANSI. I am not even using a console.

**Comment by willmcgugan** [comment]
Trust me, you need the capture API. If you capture the output it won't print it.

**Comment by ocervell** [comment]
Alright, I guess this works:
```
import io
from rich.console import Console
console = Console()
my_text = '[bold green]My[/][bold red]awesome[/][bold yellow]text[/]'
with console.capture() as capture:
  console.print(my_text)
str_output = capture.get()
print(str_output)
```
returns:
```
'\x1b[1;32mMy\x1b[0m\x1b[1;31mawesome\x1b[0m\x1b[1;33mtext\x1b[0m\n'
```

**Comment by ocervell** [comment]
Final method for future watchers:

```
from rich.console import Console

def rich_to_ansi(text):
	"""Convert text formatted with rich markup to standard string."""

	tmp_console = Console(file=None, highlight=False)
	with tmp_console.capture() as capture:
		tmp_console.print(text, end='')
	return capture.get()
```

and use it like:

```
>>> text = '[bold green]My[/][bold red]awesome[/][bold yellow]text[/]'
>>> ansi_text = rich_to_ansi(text)
>>> ansi_text
'\x1b[1;32mMy\x1b[0m\x1b[1;31mawesome\x1b[0m\x1b[1;33mtext\x1b[0m'
>>> print(ansi_text)
# colored text
```

Setting `file=None` prevents printing it to standard out in the process.
