### ISSUE TITLE
[REQUEST] Windows terminal emoji is not supporting 

### ISSUE THREAD

**Issue by mrintroverrt** [Textualize/rich#3175]
**Issue Description:**

I have a piece of code that uses emojis for formatting in my project. The code works correctly on Linux, but on Windows, I encounter an issue where some emojis are displayed as blank boxes, specifically, 🖾. 

**Steps to Reproduce:**

1. Open the code on Windows.
2. Observe the rendering issue with the emoji 🖾.

**Expected Behavior:**

The emoji 🖾 should render correctly on all platforms.

**Platform Information:**

- Operating System: Windows
- Text Editor/Environment: [Specify the text editor or environment where you are experiencing this issue]

**Additional Information:**
**Sample Code**
`print(f"[bold green1]:small_blue_diamond: Performing action: [bold]{action}[/bold][/bold green1]")`
[Include any additional details or configurations that might be relevant to the issue.]

**Comment by TomJGooding** [comment]
If your terminal doesn't support emojis, there's isn't anything Rich can do about that.

What terminal emulator are you using, the new Windows Termianl or Console Host (conhost.exe)?

**Comment by mrintroverrt** [comment]
Thanks now it's working fine with new terminal
