### ISSUE TITLE
[BUG] rich.text - Text.highlight_words() : highlights letters, not words

### ISSUE THREAD

**Issue by bwprog** [Textualize/rich#3184]
- [ ] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [ ] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

Using the Text class, I try to highlight a specific word in the text using the highlight_words() function. The word does get highlighted, however all other letters that match any letter in the highlight word within the Text object get highlighted as well.

<img width="349" alt="richtextbug" src="https://github.com/Textualize/rich/assets/124224572/099c04ab-aece-4b70-a37d-7561940684e3">

The fact both the function and keyword use "words" and not "letters" indicates to me this is a bug. I looked at the source code and I think I see the problem.

This line of the code treats keyword "words" as an iterable which it is, as a string. 

```
re_words = "|".join(re.escape(word) for word in words)
```

It ends up splitting the keyword string like this:
```
'j|s|o|n'
```

I think it's just missing split on the end like this. That changes the iterable to a list of words.
```
re_words = "|".join(re.escape(word) for word in words.split(" "))
```

I made the change on my local text.py and get what I think should be the correct output. Works on 1 and 2 words with a space separating. I don't know if this would break any edge cases.

<img width="544" alt="richtextfix" src="https://github.com/Textualize/rich/assets/124224572/a3c62643-1a7b-43d5-bf57-e2f63579cf9d">

With that, the keyword string becomes this:
```
'json'
```
Or with a second word, 'json output', like this:
```
'json|output'
```

**Platform**

<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

Linux OpenSuse Tumbleweed (2023-11-02) / Python 3.11.5 / Konsole 23.08.2 / rich 13.6.0

<img width="634" alt="richdiag1" src="https://github.com/Textualize/rich/assets/124224572/e1ad58ce-6e9f-4631-b0db-d3a20cab8327">

<img width="634" alt="richdiag2" src="https://github.com/Textualize/rich/assets/124224572/917c0d69-a8bf-45af-92a0-68e4730282ae">

</details>

**Comment by darrenburns** [comment]
The signature for `highlight_words` says that it takes an argument of type `words: Iterable[str]`.

This means you need to pass your words as, for example, a list:

```python
text.highlight_words(["one", "two", "three"], style="blue")
```

In your original example, you should do:

```python
j.highlight_words(["json"], style="blue")
```

Closing this issue - but feel free to let me know if you're still having trouble.
