### ISSUE TITLE
Center align text in console screen

### ISSUE THREAD

**Issue by Conor0Callaghan** [Textualize/rich#3196]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

When more than one line is output is output in the console using a screen (using the align.center example code in screen.py), only the wider text is kept centred, leaving the shorter lines to fall back to left justify. 

![image](https://github.com/Textualize/rich/assets/4090256/9caf4782-c787-4a6c-a602-138419f3d1e0)

**Platform**

OS: Debian Bookworm 12.2 
rich: 13.6.0 

<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by TomJGooding** [comment]
Here's an slightly modified example from [the docs for the Console screen](https://rich.readthedocs.io/en/stable/console.html?highlight=screen#alternate-screen) which uses a Text class to justify multiline text:

```python
from time import sleep

from rich.align import Align
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

console = Console()

with console.screen(style="bold white on red") as screen:
    for count in range(5, 0, -1):
        text = Align.center(
            Text.from_markup(
                "[blink]Don't Panic![/blink]\n"
                "You will be returned to the command prompt in...\n"
                f"{count}",
                justify="center",
            ),
            vertical="middle",
        )
        screen.update(Panel(text))
        sleep(1)
```

**Comment by Conor0Callaghan** [comment]
Do you think the issue is still relevant as a bug @TomJGooding or do you think the example code just needs to be updated? For me I think the align.center should permeate throughout the text within the panel.

**Comment by Conor0Callaghan** [comment]
> Aligning is not quite the same thing as text justification. Align always applies to the bounding box defined by the renderable.

Ah OK I see, I think that's where the confusion arose. Thanks for rich and thanks for clearing it up @willmcgugan ! Ill close as a non bug
