### ISSUE TITLE
Export `rich.text.TextType` so it shows up in the reference

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/rich#3213]
Exporting `TextType` and making it visible in the docs means we'll be able to link to it from the Textual docs, where it shows up _a lot_.

**Comment by willmcgugan** [comment]
@rodrigogiraoserrao I think this is done. Please check and close if it is.

**Comment by rodrigogiraoserrao** [comment]
I don't think it is.
`TextType` in `rich/text.py` _is_ documented with a docstring but it doesn't show up in the rich documentation online: https://rich.readthedocs.io/en/stable/reference/text.html

The rich docs may need to be rebuilt.
I don't know how these docs work but maybe we need to add `TextStyle` to `rich/docs/source/reference/text.rst`:

https://github.com/Textualize/rich/blob/fd981823644ccf50d685ac9c0cfe8e1e56c9dd35/docs/source/reference/text.rst?plain=1#L1-L5
