### ISSUE TITLE
[BUG] About FileHandler

### ISSUE THREAD

**Issue by Byxs20** [Textualize/rich#3244]
**Describe the bug**

python version:3.8.10
rich version: 13.7.0

Q1:
Hi, I am trying to export a log file using `logging.FileHandler`, but I found that if I use `markup=True` it results in the exported file as shown below:

```python
import logging
from rich.logging import RichHandler

logging.basicConfig(
    level=logging.DEBUG,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[
        RichHandler(markup=True),
        logging.FileHandler("debug.txt", mode='w')
    ]
)

log = logging.getLogger()
log.info("[red] Hello World![/]")
```

![image](https://github.com/Textualize/rich/assets/64669718/de640d40-2214-45a9-9972-6f6db2951b86)

Q2:
```python
import logging
from rich.logging import RichHandler

logging.basicConfig(
    level=logging.DEBUG,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[
        RichHandler(markup=True, highlighter=None),
    ]
)

log = logging.getLogger()
log.info("[green] 1d0f936a-100e-4003-9f6d-d2298d2c8cc0 [/]")
```
Why is it that passing in `highlighter=None` when initializing `RichHandler` in the first place doesn't take effect, but instead I need to pass in `extra={'highlighter': None}` again in `log.info`, is this how it was originally designed to work?

![image](https://github.com/Textualize/rich/assets/64669718/abdff082-f89f-4c3c-a734-63ee0db1a38c)

![image](https://github.com/Textualize/rich/assets/64669718/483de75a-2725-4f03-b3a5-25e7b5611269)

**Platform**
<details>
<summary>Click to expand</summary>

╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=165 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 22                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=165, height=22),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=165,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=22,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=165, height=22)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 165                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭── <class 'rich._windows.WindowsConsoleFeatures'> ───╮
│ Windows features available.                         │
│                                                     │
│ ╭─────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=True, truecolor=True) │ │
│ ╰─────────────────────────────────────────────────╯ │
│                                                     │
│ truecolor = True                                    │
│        vt = True                                    │
╰─────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': None,                  │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'vscode',      │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Windows"

</details>

**Comment by willmcgugan** [comment]
Only `RichHandler` is aware of console markup.

See the [reference](https://rich.readthedocs.io/en/latest/reference/logging.html) for details on highlighting.

**Comment by willmcgugan** [comment]
The logging module will simply pass the string to each handler. Its not clear what the issue is from your explanation. Do you want the markup stripped from the log file?

**Comment by willmcgugan** [comment]
You could implement a handler that strips console markup. `Text.from_markup(log_message).plain` will remove markup from `log_message`
