### ISSUE TITLE
[BUG] Some colors aren't printed in bold

### ISSUE THREAD

**Issue by johndoknjas** [Textualize/rich#3275]
- I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**
Some colors printed in bold have a clear visual difference, but for others it appears there is no change. I've included some examples of these in this code:
```
from rich.console import Console
from rich.style import Style

console = Console()

def print_colors(l: list[str], message: str) -> None:
    print(message)
    for c in l:
        console.print("not bold", style=Style(color=c, bold=False))
        console.print("bold", style=Style(color=c, bold=True))
        print('\n')

print_colors(['bright_red', 'grey100', 'grey39', 'bright_magenta', 'purple'], 
             "For these colors, the bold parameter seems to make no visual difference:\n")
print_colors(['white', 'red', 'magenta'], 
             "------------------------------\nFor these colors, the bold parameter does make a difference:\n")
```
The output on my end:
![image](https://github.com/Textualize/rich/assets/32089502/7ecb964a-0d71-4a72-b757-7bf257407f3e)

**Platform**
Windows 11

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
Windows PowerShell

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by TomJGooding** [comment]
This isn't a Rich issue but rather just how your terminal emulator renders bold text. 

If you're using Windows Terminal, I think there's a setting under Appearance you can change.

**Comment by johndoknjas** [comment]
@TomJGooding Thanks, you're right - the setting is [this](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#intense-text-formatting). In case anyone else sees this, to update it I did the following:

- In the terminal clicked the drop down icon, chose Settings, and then clicked "Open JSON file" in the bottom left corner.
- In the file, navigate to the profiles/list key.
- For the terminal profile you want to update, add the `"intenseTextStyle": "bold"` pair to its object. Now it will no longer default to `"bright"`.
