### ISSUE TITLE
[BUG] `soft_wrap` does nothing when printing a `Syntax` object to console

### ISSUE THREAD

**Issue by awgymer** [Textualize/rich#3304]
- [ ] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [ ] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

I am trying to print some formatted/highlighted `markdown` to console with a `Syntax` object but it always crops the end of long lines, regardless of my settings.
 
![Screenshot 2024-03-19 at 10 51 35 am](https://github.com/Textualize/rich/assets/24782660/8e99d141-b9f3-40ac-aecd-04eb7dc507d8)

**Platform**

<details>
<summary>Click to expand</summary>

Mac OS 13.5
Using terminal app with `zsh` 
Python 3.11
rich 13.6

</details>

**Comment by willmcgugan** [comment]
You can set `word_wrap=True` on the Syntax class.

**Comment by awgymer** [comment]
This does not fix the issue:
![Screenshot 2024-03-19 at 11 53 27 am](https://github.com/Textualize/rich/assets/24782660/1b188fcc-1896-411b-b820-b119fdf3f9ad)
