### ISSUE TITLE
[BUG] Center looks strange

### ISSUE THREAD

**Issue by sus2790** [Textualize/rich#3323]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**
#### Original:
![image](https://github.com/Textualize/rich/assets/104747821/b2fe7b83-470a-441a-8a34-5b934a4fbf72)
#### Output:
![image](https://github.com/Textualize/rich/assets/104747821/ebfb55d8-ffb4-4af3-bd53-3c9b2461b056)
#### Expect:
![image](https://github.com/Textualize/rich/assets/104747821/84c802ad-0bbb-423e-a467-8078f0ff4c88)

The banner just looks werid, not much to say.

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? Windows 11
What terminal software are you using? Python 3.12.2 / Vscode 1.88.0

╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=188 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 20                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=188, height=20),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=188,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=20,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=188, height=20)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 188                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭── <class 'rich._windows.WindowsConsoleFeatures'> ───╮
│ Windows features available.                         │
│                                                     │
│ ╭─────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=True, truecolor=True) │ │
│ ╰─────────────────────────────────────────────────╯ │
│                                                     │
│ truecolor = True                                    │
│        vt = True                                    │
╰─────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': None,                  │
│     'COLORTERM': 'truecolor',      │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': 'vscode',      │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Windows"

</details>

**Comment by TomJGooding** [comment]
You probably want to use align rather than justify for mulit-line text:

```python
from rich.align import Align
from rich.console import Console
from rich.text import Text

BANNER = """
'||'  '||'
 ||    ||  .... ... ... ...    ....  ... ..
 ||''''||   '|.  |   ||'  || .|...||  ||' ''
 ||    ||    '|.|    ||    | ||       ||
.||.  .||.    '|     ||...'   '|...' .||.
           .. |      ||
            ''      ''''
"""


console = Console()
banner_text = Align.center(Text(BANNER))
console.print(banner_text)
```

**Comment by sus2790** [comment]
ohh.... I didn't notice that..
