### ISSUE TITLE
print a fixed size table row by row on the console

### ISSUE THREAD

**Issue by gsemet** [Textualize/rich#3331]
Same as #241, but with the assumption the size of each column is calculated before hand.

For example with expand=True, and a bunch of fixed size column, and ratio to compute the other colum, each column size can be known beforehand, and so, flush each row directly.

**Comment by willmcgugan** [comment]
That isn't supported by Rich, but you could build something like that.

**Comment by gsemet** [comment]
> That isn't supported by Rich, but you could build something like that.

I do not understand how i can do it?
