### ISSUE TITLE
[BUG] Terminal settings aren't restored

### ISSUE THREAD

**Issue by nineteendo** [Textualize/rich#3354]
- [X] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [X] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

### On exit

Rich doesn't restore the terminal back to its original settings when the program terminates:

```zsh
wannes@Stefans-iMac ~ % python -c "import rich.console; rich.console.Console().show_cursor(False)"
```

- Before (cursor is shown)
    ![before](https://github.com/Textualize/rich/assets/65588599/fb840991-6a0a-4667-9274-d9c7a147a5bb)
- After (cursor is hidden) **NOK**
    ![after](https://github.com/Textualize/rich/assets/65588599/852e99ba-8aeb-44f4-be58-512469d10c65)

### On suspend

Rich doesn't restore the terminal back to its original settings when the program is suspended:

```python
from rich.console import Console

console: Console = Console()
console.show_cursor(show=False)
input("Press enter")
console.show_cursor()
```

- Before (cursor is shown)
    ![1](https://github.com/Textualize/rich/assets/65588599/8557c5b6-b6fc-45b7-b2fc-e566e1f9fbdf)
- Hide cursor
    ![2](https://github.com/Textualize/rich/assets/65588599/37bfe302-fbff-4bfa-8a80-c3e7b7bac8fc)
- Suspend (cursor is hidden) **NOK**
    ![3](https://github.com/Textualize/rich/assets/65588599/43666d71-476a-45c4-bc9e-0010e171e243)
- Show cursor manually
    ![4](https://github.com/Textualize/rich/assets/65588599/538a2c30-d2a6-4c0a-83b5-32d09eab5101)
- Resume (cursor is shown) **NOK**
    ![5](https://github.com/Textualize/rich/assets/65588599/db075d1f-d6d1-41ee-8d7f-f7f163ad87b5)
- Show cursor
    ![6](https://github.com/Textualize/rich/assets/65588599/bb449eb8-0aad-4078-b594-a1e1363a98c7)

**Platform**
<details>
<summary>Click to expand</summary>

```none
╭─────────────────────── <class 'rich.console.Console'> ───────────────────────╮
│ A high level console interface.                                              │
│                                                                              │
│ ╭──────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=80 ColorSystem.EIGHT_BIT>                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│     color_system = '256'                                                     │
│         encoding = 'utf-8'                                                   │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w'               │
│                    encoding='utf-8'>                                         │
│           height = 24                                                        │
│    is_alt_screen = False                                                     │
│ is_dumb_terminal = False                                                     │
│   is_interactive = True                                                      │
│       is_jupyter = False                                                     │
│      is_terminal = True                                                      │
│   legacy_windows = False                                                     │
│         no_color = False                                                     │
│          options = ConsoleOptions(                                           │
│                        size=ConsoleDimensions(width=80, height=24),          │
│                        legacy_windows=False,                                 │
│                        min_width=1,                                          │
│                        max_width=80,                                         │
│                        is_terminal=True,                                     │
│                        encoding='utf-8',                                     │
│                        max_height=24,                                        │
│                        justify=None,                                         │
│                        overflow=None,                                        │
│                        no_wrap=False,                                        │
│                        highlight=None,                                       │
│                        markup=None,                                          │
│                        height=None                                           │
│                    )                                                         │
│            quiet = False                                                     │
│           record = False                                                     │
│         safe_box = True                                                      │
│             size = ConsoleDimensions(width=80, height=24)                    │
│        soft_wrap = False                                                     │
│           stderr = False                                                     │
│            style = None                                                      │
│         tab_size = 8                                                         │
│            width = 80                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭──────── Environment Variables ────────╮
│ {                                     │
│     'TERM': 'xterm-256color',         │
│     'COLORTERM': None,                │
│     'CLICOLOR': None,                 │
│     'NO_COLOR': None,                 │
│     'TERM_PROGRAM': 'Apple_Terminal', │
│     'COLUMNS': None,                  │
│     'LINES': None,                    │
│     'JUPYTER_COLUMNS': None,          │
│     'JUPYTER_LINES': None,            │
│     'JPY_PARENT_PID': None,           │
│     'VSCODE_VERBOSE_LOGGING': None    │
│ }                                     │
╰───────────────────────────────────────╯
platform="Darwin"
rich==13.7.1
```

</details>

**Comment by nineteendo** [comment]
For reference, here's how I handled this in my own library: https://github.com/nineteendo/ansio/blob/125577e28362ed5395c3dafed38df763fa88b8c2/ansio/__init__.py

**Comment by MrDaGree** [comment]
is there any updates to this?

**Comment by nineteendo** [comment]
Nope, this is one of the reasons why I don't use rich.

**Comment by willmcgugan** [comment]
The cursor state is something managed by the terminal. It can be modified outside of a Console object, which makes knowing how to "reset" it next to impossible. Additionally, to detect the cursor state, you would need to capture stdin,  which Rich doesn't do as it would break the many project that do capture stdin.

If you want control over the cursor state, put it in a try / finally, or a context manager.

**Comment by nineteendo** [comment]
> to detect the cursor state, you would need to capture stdin

Can I detect that without using ansi escape codes? My library will always show the cursor on exit if you chose to hide it.

**Comment by MrDaGree** [comment]
> It can be modified outside of a Console object, which makes knowing how to "reset" it next to impossible.

In my project I'm not modifying the cursor at all. I've only used `status`, `Live` tables, and progress bars. I'd expect for using things the correct way it surely can manage its cursor itself.

**Comment by willmcgugan** [comment]
Don't call input when any of these objects are running. Input will block and write to the terminal at the same time as Rich, and there is no way for Rich to detect this.

If you want a UI where you can get user input and update the screen, look in to a TUI framework like Textual.
