### ISSUE TITLE
[REQUEST] Rich progress bar changes color based on the number steps/files elapsed.

### ISSUE THREAD

**Issue by ketan96-m** [Textualize/rich#3379]
Consider posting in https://github.com/textualize/rich/discussions for feedback before raising a feature request.

Have you checked the issues for a similar suggestions?
Yes 

**How would you improve Rich?**

My application submits a bunch of transformation to a server and the rich bar gives the status of the transformation and eventual downloads. However, these transformation are prone to failures and I would like to change the color of my progress bar to indicate that some failure has occurred while other transformations continue. 

![image](https://github.com/Textualize/rich/assets/40893179/b852b7c9-b695-4775-8c0d-46c4088a965e)
I would like to change the bar color to red because it stopped just before finishing.

The `update` function does provide ways to make changes but I couldn't find a way to change the color of the bar using `BarColumn()` when passed as a keyword argument to the `update` method.
e.g 
```
progress.update(
                    progress_task,
                    progress_bar_title,
                    completed=self.current_status.files_completed,
                    bar = BarColumn(complete_style="rgb(0,0,255)",
                                             style="rgb(255,0,0)")
                )
```

**What problem does it solve for you?**

This will add more style to the progress bar when there are failures or if we can't reach 100%.

**Comment by willmcgugan** [comment]
You can override `Progress.get_renderables()` to display the progress however you like.
