### ISSUE TITLE
[BUG] Rich not playing nice when called from Reticulate

### ISSUE THREAD

**Issue by jucor** [Textualize/rich#3416]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

Hi!

When called from the "Call-python-from-R" package [Reticulate](https://rstudio.github.io/reticulate/), Rich progress bars display incorrectly:
![image](https://github.com/Textualize/rich/assets/660037/b0cc1ca8-841c-43b2-8fd9-2471bbb125f9)

I've opened a bug report at Reticulate, with  full description and minimum code example: https://github.com/rstudio/reticulate/issues/1632 

I realise this is likely some Reticulate wizardry (they remap stdout to R's console) that might be an issue, hence the bug report there, but I figured the kind developers will know much, much more about what to expect from a console, and how to get compatibility :)

Thanks a lot for any help!

**Comment by jucor** [comment]
I have found the root cause: Rstudio Console does not support cursor motion ANSI control sequences. I have opened a feature request upstream in https://github.com/rstudio/rstudio/issues/14942 , as well as a bug report for an associated issue https://github.com/rstudio/rstudio/issues/14941 .

**Comment by willmcgugan** [comment]
I don't think there is much that can be don't if Reticulate doesn't support escape sequences. They clearly support the escape sequences for color, so fingers crossed they will support more...

**Comment by jucor** [comment]
They support a subset, e.g. backspace. What they don't support is other movement :/
