### ISSUE TITLE
[BUG] github/pypi release possible wrong date?

### ISSUE THREAD

**Issue by Elypha** [Textualize/rich#3456]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

Hello,

This is not essentially a bug but just found that a merged commit https://github.com/Textualize/rich/commit/2a33a77eb78298cbed2ec0e4d9b007510caa882f from more than a year ago was actually not included in the latest release in Feb 2024.
And, for the date - since the release comment says 2023-02-28, may I know if that was just an old release drafted at 2023-02-28 and published a year later due to some reason, or it's simply a typo.
If it's the former case then that commit shouldn't be included indeed which is okay, but as it seems to me more like a typo I'm submitting this issue to ask about it.

**Platform**
<details>
<summary>Click to expand</summary>

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
```

If you're using Rich in a Jupyter Notebook, run the following snippet in a cell
and paste the output in your bug report.

```python
from rich.diagnose import report
report()
```

</details>

**Comment by TomJGooding** [comment]
The commit was **merged** in July 2024 and the [Changelog](https://github.com/Textualize/rich/blob/master/CHANGELOG.md) shows this change is unreleased?

**Comment by willmcgugan** [comment]
There was a large backlog, we're just getting caught up. Might have taken a while to be merged.
