### ISSUE TITLE
[BUG]  Kwargs unpacking issue to the Style class (not sure if other class affected)

### ISSUE THREAD

**Issue by AntsForBreakfast** [Textualize/rich#3465]
When trying to unpack style params to a Style class as kwargs i get meta error but meta is last parameter. Not sure why it happens since kwargs should not care about position

Provide a minimal code example that demonstrates the issue if you can. If the issue is visual in nature, consider posting a screenshot.
```
style_params = {}
Style(**style_params)
```

What platform (Win/Linux/Mac) are you running on? What terminal software are you using?
Linux Arch, Kitty terminal

**Comment by willmcgugan** [comment]
Can you paste the traceback.

**Comment by AntsForBreakfast** [comment]
> Can you paste the traceback.

Sorry been busy, will do today at evening

**Comment by AntsForBreakfast** [comment]
After some testing it seem to be working and its linter issue. It creates Style object but linter says: Argument of type "Color" cannot be assigner to parameter "meta" of type "Dict[str, any] | None"

**Comment by willmcgugan** [comment]
I think this is actually an error in the linter.
