### ISSUE TITLE
[REQUEST] logging exceptions: highlight paths to my code

### ISSUE THREAD

**Issue by mustafa0x** [Textualize/rich#3492]
In exceptions, can rich automatically highlight paths of my code, to be able to distinguish from code in the virtualenv or external packages. For example, in the following exception, the middle path should be highlighted.

```py
/Users/mustafa/Library/Caches/pypoetry/virtualenvs/foobar-Ra8Pwy-F-py3.12/lib/python3.12/site-packages/ninja/main.py:515
/Users/mustafa/dev/project/api.py:38
/Users/mustafa/Library/Caches/pypoetry/virtualenvs/foobar-Ra8Pwy-F-py3.12/lib/python3.12/site-packages/ninja/operation.py:121

```

Benefits

- Faster error source identification: Instantly spot errors in your code vs. external libraries.
- Improved debugging efficiency: Quickly determine if an issue is in your code or a third-party library.

edit: [claude suggested using excepthook](https://claude.site/artifacts/527c9d38-f29d-4c9d-b47c-4bf1833dd342). not sure if the solution makes sense.

**Comment by willmcgugan** [comment]
You can [exclude](https://rich.readthedocs.io/en/latest/traceback.html#suppressing-frames) known libraries from tracebacks.

**Comment by mustafa0x** [comment]
I want to exclude (or more accurately, de-emphaszie) everything in the venv.

Like vscode has a [justMyCode configuration option](https://code.visualstudio.com/docs/python/debugging#_justmycode).
