### ISSUE TITLE
[REQUEST] `progress.Progress` working with `async` code

### ISSUE THREAD

**Issue by jamesbraza** [Textualize/rich#3501]
**How would you improve Rich?**

As of `rich==13.8.1`, it looks like [`Progress` centers on a `threading.RLock`](https://github.com/Textualize/rich/blob/v13.8.1/rich/progress.py#L1086) for thread safety. This is good for multithreading users.

Much of the Python community these days uses `async` (using `asyncio` or `trio`) code. `threading.Lock`/`RLock` are suboptimal for `async` code because they block all concurrent code in an event loop.

It would be nice to:
- Support an `async`-equivalent of `Progress`
- Document the thread-safety (and potential `async` safety) of `Progress` in the docs [here](https://rich.readthedocs.io/en/stable/progress.html)

**What problem does it solve for you?**

Efficient `asyncio` code that uses `rich` for a progress bar

**Comment by willmcgugan** [comment]
AFAIK there are no issues with using progress in an async app.

The locks are there to synchronize with a thread that performs updates, and other threads launched by the dev. If they block, it is for microseconds, during which the cpu is 100% utilized and the async loop wouldn't be able to switch anyway.

In other words, the way Rich uses threading locks its no less optimal that any code between `await` keywords in an async app.
