### ISSUE TITLE
[BUG] traceback not captured

### ISSUE THREAD

**Issue by juneleung** [Textualize/rich#3544]
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

**Describe the bug**

I tried to add the ```from rich.traceback import install``` in the code and run with ```os.system()```, traceback error not be captured and shown in rich colorize display. as shown:
![image](https://github.com/user-attachments/assets/3168d38f-32fe-421d-abff-4d5ced619bb8)

I tried to run an error code like try a not existing function, the traceback displays perfectly.
![image](https://github.com/user-attachments/assets/30e2c266-0335-4b3a-b06a-b5e5c6e2b77b)

How to make all the traceback colorized? Thanks!

**Platform**
<details>
<summary>Click to expand</summary>

Arch Linux, VSCode

```
python -m rich.diagnose
pip freeze | grep rich
```
![image](https://github.com/user-attachments/assets/60543656-a98c-4985-9849-6d3e66712f25)
![image](https://github.com/user-attachments/assets/36611e01-183a-43ea-9973-115530d94571)

</details>

**Comment by willmcgugan** [comment]
The error is occurring in the command. There is no way for Rich to capture a traceback from a different process. Can you not add the traceback handler to your train module?
