### ISSUE TITLE
[REQUEST] Could you please add images to the rich docs?

### ISSUE THREAD

**Issue by misrasaurabh1** [Textualize/rich#3547]
**How would you improve Rich?**

I am a new user to rich. I am a fan, it has improved codeflash.ai 's look and feel quite a lot.

One problem I have is that from the official docs, i don't really understand what a particular feature will do just from looking at the docs. Since rich is such a visual library, adding images to all the examples will greatly help developers understand and value rich.

**What problem does it solve for you?**

I don't understand what feature could be useful to me, because i don't know what the feature looks like. It limits new user and existing user adoption.

**Comment by willmcgugan** [comment]
What would you like to see images of?

**Comment by misrasaurabh1** [comment]
> What would you like to see images of?
I would like to see "if i implemented the code example mentioned in the docs, then how would the resulting output look like.".
Without this context I have a hard time understanding what a particular feature means in the doc.

**Comment by willmcgugan** [comment]
There are numerous examples of output in the docs, as html. I'm sure there could be more, but frankly you can see the output of most thing by copying a few lines in to your terminal.

If you would like to PR for screenshots in the docs, feel free, but this is very low priority considering you are the first to ask.
