### ISSUE TITLE
uv Rich Installation error : No executables are provided by rich

### ISSUE THREAD

**Issue by kb-cov** [Textualize/rich#3555]
Hi, I am trying to install Rich using the new uv package manager.....when trying to install I get the following error message:

➜  ~ uv tool install rich
Resolved 4 packages in 113ms
Installed 4 packages in 36ms
 + markdown-it-py==3.0.0
 + mdurl==0.1.2
 + pygments==2.18.0
 + rich==13.9.4
No executables are provided by `rich`

When I try to run it in terminal using uvx I get....

➜  ~ uvx rich .zshrc
Installed 4 packages in 33ms
The executable `rich` was not found.
warning: Package `rich` does not provide any executables.

I'm on MacOS Sequoia 15.1 and using latest uv version 0.5.1.....I'm not sure if this is a uv issue or a problem with the Rich package itself.  Any ideas what may be causing this error message ?

Thanks...

**Comment by TomJGooding** [comment]
I'm not yet familiar with `uv`, but I think the problem is that you're trying to install the `rich` _library_ as a _tool_?

> Tools are Python packages that provide command-line interfaces.

https://docs.astral.sh/uv/concepts/tools/

**Comment by kb-cov** [comment]
@TomJGooding - you are absolutely right....I have had a total brain dead moment on this....I've been using Rich on the command line for so long (installed via PIPX), I had convinced myself that because the command is actually `rich` I assumed I needed to install Rich, when in fact I actually needed to install Rich-CLI.....apologies for wasting your time and thank you for pointing out my obvious mistake.  As an aside, uv is pretty great so far - have moved from using pyenv, pipx, pip and python's venv module to doing it all in uv and its nice to have all that functionality in one tool....might be worth giving it a go...

**Comment by kb-cov** [comment]
rich-cli now successfully installed through uv....thank you.
